// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_pooling2d_cl_array_ap_ufixed_8u_array_ap_ufixed_6_0_4_0_0_8u_config9_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer9_out_din,
        layer9_out_num_data_valid,
        layer9_out_fifo_cap,
        layer9_out_full_n,
        layer9_out_write,
        start_out,
        start_write,
        layer8_out_dout,
        layer8_out_num_data_valid,
        layer8_out_fifo_cap,
        layer8_out_empty_n,
        layer8_out_read
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [47:0] layer9_out_din;
input  [2:0] layer9_out_num_data_valid;
input  [2:0] layer9_out_fifo_cap;
input   layer9_out_full_n;
output   layer9_out_write;
output   start_out;
output   start_write;
input  [47:0] layer8_out_dout;
input  [4:0] layer8_out_num_data_valid;
input  [4:0] layer8_out_fifo_cap;
input   layer8_out_empty_n;
output   layer8_out_read;

reg ap_idle;
reg layer9_out_write;
reg start_write;
reg layer8_out_read;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    internal_ap_ready;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state4_pp0_stage1_iter1;
reg   [0:0] icmp_ln55_reg_1534;
reg   [0:0] icmp_ln55_reg_1534_pp0_iter1_reg;
reg   [0:0] and_ln55_1_reg_1669;
reg    ap_predicate_op231_write_state6;
reg    ap_block_state6_pp0_stage1_iter2;
reg    ap_block_pp0_stage1_subdone;
reg   [0:0] icmp_ln109_reg_1514;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [31:0] sY;
reg   [31:0] pY;
reg   [31:0] pX;
reg   [31:0] sX;
reg   [5:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1;
reg   [5:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel;
reg   [5:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_13;
reg   [5:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_12;
reg   [5:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_11;
reg   [5:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_10;
reg   [5:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_9;
reg   [5:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_8;
reg   [5:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_7;
reg   [5:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_6;
reg   [5:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_5;
reg   [5:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_4;
reg   [5:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_3;
reg   [5:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_2;
reg   [5:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_1;
reg   [5:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap;
reg    void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_7_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_7_we0;
wire   [5:0] void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_7_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_6_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_6_we0;
wire   [5:0] void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_6_d0;
wire   [5:0] void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_6_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_5_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_5_we0;
wire   [5:0] void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_5_d0;
wire   [5:0] void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_5_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_4_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_4_we0;
wire   [5:0] void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_4_d0;
wire   [5:0] void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_4_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_3_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_3_we0;
wire   [5:0] void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_3_d0;
wire   [5:0] void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_3_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_2_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_2_we0;
wire   [5:0] void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_2_d0;
wire   [5:0] void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_2_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_1_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_1_we0;
wire   [5:0] void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_1_d0;
wire   [5:0] void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_1_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_we0;
wire   [5:0] void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_d0;
wire   [5:0] void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_q0;
reg    layer8_out_blk_n;
wire    ap_block_pp0_stage0;
reg    layer9_out_blk_n;
wire    ap_block_pp0_stage1;
wire   [0:0] icmp_ln109_fu_202_p2;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln109_reg_1514_pp0_iter1_reg;
reg   [31:0] pX_load_reg_1518;
wire   [31:0] add_ln76_fu_218_p2;
reg   [31:0] add_ln76_reg_1523;
reg   [31:0] sX_load_reg_1529;
reg    ap_block_pp0_stage1_11001;
wire   [0:0] icmp_ln55_fu_233_p2;
wire   [0:0] icmp_ln55_3_fu_239_p2;
reg   [0:0] icmp_ln55_3_reg_1539;
wire   [0:0] icmp_ln76_fu_244_p2;
reg   [0:0] icmp_ln76_reg_1544;
reg   [0:0] icmp_ln76_reg_1544_pp0_iter1_reg;
wire   [31:0] add_ln80_fu_253_p2;
reg   [31:0] add_ln80_reg_1548;
wire   [5:0] trunc_ln115_fu_259_p1;
reg   [5:0] trunc_ln115_reg_1554;
reg   [5:0] trunc_ln115_6_reg_1560;
reg   [5:0] trunc_ln115_7_reg_1566;
reg   [5:0] trunc_ln115_9_reg_1572;
reg   [5:0] trunc_ln115_s_reg_1578;
reg   [5:0] trunc_ln115_1_reg_1584;
reg   [5:0] trunc_ln115_2_reg_1590;
reg   [5:0] trunc_ln115_3_reg_1596;
reg   [5:0] p_4_reg_1602;
reg   [5:0] p_5_reg_1608;
reg   [5:0] p_6_reg_1614;
reg   [5:0] p_1_reg_1620;
reg   [5:0] p_2_reg_1626;
reg   [5:0] p_3_reg_1632;
reg   [5:0] p_s_reg_1638;
reg   [5:0] p_0_reg_1644;
wire   [31:0] add_ln91_fu_425_p2;
reg   [31:0] add_ln91_reg_1650;
wire   [0:0] icmp_ln80_fu_442_p2;
reg   [0:0] icmp_ln80_reg_1655;
reg   [31:0] grp_load_fu_184_p1;
reg   [31:0] sY_load_1_reg_1659;
wire   [0:0] grp_fu_188_p2;
reg   [0:0] icmp_ln86_reg_1664;
wire   [0:0] and_ln55_1_fu_606_p2;
wire   [10:0] select_ln66_fu_654_p3;
reg   [10:0] select_ln66_reg_1673;
wire   [10:0] select_ln66_9_fu_674_p3;
reg   [10:0] select_ln66_9_reg_1679;
wire   [10:0] select_ln66_11_fu_724_p3;
reg   [10:0] select_ln66_11_reg_1685;
wire   [10:0] select_ln66_12_fu_744_p3;
reg   [10:0] select_ln66_12_reg_1691;
wire   [10:0] select_ln66_14_fu_794_p3;
reg   [10:0] select_ln66_14_reg_1697;
wire   [10:0] select_ln66_15_fu_814_p3;
reg   [10:0] select_ln66_15_reg_1703;
wire   [10:0] select_ln66_17_fu_864_p3;
reg   [10:0] select_ln66_17_reg_1709;
wire   [10:0] select_ln66_18_fu_884_p3;
reg   [10:0] select_ln66_18_reg_1715;
wire   [10:0] select_ln66_20_fu_934_p3;
reg   [10:0] select_ln66_20_reg_1721;
wire   [10:0] select_ln66_21_fu_954_p3;
reg   [10:0] select_ln66_21_reg_1727;
wire   [10:0] select_ln66_23_fu_1004_p3;
reg   [10:0] select_ln66_23_reg_1733;
wire   [10:0] select_ln66_24_fu_1024_p3;
reg   [10:0] select_ln66_24_reg_1739;
wire   [10:0] select_ln66_26_fu_1074_p3;
reg   [10:0] select_ln66_26_reg_1745;
wire   [10:0] select_ln66_27_fu_1094_p3;
reg   [10:0] select_ln66_27_reg_1751;
wire   [10:0] select_ln66_29_fu_1144_p3;
reg   [10:0] select_ln66_29_reg_1757;
wire   [10:0] select_ln66_30_fu_1164_p3;
reg   [10:0] select_ln66_30_reg_1763;
wire   [31:0] add_ln86_fu_1189_p2;
reg   [31:0] add_ln86_reg_1769;
wire   [5:0] p_Val2_s_fu_1228_p3;
reg   [5:0] p_Val2_s_reg_1774;
wire   [5:0] p_Val2_108_fu_1264_p3;
reg   [5:0] p_Val2_108_reg_1779;
wire   [5:0] p_Val2_109_fu_1300_p3;
reg   [5:0] p_Val2_109_reg_1784;
wire   [5:0] p_Val2_110_fu_1336_p3;
reg   [5:0] p_Val2_110_reg_1789;
wire   [5:0] p_Val2_111_fu_1372_p3;
reg   [5:0] p_Val2_111_reg_1794;
wire   [5:0] p_Val2_112_fu_1408_p3;
reg   [5:0] p_Val2_112_reg_1799;
wire   [5:0] p_Val2_113_fu_1444_p3;
reg   [5:0] p_Val2_113_reg_1804;
wire   [5:0] p_Val2_114_fu_1480_p3;
reg   [5:0] p_Val2_114_reg_1809;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [31:0] ap_phi_mux_storemerge_phi_fu_177_p4;
reg   [31:0] ap_phi_reg_pp0_iter2_storemerge_reg_173;
wire   [31:0] ap_phi_reg_pp0_iter0_storemerge_reg_173;
reg   [31:0] ap_phi_reg_pp0_iter1_storemerge_reg_173;
reg   [31:0] ap_sig_allocacmp_sY_load_1;
reg   [31:0] ap_sig_allocacmp_pY_load_1;
reg   [31:0] ap_sig_allocacmp_pX_load;
reg   [31:0] ap_sig_allocacmp_sX_load;
reg   [4:0] indvar_flatten_fu_156;
wire   [4:0] add_ln109_fu_208_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_indvar_flatten_load;
reg    ap_block_pp0_stage1_01001;
wire   [31:0] select_ln91_fu_418_p3;
wire   [0:0] icmp_ln55_2_fu_595_p2;
wire   [0:0] and_ln55_fu_601_p2;
wire   [10:0] pool_window_V_fu_612_p3;
wire   [10:0] pool_window_V_1_fu_620_p3;
wire   [0:0] icmp_ln1651_fu_642_p2;
wire   [0:0] xor_ln1651_fu_648_p2;
wire   [10:0] pool_window_V_2_fu_627_p3;
wire   [10:0] pool_window_V_3_fu_635_p3;
wire   [0:0] icmp_ln1651_9_fu_662_p2;
wire   [0:0] xor_ln1651_9_fu_668_p2;
wire   [10:0] pool_window_V_4_fu_682_p3;
wire   [10:0] pool_window_V_5_fu_690_p3;
wire   [0:0] icmp_ln1651_11_fu_712_p2;
wire   [0:0] xor_ln1651_11_fu_718_p2;
wire   [10:0] pool_window_V_6_fu_697_p3;
wire   [10:0] pool_window_V_7_fu_705_p3;
wire   [0:0] icmp_ln1651_12_fu_732_p2;
wire   [0:0] xor_ln1651_12_fu_738_p2;
wire   [10:0] pool_window_V_8_fu_752_p3;
wire   [10:0] pool_window_V_9_fu_760_p3;
wire   [0:0] icmp_ln1651_14_fu_782_p2;
wire   [0:0] xor_ln1651_14_fu_788_p2;
wire   [10:0] pool_window_V_10_fu_767_p3;
wire   [10:0] pool_window_V_11_fu_775_p3;
wire   [0:0] icmp_ln1651_15_fu_802_p2;
wire   [0:0] xor_ln1651_15_fu_808_p2;
wire   [10:0] pool_window_V_12_fu_822_p3;
wire   [10:0] pool_window_V_13_fu_830_p3;
wire   [0:0] icmp_ln1651_17_fu_852_p2;
wire   [0:0] xor_ln1651_17_fu_858_p2;
wire   [10:0] pool_window_V_14_fu_837_p3;
wire   [10:0] pool_window_V_15_fu_845_p3;
wire   [0:0] icmp_ln1651_18_fu_872_p2;
wire   [0:0] xor_ln1651_18_fu_878_p2;
wire   [10:0] pool_window_V_16_fu_892_p3;
wire   [10:0] pool_window_V_17_fu_900_p3;
wire   [0:0] icmp_ln1651_20_fu_922_p2;
wire   [0:0] xor_ln1651_20_fu_928_p2;
wire   [10:0] pool_window_V_18_fu_907_p3;
wire   [10:0] pool_window_V_19_fu_915_p3;
wire   [0:0] icmp_ln1651_21_fu_942_p2;
wire   [0:0] xor_ln1651_21_fu_948_p2;
wire   [10:0] pool_window_V_20_fu_962_p3;
wire   [10:0] pool_window_V_21_fu_970_p3;
wire   [0:0] icmp_ln1651_23_fu_992_p2;
wire   [0:0] xor_ln1651_23_fu_998_p2;
wire   [10:0] pool_window_V_22_fu_977_p3;
wire   [10:0] pool_window_V_23_fu_985_p3;
wire   [0:0] icmp_ln1651_24_fu_1012_p2;
wire   [0:0] xor_ln1651_24_fu_1018_p2;
wire   [10:0] pool_window_V_24_fu_1032_p3;
wire   [10:0] pool_window_V_25_fu_1040_p3;
wire   [0:0] icmp_ln1651_26_fu_1062_p2;
wire   [0:0] xor_ln1651_26_fu_1068_p2;
wire   [10:0] pool_window_V_26_fu_1047_p3;
wire   [10:0] pool_window_V_27_fu_1055_p3;
wire   [0:0] icmp_ln1651_27_fu_1082_p2;
wire   [0:0] xor_ln1651_27_fu_1088_p2;
wire   [10:0] pool_window_V_28_fu_1102_p3;
wire   [10:0] pool_window_V_29_fu_1110_p3;
wire   [0:0] icmp_ln1651_29_fu_1132_p2;
wire   [0:0] xor_ln1651_29_fu_1138_p2;
wire   [10:0] pool_window_V_30_fu_1117_p3;
wire   [10:0] pool_window_V_31_fu_1125_p3;
wire   [0:0] icmp_ln1651_30_fu_1152_p2;
wire   [0:0] xor_ln1651_30_fu_1158_p2;
wire   [31:0] select_ln86_fu_1182_p3;
wire   [0:0] icmp_ln1651_10_fu_1200_p2;
wire   [0:0] xor_ln1651_10_fu_1204_p2;
wire   [5:0] tmp_1_fu_1210_p4;
wire   [5:0] tmp_2_fu_1219_p4;
wire   [0:0] icmp_ln1651_13_fu_1236_p2;
wire   [0:0] xor_ln1651_13_fu_1240_p2;
wire   [5:0] tmp_4_fu_1246_p4;
wire   [5:0] tmp_5_fu_1255_p4;
wire   [0:0] icmp_ln1651_16_fu_1272_p2;
wire   [0:0] xor_ln1651_16_fu_1276_p2;
wire   [5:0] tmp_7_fu_1282_p4;
wire   [5:0] tmp_8_fu_1291_p4;
wire   [0:0] icmp_ln1651_19_fu_1308_p2;
wire   [0:0] xor_ln1651_19_fu_1312_p2;
wire   [5:0] tmp_10_fu_1318_p4;
wire   [5:0] tmp_11_fu_1327_p4;
wire   [0:0] icmp_ln1651_22_fu_1344_p2;
wire   [0:0] xor_ln1651_22_fu_1348_p2;
wire   [5:0] tmp_13_fu_1354_p4;
wire   [5:0] tmp_14_fu_1363_p4;
wire   [0:0] icmp_ln1651_25_fu_1380_p2;
wire   [0:0] xor_ln1651_25_fu_1384_p2;
wire   [5:0] tmp_16_fu_1390_p4;
wire   [5:0] tmp_17_fu_1399_p4;
wire   [0:0] icmp_ln1651_28_fu_1416_p2;
wire   [0:0] xor_ln1651_28_fu_1420_p2;
wire   [5:0] tmp_19_fu_1426_p4;
wire   [5:0] tmp_20_fu_1435_p4;
wire   [0:0] icmp_ln1651_31_fu_1452_p2;
wire   [0:0] xor_ln1651_31_fu_1456_p2;
wire   [5:0] tmp_22_fu_1462_p4;
wire   [5:0] tmp_23_fu_1471_p4;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [1:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to2;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_378;
reg    ap_condition_376;
reg    ap_condition_186;
reg    ap_condition_1158;
reg    ap_condition_1164;
reg    ap_condition_1168;
reg    ap_condition_450;
reg    ap_condition_289;
reg    ap_condition_1176;
reg    ap_condition_1180;
reg    ap_condition_284;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 sY = 32'd0;
#0 pY = 32'd0;
#0 pX = 32'd0;
#0 sX = 32'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1 = 6'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel = 6'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_13 = 6'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_12 = 6'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_11 = 6'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_10 = 6'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_9 = 6'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_8 = 6'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_7 = 6'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_6 = 6'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_5 = 6'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_4 = 6'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_3 = 6'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_2 = 6'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_1 = 6'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap = 6'd0;
#0 ap_done_reg = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
end

myproject_pooling2d_cl_array_ap_ufixed_8u_array_ap_ufixed_6_0_4_0_0_8u_config9_s_void_prcU #(
    .DataWidth( 6 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(2'd3),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_7_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_7_we0),
    .d0(trunc_ln115_fu_259_p1),
    .q0(void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_7_q0)
);

myproject_pooling2d_cl_array_ap_ufixed_8u_array_ap_ufixed_6_0_4_0_0_8u_config9_s_void_prcU #(
    .DataWidth( 6 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(2'd3),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_6_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_6_we0),
    .d0(void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_6_d0),
    .q0(void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_6_q0)
);

myproject_pooling2d_cl_array_ap_ufixed_8u_array_ap_ufixed_6_0_4_0_0_8u_config9_s_void_prcU #(
    .DataWidth( 6 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(2'd3),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_5_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_5_we0),
    .d0(void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_5_d0),
    .q0(void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_5_q0)
);

myproject_pooling2d_cl_array_ap_ufixed_8u_array_ap_ufixed_6_0_4_0_0_8u_config9_s_void_prcU #(
    .DataWidth( 6 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(2'd3),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_4_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_4_we0),
    .d0(void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_4_d0),
    .q0(void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_4_q0)
);

myproject_pooling2d_cl_array_ap_ufixed_8u_array_ap_ufixed_6_0_4_0_0_8u_config9_s_void_prcU #(
    .DataWidth( 6 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(2'd3),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_3_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_3_we0),
    .d0(void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_3_d0),
    .q0(void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_3_q0)
);

myproject_pooling2d_cl_array_ap_ufixed_8u_array_ap_ufixed_6_0_4_0_0_8u_config9_s_void_prcU #(
    .DataWidth( 6 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(2'd3),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_2_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_2_we0),
    .d0(void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_2_d0),
    .q0(void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_2_q0)
);

myproject_pooling2d_cl_array_ap_ufixed_8u_array_ap_ufixed_6_0_4_0_0_8u_config9_s_void_prcU #(
    .DataWidth( 6 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(2'd3),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_1_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_1_we0),
    .d0(void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_1_d0),
    .q0(void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_1_q0)
);

myproject_pooling2d_cl_array_ap_ufixed_8u_array_ap_ufixed_6_0_4_0_0_8u_config9_s_void_prcU #(
    .DataWidth( 6 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(2'd3),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_we0),
    .d0(void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_d0),
    .q0(void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_q0)
);

myproject_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_376)) begin
        if ((1'b1 == ap_condition_378)) begin
            ap_phi_reg_pp0_iter2_storemerge_reg_173 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_storemerge_reg_173 <= ap_phi_reg_pp0_iter1_storemerge_reg_173;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_450)) begin
        if ((icmp_ln109_fu_202_p2 == 1'd0)) begin
            indvar_flatten_fu_156 <= add_ln109_fu_208_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_156 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_289)) begin
        if ((icmp_ln76_reg_1544 == 1'd1)) begin
            pX <= 32'd0;
        end else if ((icmp_ln76_reg_1544 == 1'd0)) begin
            pX <= add_ln76_reg_1523;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1176)) begin
        if ((icmp_ln80_reg_1655 == 1'd1)) begin
            pY <= 32'd0;
        end else if ((icmp_ln80_reg_1655 == 1'd0)) begin
            pY <= add_ln80_reg_1548;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if ((1'b1 == ap_condition_284)) begin
            sX <= 32'd0;
        end else if ((1'b1 == ap_condition_1180)) begin
            sX <= add_ln91_reg_1650;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln109_fu_202_p2 == 1'd0))) begin
        add_ln76_reg_1523 <= add_ln76_fu_218_p2;
        pX_load_reg_1518 <= ap_sig_allocacmp_pX_load;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_reg_1514 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln76_fu_244_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln80_reg_1548 <= add_ln80_fu_253_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln80_reg_1655 == 1'd0) & (icmp_ln76_reg_1544 == 1'd1) & (icmp_ln109_reg_1514_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln86_reg_1769 <= add_ln86_fu_1189_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln76_reg_1544 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln91_reg_1650 <= add_ln91_fu_425_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln55_reg_1534 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        and_ln55_1_reg_1669 <= and_ln55_1_fu_606_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln55_reg_1534_pp0_iter1_reg <= icmp_ln55_reg_1534;
        icmp_ln76_reg_1544_pp0_iter1_reg <= icmp_ln76_reg_1544;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_phi_reg_pp0_iter1_storemerge_reg_173 <= ap_phi_reg_pp0_iter0_storemerge_reg_173;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln109_reg_1514 <= icmp_ln109_fu_202_p2;
        icmp_ln109_reg_1514_pp0_iter1_reg <= icmp_ln109_reg_1514;
        p_0_reg_1644 <= void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_q0;
        p_1_reg_1620 <= void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_4_q0;
        p_2_reg_1626 <= void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_3_q0;
        p_3_reg_1632 <= void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_2_q0;
        p_4_reg_1602 <= void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_7_q0;
        p_5_reg_1608 <= void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_6_q0;
        p_6_reg_1614 <= void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_5_q0;
        p_s_reg_1638 <= void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_1_q0;
        trunc_ln115_1_reg_1584 <= {{layer8_out_dout[23:18]}};
        trunc_ln115_2_reg_1590 <= {{layer8_out_dout[29:24]}};
        trunc_ln115_3_reg_1596 <= {{layer8_out_dout[35:30]}};
        trunc_ln115_6_reg_1560 <= {{layer8_out_dout[41:36]}};
        trunc_ln115_7_reg_1566 <= {{layer8_out_dout[47:42]}};
        trunc_ln115_9_reg_1572 <= {{layer8_out_dout[11:6]}};
        trunc_ln115_reg_1554 <= trunc_ln115_fu_259_p1;
        trunc_ln115_s_reg_1578 <= {{layer8_out_dout[17:12]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_reg_1514 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln55_fu_233_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        icmp_ln55_3_reg_1539 <= icmp_ln55_3_fu_239_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_reg_1514 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        icmp_ln55_reg_1534 <= icmp_ln55_fu_233_p2;
        icmp_ln76_reg_1544 <= icmp_ln76_fu_244_p2;
        sX_load_reg_1529 <= ap_sig_allocacmp_sX_load;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln76_reg_1544 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln80_reg_1655 <= icmp_ln80_fu_442_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_reg_1514 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln80_fu_442_p2 == 1'd0) & (icmp_ln76_reg_1544 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln86_reg_1664 <= grp_fu_188_p2;
        sY_load_1_reg_1659 <= grp_load_fu_184_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln55_1_reg_1669) & (icmp_ln55_reg_1534_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_Val2_108_reg_1779 <= p_Val2_108_fu_1264_p3;
        p_Val2_109_reg_1784 <= p_Val2_109_fu_1300_p3;
        p_Val2_110_reg_1789 <= p_Val2_110_fu_1336_p3;
        p_Val2_111_reg_1794 <= p_Val2_111_fu_1372_p3;
        p_Val2_112_reg_1799 <= p_Val2_112_fu_1408_p3;
        p_Val2_113_reg_1804 <= p_Val2_113_fu_1444_p3;
        p_Val2_114_reg_1809 <= p_Val2_114_fu_1480_p3;
        p_Val2_s_reg_1774 <= p_Val2_s_fu_1228_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap <= trunc_ln115_7_reg_1566;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_1 <= trunc_ln115_6_reg_1560;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_10 <= p_3_reg_1632;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_11 <= p_2_reg_1626;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_12 <= p_1_reg_1620;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_13 <= p_6_reg_1614;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_2 <= trunc_ln115_3_reg_1596;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_3 <= trunc_ln115_2_reg_1590;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_4 <= trunc_ln115_1_reg_1584;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_5 <= trunc_ln115_s_reg_1578;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_6 <= trunc_ln115_9_reg_1572;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_7 <= trunc_ln115_reg_1554;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_8 <= p_0_reg_1644;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_9 <= p_s_reg_1638;
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel <= p_5_reg_1608;
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1 <= p_4_reg_1602;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln76_reg_1544_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sY <= ap_phi_mux_storemerge_phi_fu_177_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'd1 == and_ln55_1_fu_606_p2) & (icmp_ln55_reg_1534 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        select_ln66_11_reg_1685[10 : 5] <= select_ln66_11_fu_724_p3[10 : 5];
        select_ln66_12_reg_1691[10 : 5] <= select_ln66_12_fu_744_p3[10 : 5];
        select_ln66_14_reg_1697[10 : 5] <= select_ln66_14_fu_794_p3[10 : 5];
        select_ln66_15_reg_1703[10 : 5] <= select_ln66_15_fu_814_p3[10 : 5];
        select_ln66_17_reg_1709[10 : 5] <= select_ln66_17_fu_864_p3[10 : 5];
        select_ln66_18_reg_1715[10 : 5] <= select_ln66_18_fu_884_p3[10 : 5];
        select_ln66_20_reg_1721[10 : 5] <= select_ln66_20_fu_934_p3[10 : 5];
        select_ln66_21_reg_1727[10 : 5] <= select_ln66_21_fu_954_p3[10 : 5];
        select_ln66_23_reg_1733[10 : 5] <= select_ln66_23_fu_1004_p3[10 : 5];
        select_ln66_24_reg_1739[10 : 5] <= select_ln66_24_fu_1024_p3[10 : 5];
        select_ln66_26_reg_1745[10 : 5] <= select_ln66_26_fu_1074_p3[10 : 5];
        select_ln66_27_reg_1751[10 : 5] <= select_ln66_27_fu_1094_p3[10 : 5];
        select_ln66_29_reg_1757[10 : 5] <= select_ln66_29_fu_1144_p3[10 : 5];
        select_ln66_30_reg_1763[10 : 5] <= select_ln66_30_fu_1164_p3[10 : 5];
        select_ln66_9_reg_1679[10 : 5] <= select_ln66_9_fu_674_p3[10 : 5];
        select_ln66_reg_1673[10 : 5] <= select_ln66_fu_654_p3[10 : 5];
    end
end

always @ (*) begin
    if (((icmp_ln109_reg_1514 == 1'd1) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to2 = 1'b1;
    end else begin
        ap_idle_pp0_1to2 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln80_reg_1655 == 1'd0) & (icmp_ln76_reg_1544_pp0_iter1_reg == 1'd1) & (icmp_ln109_reg_1514_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_storemerge_phi_fu_177_p4 = add_ln86_reg_1769;
    end else begin
        ap_phi_mux_storemerge_phi_fu_177_p4 = ap_phi_reg_pp0_iter2_storemerge_reg_173;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 5'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_156;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_186)) begin
        if ((icmp_ln76_reg_1544 == 1'd1)) begin
            ap_sig_allocacmp_pX_load = 32'd0;
        end else if ((icmp_ln76_reg_1544 == 1'd0)) begin
            ap_sig_allocacmp_pX_load = add_ln76_reg_1523;
        end else begin
            ap_sig_allocacmp_pX_load = pX;
        end
    end else begin
        ap_sig_allocacmp_pX_load = pX;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1158)) begin
        if ((icmp_ln80_reg_1655 == 1'd1)) begin
            ap_sig_allocacmp_pY_load_1 = 32'd0;
        end else if ((icmp_ln80_reg_1655 == 1'd0)) begin
            ap_sig_allocacmp_pY_load_1 = add_ln80_reg_1548;
        end else begin
            ap_sig_allocacmp_pY_load_1 = pY;
        end
    end else begin
        ap_sig_allocacmp_pY_load_1 = pY;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln76_reg_1544 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_sig_allocacmp_sX_load = add_ln91_reg_1650;
    end else begin
        ap_sig_allocacmp_sX_load = sX;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln76_reg_1544_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_sY_load_1 = ap_phi_mux_storemerge_phi_fu_177_p4;
    end else begin
        ap_sig_allocacmp_sY_load_1 = sY;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if ((1'b1 == ap_condition_1168)) begin
            grp_load_fu_184_p1 = sY;
        end else if ((1'b1 == ap_condition_1164)) begin
            grp_load_fu_184_p1 = ap_sig_allocacmp_sY_load_1;
        end else begin
            grp_load_fu_184_p1 = 'bx;
        end
    end else begin
        grp_load_fu_184_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer8_out_blk_n = layer8_out_empty_n;
    end else begin
        layer8_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer8_out_read = 1'b1;
    end else begin
        layer8_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_predicate_op231_write_state6 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        layer9_out_blk_n = layer9_out_full_n;
    end else begin
        layer9_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_predicate_op231_write_state6 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        layer9_out_write = 1'b1;
    end else begin
        layer9_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_1_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_1_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_2_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_2_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_3_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_3_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_4_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_4_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_5_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_5_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_6_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_6_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_7_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_7_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to2 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln109_fu_208_p2 = (ap_sig_allocacmp_indvar_flatten_load + 5'd1);

assign add_ln76_fu_218_p2 = (ap_sig_allocacmp_pX_load + 32'd1);

assign add_ln80_fu_253_p2 = (ap_sig_allocacmp_pY_load_1 + 32'd1);

assign add_ln86_fu_1189_p2 = (sY_load_1_reg_1659 + select_ln86_fu_1182_p3);

assign add_ln91_fu_425_p2 = (sX_load_reg_1529 + select_ln91_fu_418_p3);

assign and_ln55_1_fu_606_p2 = (grp_fu_188_p2 & and_ln55_fu_601_p2);

assign and_ln55_fu_601_p2 = (icmp_ln55_3_reg_1539 & icmp_ln55_2_fu_595_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (ap_done_reg == 1'b1)) | ((layer8_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (ap_done_reg == 1'b1)) | ((layer8_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001 = ((ap_predicate_op231_write_state6 == 1'b1) & (layer9_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((ap_predicate_op231_write_state6 == 1'b1) & (layer9_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_predicate_op231_write_state6 == 1'b1) & (layer9_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = (layer8_out_empty_n == 1'b0);
end

assign ap_block_state4_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state6_pp0_stage1_iter2 = ((ap_predicate_op231_write_state6 == 1'b1) & (layer9_out_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_1158 = ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln76_reg_1544 == 1'd1) & (icmp_ln109_reg_1514_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

always @ (*) begin
    ap_condition_1164 = ((icmp_ln109_reg_1514 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln80_fu_442_p2 == 1'd0) & (icmp_ln76_reg_1544 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_1168 = ((1'b0 == ap_block_pp0_stage1) & (icmp_ln55_reg_1534 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

always @ (*) begin
    ap_condition_1176 = ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln76_reg_1544 == 1'd1) & (icmp_ln109_reg_1514_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

always @ (*) begin
    ap_condition_1180 = ((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln76_reg_1544 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

always @ (*) begin
    ap_condition_186 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_284 = ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln76_reg_1544 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_289 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_376 = ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

always @ (*) begin
    ap_condition_378 = ((icmp_ln80_reg_1655 == 1'd1) & (icmp_ln76_reg_1544 == 1'd1) & (icmp_ln109_reg_1514_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_condition_450 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_phi_reg_pp0_iter0_storemerge_reg_173 = 'bx;

always @ (*) begin
    ap_predicate_op231_write_state6 = ((1'd1 == and_ln55_1_reg_1669) & (icmp_ln55_reg_1534_pp0_iter1_reg == 1'd1));
end

assign ap_ready = internal_ap_ready;

assign grp_fu_188_p2 = ((grp_load_fu_184_p1 == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln109_fu_202_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln1651_10_fu_1200_p2 = ((select_ln66_reg_1673 < select_ln66_9_reg_1679) ? 1'b1 : 1'b0);

assign icmp_ln1651_11_fu_712_p2 = ((pool_window_V_4_fu_682_p3 < pool_window_V_5_fu_690_p3) ? 1'b1 : 1'b0);

assign icmp_ln1651_12_fu_732_p2 = ((pool_window_V_6_fu_697_p3 < pool_window_V_7_fu_705_p3) ? 1'b1 : 1'b0);

assign icmp_ln1651_13_fu_1236_p2 = ((select_ln66_11_reg_1685 < select_ln66_12_reg_1691) ? 1'b1 : 1'b0);

assign icmp_ln1651_14_fu_782_p2 = ((pool_window_V_8_fu_752_p3 < pool_window_V_9_fu_760_p3) ? 1'b1 : 1'b0);

assign icmp_ln1651_15_fu_802_p2 = ((pool_window_V_10_fu_767_p3 < pool_window_V_11_fu_775_p3) ? 1'b1 : 1'b0);

assign icmp_ln1651_16_fu_1272_p2 = ((select_ln66_14_reg_1697 < select_ln66_15_reg_1703) ? 1'b1 : 1'b0);

assign icmp_ln1651_17_fu_852_p2 = ((pool_window_V_12_fu_822_p3 < pool_window_V_13_fu_830_p3) ? 1'b1 : 1'b0);

assign icmp_ln1651_18_fu_872_p2 = ((pool_window_V_14_fu_837_p3 < pool_window_V_15_fu_845_p3) ? 1'b1 : 1'b0);

assign icmp_ln1651_19_fu_1308_p2 = ((select_ln66_17_reg_1709 < select_ln66_18_reg_1715) ? 1'b1 : 1'b0);

assign icmp_ln1651_20_fu_922_p2 = ((pool_window_V_16_fu_892_p3 < pool_window_V_17_fu_900_p3) ? 1'b1 : 1'b0);

assign icmp_ln1651_21_fu_942_p2 = ((pool_window_V_18_fu_907_p3 < pool_window_V_19_fu_915_p3) ? 1'b1 : 1'b0);

assign icmp_ln1651_22_fu_1344_p2 = ((select_ln66_20_reg_1721 < select_ln66_21_reg_1727) ? 1'b1 : 1'b0);

assign icmp_ln1651_23_fu_992_p2 = ((pool_window_V_20_fu_962_p3 < pool_window_V_21_fu_970_p3) ? 1'b1 : 1'b0);

assign icmp_ln1651_24_fu_1012_p2 = ((pool_window_V_22_fu_977_p3 < pool_window_V_23_fu_985_p3) ? 1'b1 : 1'b0);

assign icmp_ln1651_25_fu_1380_p2 = ((select_ln66_23_reg_1733 < select_ln66_24_reg_1739) ? 1'b1 : 1'b0);

assign icmp_ln1651_26_fu_1062_p2 = ((pool_window_V_24_fu_1032_p3 < pool_window_V_25_fu_1040_p3) ? 1'b1 : 1'b0);

assign icmp_ln1651_27_fu_1082_p2 = ((pool_window_V_26_fu_1047_p3 < pool_window_V_27_fu_1055_p3) ? 1'b1 : 1'b0);

assign icmp_ln1651_28_fu_1416_p2 = ((select_ln66_26_reg_1745 < select_ln66_27_reg_1751) ? 1'b1 : 1'b0);

assign icmp_ln1651_29_fu_1132_p2 = ((pool_window_V_28_fu_1102_p3 < pool_window_V_29_fu_1110_p3) ? 1'b1 : 1'b0);

assign icmp_ln1651_30_fu_1152_p2 = ((pool_window_V_30_fu_1117_p3 < pool_window_V_31_fu_1125_p3) ? 1'b1 : 1'b0);

assign icmp_ln1651_31_fu_1452_p2 = ((select_ln66_29_reg_1757 < select_ln66_30_reg_1763) ? 1'b1 : 1'b0);

assign icmp_ln1651_9_fu_662_p2 = ((pool_window_V_2_fu_627_p3 < pool_window_V_3_fu_635_p3) ? 1'b1 : 1'b0);

assign icmp_ln1651_fu_642_p2 = ((pool_window_V_fu_612_p3 < pool_window_V_1_fu_620_p3) ? 1'b1 : 1'b0);

assign icmp_ln55_2_fu_595_p2 = (($signed(pY) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln55_3_fu_239_p2 = (($signed(pX_load_reg_1518) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln55_fu_233_p2 = ((ap_sig_allocacmp_sX_load == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln76_fu_244_p2 = ((add_ln76_reg_1523 == 32'd4) ? 1'b1 : 1'b0);

assign icmp_ln80_fu_442_p2 = ((add_ln80_reg_1548 == 32'd4) ? 1'b1 : 1'b0);

assign layer9_out_din = {{{{{{{{p_Val2_114_reg_1809}, {p_Val2_113_reg_1804}}, {p_Val2_112_reg_1799}}, {p_Val2_111_reg_1794}}, {p_Val2_110_reg_1789}}, {p_Val2_109_reg_1784}}, {p_Val2_108_reg_1779}}, {p_Val2_s_reg_1774}};

assign p_Val2_108_fu_1264_p3 = ((xor_ln1651_13_fu_1240_p2[0:0] == 1'b1) ? tmp_4_fu_1246_p4 : tmp_5_fu_1255_p4);

assign p_Val2_109_fu_1300_p3 = ((xor_ln1651_16_fu_1276_p2[0:0] == 1'b1) ? tmp_7_fu_1282_p4 : tmp_8_fu_1291_p4);

assign p_Val2_110_fu_1336_p3 = ((xor_ln1651_19_fu_1312_p2[0:0] == 1'b1) ? tmp_10_fu_1318_p4 : tmp_11_fu_1327_p4);

assign p_Val2_111_fu_1372_p3 = ((xor_ln1651_22_fu_1348_p2[0:0] == 1'b1) ? tmp_13_fu_1354_p4 : tmp_14_fu_1363_p4);

assign p_Val2_112_fu_1408_p3 = ((xor_ln1651_25_fu_1384_p2[0:0] == 1'b1) ? tmp_16_fu_1390_p4 : tmp_17_fu_1399_p4);

assign p_Val2_113_fu_1444_p3 = ((xor_ln1651_28_fu_1420_p2[0:0] == 1'b1) ? tmp_19_fu_1426_p4 : tmp_20_fu_1435_p4);

assign p_Val2_114_fu_1480_p3 = ((xor_ln1651_31_fu_1456_p2[0:0] == 1'b1) ? tmp_22_fu_1462_p4 : tmp_23_fu_1471_p4);

assign p_Val2_s_fu_1228_p3 = ((xor_ln1651_10_fu_1204_p2[0:0] == 1'b1) ? tmp_1_fu_1210_p4 : tmp_2_fu_1219_p4);

assign pool_window_V_10_fu_767_p3 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_5}, {5'd0}};

assign pool_window_V_11_fu_775_p3 = {{trunc_ln115_s_reg_1578}, {5'd0}};

assign pool_window_V_12_fu_822_p3 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_12}, {5'd0}};

assign pool_window_V_13_fu_830_p3 = {{p_1_reg_1620}, {5'd0}};

assign pool_window_V_14_fu_837_p3 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_4}, {5'd0}};

assign pool_window_V_15_fu_845_p3 = {{trunc_ln115_1_reg_1584}, {5'd0}};

assign pool_window_V_16_fu_892_p3 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_11}, {5'd0}};

assign pool_window_V_17_fu_900_p3 = {{p_2_reg_1626}, {5'd0}};

assign pool_window_V_18_fu_907_p3 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_3}, {5'd0}};

assign pool_window_V_19_fu_915_p3 = {{trunc_ln115_2_reg_1590}, {5'd0}};

assign pool_window_V_1_fu_620_p3 = {{p_4_reg_1602}, {5'd0}};

assign pool_window_V_20_fu_962_p3 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_10}, {5'd0}};

assign pool_window_V_21_fu_970_p3 = {{p_3_reg_1632}, {5'd0}};

assign pool_window_V_22_fu_977_p3 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_2}, {5'd0}};

assign pool_window_V_23_fu_985_p3 = {{trunc_ln115_3_reg_1596}, {5'd0}};

assign pool_window_V_24_fu_1032_p3 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_9}, {5'd0}};

assign pool_window_V_25_fu_1040_p3 = {{p_s_reg_1638}, {5'd0}};

assign pool_window_V_26_fu_1047_p3 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_1}, {5'd0}};

assign pool_window_V_27_fu_1055_p3 = {{trunc_ln115_6_reg_1560}, {5'd0}};

assign pool_window_V_28_fu_1102_p3 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_8}, {5'd0}};

assign pool_window_V_29_fu_1110_p3 = {{p_0_reg_1644}, {5'd0}};

assign pool_window_V_2_fu_627_p3 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_7}, {5'd0}};

assign pool_window_V_30_fu_1117_p3 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap}, {5'd0}};

assign pool_window_V_31_fu_1125_p3 = {{trunc_ln115_7_reg_1566}, {5'd0}};

assign pool_window_V_3_fu_635_p3 = {{trunc_ln115_reg_1554}, {5'd0}};

assign pool_window_V_4_fu_682_p3 = {{void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel}, {5'd0}};

assign pool_window_V_5_fu_690_p3 = {{p_5_reg_1608}, {5'd0}};

assign pool_window_V_6_fu_697_p3 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_6}, {5'd0}};

assign pool_window_V_7_fu_705_p3 = {{trunc_ln115_9_reg_1572}, {5'd0}};

assign pool_window_V_8_fu_752_p3 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_13}, {5'd0}};

assign pool_window_V_9_fu_760_p3 = {{p_6_reg_1614}, {5'd0}};

assign pool_window_V_fu_612_p3 = {{void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1}, {5'd0}};

assign select_ln66_11_fu_724_p3 = ((xor_ln1651_11_fu_718_p2[0:0] == 1'b1) ? pool_window_V_4_fu_682_p3 : pool_window_V_5_fu_690_p3);

assign select_ln66_12_fu_744_p3 = ((xor_ln1651_12_fu_738_p2[0:0] == 1'b1) ? pool_window_V_6_fu_697_p3 : pool_window_V_7_fu_705_p3);

assign select_ln66_14_fu_794_p3 = ((xor_ln1651_14_fu_788_p2[0:0] == 1'b1) ? pool_window_V_8_fu_752_p3 : pool_window_V_9_fu_760_p3);

assign select_ln66_15_fu_814_p3 = ((xor_ln1651_15_fu_808_p2[0:0] == 1'b1) ? pool_window_V_10_fu_767_p3 : pool_window_V_11_fu_775_p3);

assign select_ln66_17_fu_864_p3 = ((xor_ln1651_17_fu_858_p2[0:0] == 1'b1) ? pool_window_V_12_fu_822_p3 : pool_window_V_13_fu_830_p3);

assign select_ln66_18_fu_884_p3 = ((xor_ln1651_18_fu_878_p2[0:0] == 1'b1) ? pool_window_V_14_fu_837_p3 : pool_window_V_15_fu_845_p3);

assign select_ln66_20_fu_934_p3 = ((xor_ln1651_20_fu_928_p2[0:0] == 1'b1) ? pool_window_V_16_fu_892_p3 : pool_window_V_17_fu_900_p3);

assign select_ln66_21_fu_954_p3 = ((xor_ln1651_21_fu_948_p2[0:0] == 1'b1) ? pool_window_V_18_fu_907_p3 : pool_window_V_19_fu_915_p3);

assign select_ln66_23_fu_1004_p3 = ((xor_ln1651_23_fu_998_p2[0:0] == 1'b1) ? pool_window_V_20_fu_962_p3 : pool_window_V_21_fu_970_p3);

assign select_ln66_24_fu_1024_p3 = ((xor_ln1651_24_fu_1018_p2[0:0] == 1'b1) ? pool_window_V_22_fu_977_p3 : pool_window_V_23_fu_985_p3);

assign select_ln66_26_fu_1074_p3 = ((xor_ln1651_26_fu_1068_p2[0:0] == 1'b1) ? pool_window_V_24_fu_1032_p3 : pool_window_V_25_fu_1040_p3);

assign select_ln66_27_fu_1094_p3 = ((xor_ln1651_27_fu_1088_p2[0:0] == 1'b1) ? pool_window_V_26_fu_1047_p3 : pool_window_V_27_fu_1055_p3);

assign select_ln66_29_fu_1144_p3 = ((xor_ln1651_29_fu_1138_p2[0:0] == 1'b1) ? pool_window_V_28_fu_1102_p3 : pool_window_V_29_fu_1110_p3);

assign select_ln66_30_fu_1164_p3 = ((xor_ln1651_30_fu_1158_p2[0:0] == 1'b1) ? pool_window_V_30_fu_1117_p3 : pool_window_V_31_fu_1125_p3);

assign select_ln66_9_fu_674_p3 = ((xor_ln1651_9_fu_668_p2[0:0] == 1'b1) ? pool_window_V_2_fu_627_p3 : pool_window_V_3_fu_635_p3);

assign select_ln66_fu_654_p3 = ((xor_ln1651_fu_648_p2[0:0] == 1'b1) ? pool_window_V_fu_612_p3 : pool_window_V_1_fu_620_p3);

assign select_ln86_fu_1182_p3 = ((icmp_ln86_reg_1664[0:0] == 1'b1) ? 32'd4294967295 : 32'd1);

assign select_ln91_fu_418_p3 = ((icmp_ln55_reg_1534[0:0] == 1'b1) ? 32'd4294967295 : 32'd1);

assign start_out = real_start;

assign tmp_10_fu_1318_p4 = {{select_ln66_17_reg_1709[10:5]}};

assign tmp_11_fu_1327_p4 = {{select_ln66_18_reg_1715[10:5]}};

assign tmp_13_fu_1354_p4 = {{select_ln66_20_reg_1721[10:5]}};

assign tmp_14_fu_1363_p4 = {{select_ln66_21_reg_1727[10:5]}};

assign tmp_16_fu_1390_p4 = {{select_ln66_23_reg_1733[10:5]}};

assign tmp_17_fu_1399_p4 = {{select_ln66_24_reg_1739[10:5]}};

assign tmp_19_fu_1426_p4 = {{select_ln66_26_reg_1745[10:5]}};

assign tmp_1_fu_1210_p4 = {{select_ln66_reg_1673[10:5]}};

assign tmp_20_fu_1435_p4 = {{select_ln66_27_reg_1751[10:5]}};

assign tmp_22_fu_1462_p4 = {{select_ln66_29_reg_1757[10:5]}};

assign tmp_23_fu_1471_p4 = {{select_ln66_30_reg_1763[10:5]}};

assign tmp_2_fu_1219_p4 = {{select_ln66_9_reg_1679[10:5]}};

assign tmp_4_fu_1246_p4 = {{select_ln66_11_reg_1685[10:5]}};

assign tmp_5_fu_1255_p4 = {{select_ln66_12_reg_1691[10:5]}};

assign tmp_7_fu_1282_p4 = {{select_ln66_14_reg_1697[10:5]}};

assign tmp_8_fu_1291_p4 = {{select_ln66_15_reg_1703[10:5]}};

assign trunc_ln115_fu_259_p1 = layer8_out_dout[5:0];

assign void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_1_d0 = {{layer8_out_dout[41:36]}};

assign void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_2_d0 = {{layer8_out_dout[35:30]}};

assign void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_3_d0 = {{layer8_out_dout[29:24]}};

assign void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_4_d0 = {{layer8_out_dout[23:18]}};

assign void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_5_d0 = {{layer8_out_dout[17:12]}};

assign void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_6_d0 = {{layer8_out_dout[11:6]}};

assign void_pooling2d_cl_stream_stream_array_ap_ufixed_8u_0_line_buffer_d0 = {{layer8_out_dout[47:42]}};

assign xor_ln1651_10_fu_1204_p2 = (icmp_ln1651_10_fu_1200_p2 ^ 1'd1);

assign xor_ln1651_11_fu_718_p2 = (icmp_ln1651_11_fu_712_p2 ^ 1'd1);

assign xor_ln1651_12_fu_738_p2 = (icmp_ln1651_12_fu_732_p2 ^ 1'd1);

assign xor_ln1651_13_fu_1240_p2 = (icmp_ln1651_13_fu_1236_p2 ^ 1'd1);

assign xor_ln1651_14_fu_788_p2 = (icmp_ln1651_14_fu_782_p2 ^ 1'd1);

assign xor_ln1651_15_fu_808_p2 = (icmp_ln1651_15_fu_802_p2 ^ 1'd1);

assign xor_ln1651_16_fu_1276_p2 = (icmp_ln1651_16_fu_1272_p2 ^ 1'd1);

assign xor_ln1651_17_fu_858_p2 = (icmp_ln1651_17_fu_852_p2 ^ 1'd1);

assign xor_ln1651_18_fu_878_p2 = (icmp_ln1651_18_fu_872_p2 ^ 1'd1);

assign xor_ln1651_19_fu_1312_p2 = (icmp_ln1651_19_fu_1308_p2 ^ 1'd1);

assign xor_ln1651_20_fu_928_p2 = (icmp_ln1651_20_fu_922_p2 ^ 1'd1);

assign xor_ln1651_21_fu_948_p2 = (icmp_ln1651_21_fu_942_p2 ^ 1'd1);

assign xor_ln1651_22_fu_1348_p2 = (icmp_ln1651_22_fu_1344_p2 ^ 1'd1);

assign xor_ln1651_23_fu_998_p2 = (icmp_ln1651_23_fu_992_p2 ^ 1'd1);

assign xor_ln1651_24_fu_1018_p2 = (icmp_ln1651_24_fu_1012_p2 ^ 1'd1);

assign xor_ln1651_25_fu_1384_p2 = (icmp_ln1651_25_fu_1380_p2 ^ 1'd1);

assign xor_ln1651_26_fu_1068_p2 = (icmp_ln1651_26_fu_1062_p2 ^ 1'd1);

assign xor_ln1651_27_fu_1088_p2 = (icmp_ln1651_27_fu_1082_p2 ^ 1'd1);

assign xor_ln1651_28_fu_1420_p2 = (icmp_ln1651_28_fu_1416_p2 ^ 1'd1);

assign xor_ln1651_29_fu_1138_p2 = (icmp_ln1651_29_fu_1132_p2 ^ 1'd1);

assign xor_ln1651_30_fu_1158_p2 = (icmp_ln1651_30_fu_1152_p2 ^ 1'd1);

assign xor_ln1651_31_fu_1456_p2 = (icmp_ln1651_31_fu_1452_p2 ^ 1'd1);

assign xor_ln1651_9_fu_668_p2 = (icmp_ln1651_9_fu_662_p2 ^ 1'd1);

assign xor_ln1651_fu_648_p2 = (icmp_ln1651_fu_642_p2 ^ 1'd1);

always @ (posedge ap_clk) begin
    select_ln66_reg_1673[4:0] <= 5'b00000;
    select_ln66_9_reg_1679[4:0] <= 5'b00000;
    select_ln66_11_reg_1685[4:0] <= 5'b00000;
    select_ln66_12_reg_1691[4:0] <= 5'b00000;
    select_ln66_14_reg_1697[4:0] <= 5'b00000;
    select_ln66_15_reg_1703[4:0] <= 5'b00000;
    select_ln66_17_reg_1709[4:0] <= 5'b00000;
    select_ln66_18_reg_1715[4:0] <= 5'b00000;
    select_ln66_20_reg_1721[4:0] <= 5'b00000;
    select_ln66_21_reg_1727[4:0] <= 5'b00000;
    select_ln66_23_reg_1733[4:0] <= 5'b00000;
    select_ln66_24_reg_1739[4:0] <= 5'b00000;
    select_ln66_26_reg_1745[4:0] <= 5'b00000;
    select_ln66_27_reg_1751[4:0] <= 5'b00000;
    select_ln66_29_reg_1757[4:0] <= 5'b00000;
    select_ln66_30_reg_1763[4:0] <= 5'b00000;
end

endmodule //myproject_pooling2d_cl_array_ap_ufixed_8u_array_ap_ufixed_6_0_4_0_0_8u_config9_s
