Backend: Vitis
ClockPeriod: 5
ClockUncertainty: 27%
HLSConfig:
  LayerName:
    bn_dense_1:
      Precision:
        bias: ap_fixed<8,5>
        result: auto
        scale: auto
        weight: ap_fixed<8,5>
      Trace: false
    conv_act_0:
      Precision:
        result: ufixed<6,0,RND_CONV,SAT,0>
      Trace: false
    conv_act_1:
      Precision:
        result: ufixed<6,0,RND_CONV,SAT,0>
      Trace: false
    dense_0:
      Precision:
        bias: ap_fixed<8,3>
        result: auto
        weight: ap_fixed<8,3>
      ReuseFactor: 9
      Trace: false
    dense_0_linear:
      Precision:
        result: auto
      Trace: false
    dense_act_0:
      Precision:
        result: ufixed<6,0,RND_CONV,SAT,0>
      Trace: false
    flatten:
      Precision:
        result: auto
      Trace: false
    fused_convbn_0:
      Precision:
        bias: ap_fixed<8,3>
        result: auto
        weight: ap_fixed<8,3>
      ReuseFactor: 9
      Trace: false
    fused_convbn_0_linear:
      Precision:
        result: auto
      Trace: false
    fused_convbn_1:
      Precision:
        bias: ap_fixed<8,3>
        result: auto
        weight: ap_fixed<8,3>
      ReuseFactor: 9
      Trace: false
    fused_convbn_1_linear:
      Precision:
        result: auto
      Trace: false
    img_input:
      Precision:
        result: auto
      Trace: false
    output_dense:
      Precision:
        bias: fixed<6,1,TRN,WRAP,0>
        result: fixed<16,5,RND,SAT>
        weight: fixed<6,1,TRN,WRAP,0>
      ReuseFactor: 16
      Trace: false
    output_dense_linear:
      Precision:
        result: auto
      Trace: false
    output_softmax:
      Precision:
        result: auto
      Trace: false
    pool_0:
      Precision:
        result: auto
      Trace: false
    pool_1:
      Precision:
        result: auto
      Trace: false
  Model:
    BramFactor: 1000000000
    MemoryStorage: distributed
    Precision:
      default: ap_fixed<16,5>
    ReuseFactor: 16
    Strategy: Resource
    TraceOutput: false
IOType: io_stream
InputData: null
KerasModel: !keras_model 'model_personDetection/hls4ml_prj_qat/keras_model.keras'
OutputDir: model_personDetection/hls4ml_prj_qat
OutputPredictions: null
Part: xc7z020clg400-1
ProjectName: myproject
Stamp: 6a17f7aa
Version: 1.0.0
WriterConfig:
  Namespace: null
  WriteTar: false
  WriteWeightsTxt: true
