// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_16_5_5_3_0_1u_config18_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        img_input_TDATA,
        img_input_TVALID,
        img_input_TREADY,
        layer18_out_din,
        layer18_out_num_data_valid,
        layer18_out_fifo_cap,
        layer18_out_full_n,
        layer18_out_write
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [15:0] img_input_TDATA;
input   img_input_TVALID;
output   img_input_TREADY;
output  [15:0] layer18_out_din;
input  [7:0] layer18_out_num_data_valid;
input  [7:0] layer18_out_fifo_cap;
input   layer18_out_full_n;
output   layer18_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg[15:0] layer18_out_din;
reg layer18_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
wire    grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadTopWidth_fu_28_ap_start;
wire    grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadTopWidth_fu_28_ap_done;
wire    grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadTopWidth_fu_28_ap_idle;
wire    grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadTopWidth_fu_28_ap_ready;
wire   [15:0] grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadTopWidth_fu_28_layer18_out_din;
wire    grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadTopWidth_fu_28_layer18_out_write;
wire    grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadMain_fu_34_ap_start;
wire    grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadMain_fu_34_ap_done;
wire    grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadMain_fu_34_ap_idle;
wire    grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadMain_fu_34_ap_ready;
wire   [15:0] grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadMain_fu_34_layer18_out_din;
wire    grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadMain_fu_34_layer18_out_write;
wire    grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadMain_fu_34_img_input_TREADY;
wire    grp_zeropad2d_cl_array_array_ap_fixed_1u_config18_Pipeline_PadBottomWidth_fu_42_ap_start;
wire    grp_zeropad2d_cl_array_array_ap_fixed_1u_config18_Pipeline_PadBottomWidth_fu_42_ap_done;
wire    grp_zeropad2d_cl_array_array_ap_fixed_1u_config18_Pipeline_PadBottomWidth_fu_42_ap_idle;
wire    grp_zeropad2d_cl_array_array_ap_fixed_1u_config18_Pipeline_PadBottomWidth_fu_42_ap_ready;
wire   [15:0] grp_zeropad2d_cl_array_array_ap_fixed_1u_config18_Pipeline_PadBottomWidth_fu_42_layer18_out_din;
wire    grp_zeropad2d_cl_array_array_ap_fixed_1u_config18_Pipeline_PadBottomWidth_fu_42_layer18_out_write;
reg    grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadTopWidth_fu_28_ap_start_reg;
reg    ap_block_state1_ignore_call3;
wire    ap_CS_fsm_state2;
reg    grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadMain_fu_34_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg    grp_zeropad2d_cl_array_array_ap_fixed_1u_config18_Pipeline_PadBottomWidth_fu_42_ap_start_reg;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
reg   [7:0] ap_NS_fsm;
reg    ap_block_state1;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    regslice_both_img_input_U_apdone_blk;
wire   [15:0] img_input_TDATA_int_regslice;
wire    img_input_TVALID_int_regslice;
reg    img_input_TREADY_int_regslice;
wire    regslice_both_img_input_U_ack_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 8'd1;
#0 grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadTopWidth_fu_28_ap_start_reg = 1'b0;
#0 grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadMain_fu_34_ap_start_reg = 1'b0;
#0 grp_zeropad2d_cl_array_array_ap_fixed_1u_config18_Pipeline_PadBottomWidth_fu_42_ap_start_reg = 1'b0;
end

myproject_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadTopWidth grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadTopWidth_fu_28(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadTopWidth_fu_28_ap_start),
    .ap_done(grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadTopWidth_fu_28_ap_done),
    .ap_idle(grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadTopWidth_fu_28_ap_idle),
    .ap_ready(grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadTopWidth_fu_28_ap_ready),
    .layer18_out_din(grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadTopWidth_fu_28_layer18_out_din),
    .layer18_out_num_data_valid(8'd0),
    .layer18_out_fifo_cap(8'd0),
    .layer18_out_full_n(layer18_out_full_n),
    .layer18_out_write(grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadTopWidth_fu_28_layer18_out_write)
);

myproject_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadMain grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadMain_fu_34(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadMain_fu_34_ap_start),
    .ap_done(grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadMain_fu_34_ap_done),
    .ap_idle(grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadMain_fu_34_ap_idle),
    .ap_ready(grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadMain_fu_34_ap_ready),
    .layer18_out_din(grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadMain_fu_34_layer18_out_din),
    .layer18_out_num_data_valid(8'd0),
    .layer18_out_fifo_cap(8'd0),
    .layer18_out_full_n(layer18_out_full_n),
    .layer18_out_write(grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadMain_fu_34_layer18_out_write),
    .img_input_TDATA(img_input_TDATA_int_regslice),
    .img_input_TVALID(img_input_TVALID_int_regslice),
    .img_input_TREADY(grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadMain_fu_34_img_input_TREADY)
);

myproject_zeropad2d_cl_array_array_ap_fixed_1u_config18_Pipeline_PadBottomWidth grp_zeropad2d_cl_array_array_ap_fixed_1u_config18_Pipeline_PadBottomWidth_fu_42(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_zeropad2d_cl_array_array_ap_fixed_1u_config18_Pipeline_PadBottomWidth_fu_42_ap_start),
    .ap_done(grp_zeropad2d_cl_array_array_ap_fixed_1u_config18_Pipeline_PadBottomWidth_fu_42_ap_done),
    .ap_idle(grp_zeropad2d_cl_array_array_ap_fixed_1u_config18_Pipeline_PadBottomWidth_fu_42_ap_idle),
    .ap_ready(grp_zeropad2d_cl_array_array_ap_fixed_1u_config18_Pipeline_PadBottomWidth_fu_42_ap_ready),
    .layer18_out_din(grp_zeropad2d_cl_array_array_ap_fixed_1u_config18_Pipeline_PadBottomWidth_fu_42_layer18_out_din),
    .layer18_out_num_data_valid(8'd0),
    .layer18_out_fifo_cap(8'd0),
    .layer18_out_full_n(layer18_out_full_n),
    .layer18_out_write(grp_zeropad2d_cl_array_array_ap_fixed_1u_config18_Pipeline_PadBottomWidth_fu_42_layer18_out_write)
);

myproject_regslice_both #(
    .DataWidth( 16 ))
regslice_both_img_input_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(img_input_TDATA),
    .vld_in(img_input_TVALID),
    .ack_in(regslice_both_img_input_U_ack_in),
    .data_out(img_input_TDATA_int_regslice),
    .vld_out(img_input_TVALID_int_regslice),
    .ack_out(img_input_TREADY_int_regslice),
    .apdone_blk(regslice_both_img_input_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_zeropad2d_cl_array_array_ap_fixed_1u_config18_Pipeline_PadBottomWidth_fu_42_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadMain_fu_34_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadMain_fu_34_ap_start_reg <= 1'b1;
        end else if ((grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadMain_fu_34_ap_ready == 1'b1)) begin
            grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadMain_fu_34_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadTopWidth_fu_28_ap_start_reg <= 1'b0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadTopWidth_fu_28_ap_start_reg <= 1'b1;
        end else if ((grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadTopWidth_fu_28_ap_ready == 1'b1)) begin
            grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadTopWidth_fu_28_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_zeropad2d_cl_array_array_ap_fixed_1u_config18_Pipeline_PadBottomWidth_fu_42_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_zeropad2d_cl_array_array_ap_fixed_1u_config18_Pipeline_PadBottomWidth_fu_42_ap_start_reg <= 1'b1;
        end else if ((grp_zeropad2d_cl_array_array_ap_fixed_1u_config18_Pipeline_PadBottomWidth_fu_42_ap_ready == 1'b1)) begin
            grp_zeropad2d_cl_array_array_ap_fixed_1u_config18_Pipeline_PadBottomWidth_fu_42_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (real_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadTopWidth_fu_28_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadMain_fu_34_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_zeropad2d_cl_array_array_ap_fixed_1u_config18_Pipeline_PadBottomWidth_fu_42_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_zeropad2d_cl_array_array_ap_fixed_1u_config18_Pipeline_PadBottomWidth_fu_42_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        img_input_TREADY_int_regslice = grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadMain_fu_34_img_input_TREADY;
    end else begin
        img_input_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((grp_zeropad2d_cl_array_array_ap_fixed_1u_config18_Pipeline_PadBottomWidth_fu_42_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        layer18_out_din = grp_zeropad2d_cl_array_array_ap_fixed_1u_config18_Pipeline_PadBottomWidth_fu_42_layer18_out_din;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        layer18_out_din = grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadMain_fu_34_layer18_out_din;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        layer18_out_din = grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadTopWidth_fu_28_layer18_out_din;
    end else begin
        layer18_out_din = grp_zeropad2d_cl_array_array_ap_fixed_1u_config18_Pipeline_PadBottomWidth_fu_42_layer18_out_din;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        layer18_out_write = grp_zeropad2d_cl_array_array_ap_fixed_1u_config18_Pipeline_PadBottomWidth_fu_42_layer18_out_write;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        layer18_out_write = grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadMain_fu_34_layer18_out_write;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        layer18_out_write = grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadTopWidth_fu_28_layer18_out_write;
    end else begin
        layer18_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadTopWidth_fu_28_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadMain_fu_34_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((grp_zeropad2d_cl_array_array_ap_fixed_1u_config18_Pipeline_PadBottomWidth_fu_42_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call3 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadMain_fu_34_ap_start = grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadMain_fu_34_ap_start_reg;

assign grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadTopWidth_fu_28_ap_start = grp_zeropad2d_cl_array_array_ap_fixed_16_5_5_3_0_1u_config18_Pipeline_PadTopWidth_fu_28_ap_start_reg;

assign grp_zeropad2d_cl_array_array_ap_fixed_1u_config18_Pipeline_PadBottomWidth_fu_42_ap_start = grp_zeropad2d_cl_array_array_ap_fixed_1u_config18_Pipeline_PadBottomWidth_fu_42_ap_start_reg;

assign img_input_TREADY = regslice_both_img_input_U_ack_in;

assign start_out = real_start;

endmodule //myproject_zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_16_5_5_3_0_1u_config18_s
