// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_softmax_stable_array_array_ap_fixed_16_5_5_3_0_10u_softmax_config17_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        layer16_out_dout,
        layer16_out_num_data_valid,
        layer16_out_fifo_cap,
        layer16_out_empty_n,
        layer16_out_read,
        layer17_out_TDATA,
        layer17_out_TVALID,
        layer17_out_TREADY
);

parameter    ap_ST_fsm_state1 = 27'd1;
parameter    ap_ST_fsm_state2 = 27'd2;
parameter    ap_ST_fsm_state3 = 27'd4;
parameter    ap_ST_fsm_state4 = 27'd8;
parameter    ap_ST_fsm_state5 = 27'd16;
parameter    ap_ST_fsm_state6 = 27'd32;
parameter    ap_ST_fsm_state7 = 27'd64;
parameter    ap_ST_fsm_state8 = 27'd128;
parameter    ap_ST_fsm_state9 = 27'd256;
parameter    ap_ST_fsm_state10 = 27'd512;
parameter    ap_ST_fsm_state11 = 27'd1024;
parameter    ap_ST_fsm_state12 = 27'd2048;
parameter    ap_ST_fsm_state13 = 27'd4096;
parameter    ap_ST_fsm_state14 = 27'd8192;
parameter    ap_ST_fsm_state15 = 27'd16384;
parameter    ap_ST_fsm_state16 = 27'd32768;
parameter    ap_ST_fsm_state17 = 27'd65536;
parameter    ap_ST_fsm_state18 = 27'd131072;
parameter    ap_ST_fsm_state19 = 27'd262144;
parameter    ap_ST_fsm_state20 = 27'd524288;
parameter    ap_ST_fsm_state21 = 27'd1048576;
parameter    ap_ST_fsm_state22 = 27'd2097152;
parameter    ap_ST_fsm_state23 = 27'd4194304;
parameter    ap_ST_fsm_state24 = 27'd8388608;
parameter    ap_ST_fsm_state25 = 27'd16777216;
parameter    ap_ST_fsm_state26 = 27'd33554432;
parameter    ap_ST_fsm_state27 = 27'd67108864;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [159:0] layer16_out_dout;
input  [1:0] layer16_out_num_data_valid;
input  [1:0] layer16_out_fifo_cap;
input   layer16_out_empty_n;
output   layer16_out_read;
output  [159:0] layer17_out_TDATA;
output   layer17_out_TVALID;
input   layer17_out_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg layer16_out_read;
reg layer17_out_TVALID;

(* fsm_encoding = "none" *) reg   [26:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [9:0] exp_table_address0;
reg    exp_table_ce0;
wire   [16:0] exp_table_q0;
reg   [9:0] exp_table_address1;
reg    exp_table_ce1;
wire   [16:0] exp_table_q1;
wire   [9:0] exp_table_address2;
reg    exp_table_ce2;
wire   [16:0] exp_table_q2;
wire   [9:0] exp_table_address3;
reg    exp_table_ce3;
wire   [16:0] exp_table_q3;
wire   [9:0] exp_table_address4;
reg    exp_table_ce4;
wire   [16:0] exp_table_q4;
wire   [9:0] exp_table_address5;
reg    exp_table_ce5;
wire   [16:0] exp_table_q5;
wire   [9:0] exp_table_address6;
reg    exp_table_ce6;
wire   [16:0] exp_table_q6;
wire   [9:0] exp_table_address7;
reg    exp_table_ce7;
wire   [16:0] exp_table_q7;
wire   [9:0] invert_table_address0;
reg    invert_table_ce0;
wire   [17:0] invert_table_q0;
reg    layer16_out_blk_n;
reg    layer17_out_TDATA_blk_n;
wire    ap_CS_fsm_state26;
wire  signed [15:0] data_array_V_fu_323_p1;
reg  signed [15:0] data_array_V_reg_1921;
reg  signed [15:0] data_array_V_8_reg_1928;
reg  signed [15:0] data_array_V_9_reg_1935;
reg  signed [15:0] data_array_V_1_reg_1942;
reg  signed [15:0] data_array_V_2_reg_1949;
reg  signed [15:0] data_array_V_3_reg_1956;
reg  signed [15:0] data_array_V_4_reg_1963;
reg  signed [15:0] data_array_V_5_reg_1970;
reg  signed [15:0] data_array_V_6_reg_1977;
reg  signed [15:0] data_array_V_7_reg_1984;
wire   [15:0] select_ln66_fu_427_p3;
reg   [15:0] select_ln66_reg_1991;
wire    ap_CS_fsm_state2;
wire   [15:0] select_ln66_1_fu_443_p3;
reg   [15:0] select_ln66_1_reg_1997;
wire   [15:0] select_ln66_3_fu_459_p3;
reg   [15:0] select_ln66_3_reg_2003;
wire   [15:0] select_ln66_4_fu_475_p3;
reg   [15:0] select_ln66_4_reg_2009;
wire   [15:0] select_ln66_2_fu_491_p3;
reg   [15:0] select_ln66_2_reg_2015;
wire    ap_CS_fsm_state3;
wire   [15:0] select_ln66_5_fu_507_p3;
reg   [15:0] select_ln66_5_reg_2021;
wire   [15:0] select_ln66_6_fu_523_p3;
reg   [15:0] select_ln66_6_reg_2027;
wire    ap_CS_fsm_state4;
wire   [15:0] select_ln66_7_fu_539_p3;
reg   [15:0] select_ln66_7_reg_2033;
wire   [15:0] x_max_V_fu_555_p3;
reg   [15:0] x_max_V_reg_2039;
wire    ap_CS_fsm_state5;
wire   [9:0] p_Result_s_fu_1012_p3;
reg   [9:0] p_Result_s_reg_2044;
wire    ap_CS_fsm_state6;
wire   [9:0] p_Result_21_fu_1038_p3;
reg   [9:0] p_Result_21_reg_2049;
wire   [9:0] p_Result_22_fu_1064_p3;
reg   [9:0] p_Result_22_reg_2054;
wire   [9:0] p_Result_23_fu_1090_p3;
reg   [9:0] p_Result_23_reg_2059;
wire   [9:0] p_Result_24_fu_1116_p3;
reg   [9:0] p_Result_24_reg_2064;
wire   [9:0] p_Result_25_fu_1142_p3;
reg   [9:0] p_Result_25_reg_2069;
wire   [9:0] p_Result_26_fu_1168_p3;
reg   [9:0] p_Result_26_reg_2074;
wire   [9:0] p_Result_27_fu_1194_p3;
reg   [9:0] p_Result_27_reg_2079;
wire   [9:0] p_Result_28_fu_1220_p3;
reg   [9:0] p_Result_28_reg_2084;
wire   [9:0] p_Result_29_fu_1246_p3;
reg   [9:0] p_Result_29_reg_2089;
wire    ap_CS_fsm_state7;
reg   [16:0] exp_res_V_reg_2134;
wire    ap_CS_fsm_state8;
reg   [16:0] exp_res_V_10_reg_2140;
reg   [16:0] exp_res_V_11_reg_2146;
reg   [16:0] exp_res_V_12_reg_2152;
reg   [16:0] exp_res_V_13_reg_2158;
reg   [16:0] exp_res_V_14_reg_2164;
reg   [16:0] exp_res_V_15_reg_2170;
reg   [16:0] exp_res_V_16_reg_2176;
wire    ap_CS_fsm_state9;
wire  signed [17:0] lhs_2_fu_1330_p3;
reg  signed [17:0] lhs_2_reg_2192;
wire  signed [17:0] rhs_2_fu_1374_p3;
reg  signed [17:0] rhs_2_reg_2198;
wire  signed [17:0] lhs_5_fu_1418_p3;
reg  signed [17:0] lhs_5_reg_2204;
wire  signed [17:0] rhs_5_fu_1462_p3;
reg  signed [17:0] rhs_5_reg_2210;
reg   [16:0] exp_res_V_17_reg_2216;
wire    ap_CS_fsm_state10;
reg   [16:0] exp_res_V_18_reg_2223;
wire   [0:0] p_Result_66_fu_1482_p3;
reg   [0:0] p_Result_66_reg_2230;
wire   [17:0] p_Val2_13_fu_1490_p2;
reg   [17:0] p_Val2_13_reg_2235;
wire   [0:0] p_Result_67_fu_1494_p3;
reg   [0:0] p_Result_67_reg_2240;
wire   [0:0] xor_ln302_13_fu_1514_p2;
reg   [0:0] xor_ln302_13_reg_2245;
wire   [17:0] select_ln350_fu_1520_p3;
reg   [17:0] select_ln350_reg_2251;
wire   [0:0] p_Result_70_fu_1540_p3;
reg   [0:0] p_Result_70_reg_2256;
wire   [17:0] p_Val2_17_fu_1548_p2;
reg   [17:0] p_Val2_17_reg_2261;
wire   [0:0] p_Result_71_fu_1552_p3;
reg   [0:0] p_Result_71_reg_2266;
wire   [0:0] xor_ln302_15_fu_1572_p2;
reg   [0:0] xor_ln302_15_reg_2271;
wire   [17:0] select_ln350_1_fu_1578_p3;
reg   [17:0] select_ln350_1_reg_2277;
reg   [0:0] p_Result_72_reg_2282;
wire    ap_CS_fsm_state11;
wire   [17:0] p_Val2_19_fu_1682_p2;
reg   [17:0] p_Val2_19_reg_2288;
reg   [0:0] p_Result_73_reg_2293;
wire   [16:0] rhs_7_fu_1714_p3;
reg   [16:0] rhs_7_reg_2299;
reg   [0:0] p_Result_75_reg_2305;
wire    ap_CS_fsm_state12;
reg   [0:0] p_Result_76_reg_2312;
reg   [9:0] tmp_9_reg_2319;
wire   [9:0] p_Result_43_fu_1849_p3;
reg   [9:0] p_Result_43_reg_2325;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
reg   [17:0] inv_exp_sum_V_reg_2335;
wire    ap_CS_fsm_state15;
wire  signed [24:0] sext_ln1273_fu_1861_p1;
reg  signed [24:0] sext_ln1273_reg_2340;
wire    ap_CS_fsm_state16;
wire   [24:0] zext_ln1273_fu_1865_p1;
wire   [15:0] grp_fu_313_p4;
reg   [15:0] out_pack_data_reg_2350;
wire    ap_CS_fsm_state17;
wire   [24:0] zext_ln1273_1_fu_1869_p1;
reg   [15:0] out_pack_data_1_reg_2360;
wire    ap_CS_fsm_state18;
wire   [24:0] zext_ln1273_2_fu_1873_p1;
reg   [15:0] out_pack_data_2_reg_2370;
wire    ap_CS_fsm_state19;
wire   [24:0] zext_ln1273_3_fu_1877_p1;
reg   [15:0] out_pack_data_3_reg_2380;
wire    ap_CS_fsm_state20;
wire   [24:0] zext_ln1273_4_fu_1881_p1;
reg   [15:0] trunc_ln1_reg_2390;
wire    ap_CS_fsm_state21;
wire   [24:0] zext_ln1273_5_fu_1885_p1;
reg   [15:0] trunc_ln818_1_reg_2400;
wire    ap_CS_fsm_state22;
wire   [24:0] zext_ln1273_6_fu_1889_p1;
reg   [15:0] trunc_ln818_2_reg_2410;
wire    ap_CS_fsm_state23;
wire   [24:0] zext_ln1273_7_fu_1893_p1;
reg   [15:0] trunc_ln818_3_reg_2420;
wire    ap_CS_fsm_state24;
wire   [24:0] zext_ln1273_8_fu_1897_p1;
reg   [15:0] trunc_ln818_4_reg_2430;
wire    ap_CS_fsm_state25;
wire   [24:0] zext_ln1273_9_fu_1901_p1;
wire   [63:0] zext_ln225_fu_1254_p1;
wire   [63:0] zext_ln225_1_fu_1258_p1;
wire   [63:0] zext_ln225_2_fu_1262_p1;
wire   [63:0] zext_ln225_3_fu_1266_p1;
wire   [63:0] zext_ln225_4_fu_1270_p1;
wire   [63:0] zext_ln225_5_fu_1274_p1;
wire   [63:0] zext_ln225_6_fu_1278_p1;
wire   [63:0] zext_ln225_7_fu_1282_p1;
wire   [63:0] zext_ln225_8_fu_1286_p1;
wire   [63:0] zext_ln225_9_fu_1290_p1;
wire   [63:0] zext_ln235_fu_1857_p1;
reg    ap_block_state1;
reg  signed [17:0] grp_fu_275_p0;
reg   [16:0] grp_fu_275_p1;
wire   [24:0] grp_fu_275_p2;
wire   [0:0] icmp_ln1651_fu_417_p2;
wire   [0:0] xor_ln1651_fu_421_p2;
wire   [0:0] icmp_ln1651_1_fu_433_p2;
wire   [0:0] xor_ln1651_1_fu_437_p2;
wire   [0:0] icmp_ln1651_3_fu_449_p2;
wire   [0:0] xor_ln1651_3_fu_453_p2;
wire   [0:0] icmp_ln1651_4_fu_465_p2;
wire   [0:0] xor_ln1651_4_fu_469_p2;
wire   [0:0] icmp_ln1651_2_fu_481_p2;
wire   [0:0] xor_ln1651_2_fu_485_p2;
wire   [0:0] icmp_ln1651_5_fu_497_p2;
wire   [0:0] xor_ln1651_5_fu_501_p2;
wire   [0:0] icmp_ln1651_6_fu_513_p2;
wire   [0:0] xor_ln1651_6_fu_517_p2;
wire   [0:0] icmp_ln1651_7_fu_529_p2;
wire   [0:0] xor_ln1651_7_fu_533_p2;
wire   [0:0] icmp_ln1651_8_fu_545_p2;
wire   [0:0] xor_ln1651_8_fu_549_p2;
wire  signed [16:0] sext_ln1348_fu_561_p1;
wire  signed [16:0] sext_ln1348_1_fu_564_p1;
wire   [16:0] ret_V_fu_567_p2;
wire   [0:0] p_Result_44_fu_573_p3;
wire   [0:0] p_Result_45_fu_581_p3;
wire   [0:0] xor_ln895_fu_589_p2;
wire  signed [16:0] sext_ln1348_2_fu_607_p1;
wire   [16:0] ret_V_1_fu_610_p2;
wire   [0:0] p_Result_46_fu_616_p3;
wire   [0:0] p_Result_47_fu_624_p3;
wire   [0:0] xor_ln895_1_fu_632_p2;
wire  signed [16:0] sext_ln1348_3_fu_650_p1;
wire   [16:0] ret_V_2_fu_653_p2;
wire   [0:0] p_Result_48_fu_659_p3;
wire   [0:0] p_Result_49_fu_667_p3;
wire   [0:0] xor_ln895_2_fu_675_p2;
wire  signed [16:0] sext_ln1348_4_fu_693_p1;
wire   [16:0] ret_V_3_fu_696_p2;
wire   [0:0] p_Result_50_fu_702_p3;
wire   [0:0] p_Result_51_fu_710_p3;
wire   [0:0] xor_ln895_3_fu_718_p2;
wire  signed [16:0] sext_ln1348_5_fu_736_p1;
wire   [16:0] ret_V_4_fu_739_p2;
wire   [0:0] p_Result_52_fu_745_p3;
wire   [0:0] p_Result_53_fu_753_p3;
wire   [0:0] xor_ln895_4_fu_761_p2;
wire  signed [16:0] sext_ln1348_6_fu_779_p1;
wire   [16:0] ret_V_5_fu_782_p2;
wire   [0:0] p_Result_54_fu_788_p3;
wire   [0:0] p_Result_55_fu_796_p3;
wire   [0:0] xor_ln895_5_fu_804_p2;
wire  signed [16:0] sext_ln1348_7_fu_822_p1;
wire   [16:0] ret_V_6_fu_825_p2;
wire   [0:0] p_Result_56_fu_831_p3;
wire   [0:0] p_Result_57_fu_839_p3;
wire   [0:0] xor_ln895_6_fu_847_p2;
wire  signed [16:0] sext_ln1348_8_fu_865_p1;
wire   [16:0] ret_V_7_fu_868_p2;
wire   [0:0] p_Result_58_fu_874_p3;
wire   [0:0] p_Result_59_fu_882_p3;
wire   [0:0] xor_ln895_7_fu_890_p2;
wire  signed [16:0] sext_ln1348_9_fu_908_p1;
wire   [16:0] ret_V_8_fu_911_p2;
wire   [0:0] p_Result_60_fu_917_p3;
wire   [0:0] p_Result_61_fu_925_p3;
wire   [0:0] xor_ln895_8_fu_933_p2;
wire  signed [16:0] sext_ln1348_10_fu_951_p1;
wire   [16:0] ret_V_9_fu_954_p2;
wire   [0:0] p_Result_62_fu_960_p3;
wire   [0:0] p_Result_63_fu_968_p3;
wire   [0:0] xor_ln895_9_fu_976_p2;
wire   [0:0] overflow_fu_595_p2;
wire   [0:0] xor_ln302_fu_601_p2;
wire   [9:0] select_ln346_fu_994_p3;
wire   [9:0] tmp_fu_1002_p4;
wire   [0:0] overflow_1_fu_638_p2;
wire   [0:0] xor_ln302_1_fu_644_p2;
wire   [9:0] select_ln346_1_fu_1020_p3;
wire   [9:0] tmp_s_fu_1028_p4;
wire   [0:0] overflow_2_fu_681_p2;
wire   [0:0] xor_ln302_2_fu_687_p2;
wire   [9:0] select_ln346_2_fu_1046_p3;
wire   [9:0] tmp_1_fu_1054_p4;
wire   [0:0] overflow_3_fu_724_p2;
wire   [0:0] xor_ln302_3_fu_730_p2;
wire   [9:0] select_ln346_3_fu_1072_p3;
wire   [9:0] tmp_2_fu_1080_p4;
wire   [0:0] overflow_4_fu_767_p2;
wire   [0:0] xor_ln302_4_fu_773_p2;
wire   [9:0] select_ln346_4_fu_1098_p3;
wire   [9:0] tmp_3_fu_1106_p4;
wire   [0:0] overflow_5_fu_810_p2;
wire   [0:0] xor_ln302_5_fu_816_p2;
wire   [9:0] select_ln346_5_fu_1124_p3;
wire   [9:0] tmp_4_fu_1132_p4;
wire   [0:0] overflow_6_fu_853_p2;
wire   [0:0] xor_ln302_6_fu_859_p2;
wire   [9:0] select_ln346_6_fu_1150_p3;
wire   [9:0] tmp_5_fu_1158_p4;
wire   [0:0] overflow_7_fu_896_p2;
wire   [0:0] xor_ln302_7_fu_902_p2;
wire   [9:0] select_ln346_7_fu_1176_p3;
wire   [9:0] tmp_6_fu_1184_p4;
wire   [0:0] overflow_8_fu_939_p2;
wire   [0:0] xor_ln302_8_fu_945_p2;
wire   [9:0] select_ln346_8_fu_1202_p3;
wire   [9:0] tmp_7_fu_1210_p4;
wire   [0:0] overflow_9_fu_982_p2;
wire   [0:0] xor_ln302_9_fu_988_p2;
wire   [9:0] select_ln346_9_fu_1228_p3;
wire   [9:0] tmp_8_fu_1236_p4;
wire   [17:0] zext_ln44_1_fu_1297_p1;
wire   [17:0] zext_ln44_fu_1294_p1;
wire   [17:0] p_Val2_10_fu_1300_p2;
wire   [0:0] tmp_31_fu_1314_p3;
wire   [0:0] p_Result_64_fu_1306_p3;
wire   [17:0] select_ln346_11_fu_1322_p3;
wire   [17:0] zext_ln44_3_fu_1341_p1;
wire   [17:0] zext_ln44_2_fu_1338_p1;
wire   [17:0] p_Val2_11_fu_1344_p2;
wire   [0:0] tmp_33_fu_1358_p3;
wire   [0:0] p_Result_65_fu_1350_p3;
wire   [17:0] select_ln346_12_fu_1366_p3;
wire   [17:0] zext_ln44_5_fu_1385_p1;
wire   [17:0] zext_ln44_4_fu_1382_p1;
wire   [17:0] p_Val2_14_fu_1388_p2;
wire   [0:0] tmp_37_fu_1402_p3;
wire   [0:0] p_Result_68_fu_1394_p3;
wire   [17:0] select_ln346_13_fu_1410_p3;
wire   [17:0] zext_ln44_7_fu_1429_p1;
wire   [17:0] zext_ln44_6_fu_1426_p1;
wire   [17:0] p_Val2_15_fu_1432_p2;
wire   [0:0] tmp_39_fu_1446_p3;
wire   [0:0] p_Result_69_fu_1438_p3;
wire   [17:0] select_ln346_14_fu_1454_p3;
wire  signed [18:0] sext_ln813_4_fu_1473_p1;
wire  signed [18:0] sext_ln813_3_fu_1470_p1;
wire   [18:0] ret_V_10_fu_1476_p2;
wire   [0:0] xor_ln896_1_fu_1502_p2;
wire   [0:0] underflow_1_fu_1508_p2;
wire  signed [18:0] sext_ln813_6_fu_1531_p1;
wire  signed [18:0] sext_ln813_5_fu_1528_p1;
wire   [18:0] ret_V_11_fu_1534_p2;
wire   [0:0] xor_ln896_2_fu_1560_p2;
wire   [0:0] underflow_2_fu_1566_p2;
wire   [0:0] xor_ln895_12_fu_1592_p2;
wire   [0:0] overflow_12_fu_1597_p2;
wire   [0:0] xor_ln302_14_fu_1602_p2;
wire   [0:0] or_ln302_1_fu_1607_p2;
wire   [17:0] select_ln302_fu_1613_p3;
wire   [0:0] xor_ln895_13_fu_1626_p2;
wire   [0:0] overflow_15_fu_1631_p2;
wire   [0:0] xor_ln302_16_fu_1636_p2;
wire   [0:0] or_ln302_2_fu_1641_p2;
wire   [17:0] select_ln302_5_fu_1647_p3;
wire  signed [17:0] lhs_6_fu_1619_p3;
wire  signed [17:0] rhs_6_fu_1653_p3;
wire  signed [18:0] sext_ln813_fu_1660_p1;
wire  signed [18:0] sext_ln813_1_fu_1664_p1;
wire   [18:0] ret_V_12_fu_1668_p2;
wire   [17:0] exp_res_V_9_cast40_fu_1589_p1;
wire   [17:0] exp_res_V_8_cast39_fu_1586_p1;
wire   [17:0] p_Val2_20_fu_1696_p2;
wire   [0:0] p_Result_74_fu_1706_p3;
wire   [16:0] add_ln856_fu_1702_p2;
wire   [0:0] xor_ln895_10_fu_1722_p2;
wire   [0:0] overflow_16_fu_1727_p2;
wire   [0:0] xor_ln302_10_fu_1732_p2;
wire   [17:0] select_ln346_10_fu_1736_p3;
wire  signed [17:0] lhs_7_fu_1744_p3;
wire  signed [18:0] sext_ln813_2_fu_1754_p1;
wire   [18:0] zext_ln813_1_fu_1758_p1;
wire   [18:0] ret_V_13_fu_1761_p2;
wire   [17:0] zext_ln813_fu_1751_p1;
wire   [17:0] p_Val2_22_fu_1775_p2;
wire   [0:0] xor_ln895_11_fu_1799_p2;
wire   [0:0] xor_ln896_fu_1809_p2;
wire   [0:0] xor_ln302_11_fu_1819_p2;
wire   [0:0] overflow_18_fu_1804_p2;
wire   [0:0] xor_ln302_12_fu_1823_p2;
wire   [0:0] underflow_fu_1814_p2;
wire   [0:0] or_ln302_fu_1829_p2;
wire   [9:0] select_ln302_8_fu_1835_p3;
wire   [9:0] select_ln350_2_fu_1842_p3;
reg    grp_fu_275_ce;
wire    ap_CS_fsm_state27;
reg   [26:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
reg    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 27'd1;
end

myproject_softmax_stable_array_array_ap_fixed_16_5_5_3_0_10u_softmax_config17_s_exp_tabBew #(
    .DataWidth( 17 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
exp_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(exp_table_address0),
    .ce0(exp_table_ce0),
    .q0(exp_table_q0),
    .address1(exp_table_address1),
    .ce1(exp_table_ce1),
    .q1(exp_table_q1),
    .address2(exp_table_address2),
    .ce2(exp_table_ce2),
    .q2(exp_table_q2),
    .address3(exp_table_address3),
    .ce3(exp_table_ce3),
    .q3(exp_table_q3),
    .address4(exp_table_address4),
    .ce4(exp_table_ce4),
    .q4(exp_table_q4),
    .address5(exp_table_address5),
    .ce5(exp_table_ce5),
    .q5(exp_table_q5),
    .address6(exp_table_address6),
    .ce6(exp_table_ce6),
    .q6(exp_table_q6),
    .address7(exp_table_address7),
    .ce7(exp_table_ce7),
    .q7(exp_table_q7)
);

myproject_softmax_stable_array_array_ap_fixed_16_5_5_3_0_10u_softmax_config17_s_invert_CeG #(
    .DataWidth( 18 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
invert_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(invert_table_address0),
    .ce0(invert_table_ce0),
    .q0(invert_table_q0)
);

myproject_mul_18s_17ns_25_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 17 ),
    .dout_WIDTH( 25 ))
mul_18s_17ns_25_2_1_U385(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_275_p0),
    .din1(grp_fu_275_p1),
    .ce(grp_fu_275_ce),
    .dout(grp_fu_275_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        data_array_V_1_reg_1942 <= {{layer16_out_dout[31:16]}};
        data_array_V_2_reg_1949 <= {{layer16_out_dout[47:32]}};
        data_array_V_3_reg_1956 <= {{layer16_out_dout[63:48]}};
        data_array_V_4_reg_1963 <= {{layer16_out_dout[79:64]}};
        data_array_V_5_reg_1970 <= {{layer16_out_dout[95:80]}};
        data_array_V_6_reg_1977 <= {{layer16_out_dout[111:96]}};
        data_array_V_7_reg_1984 <= {{layer16_out_dout[127:112]}};
        data_array_V_8_reg_1928 <= {{layer16_out_dout[143:128]}};
        data_array_V_9_reg_1935 <= {{layer16_out_dout[159:144]}};
        data_array_V_reg_1921 <= data_array_V_fu_323_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        exp_res_V_10_reg_2140 <= exp_table_q6;
        exp_res_V_11_reg_2146 <= exp_table_q5;
        exp_res_V_12_reg_2152 <= exp_table_q4;
        exp_res_V_13_reg_2158 <= exp_table_q3;
        exp_res_V_14_reg_2164 <= exp_table_q2;
        exp_res_V_15_reg_2170 <= exp_table_q1;
        exp_res_V_16_reg_2176 <= exp_table_q0;
        exp_res_V_reg_2134 <= exp_table_q7;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        exp_res_V_17_reg_2216 <= exp_table_q1;
        exp_res_V_18_reg_2223 <= exp_table_q0;
        p_Result_66_reg_2230 <= ret_V_10_fu_1476_p2[32'd18];
        p_Result_67_reg_2240 <= p_Val2_13_fu_1490_p2[32'd17];
        p_Result_70_reg_2256 <= ret_V_11_fu_1534_p2[32'd18];
        p_Result_71_reg_2266 <= p_Val2_17_fu_1548_p2[32'd17];
        p_Val2_13_reg_2235 <= p_Val2_13_fu_1490_p2;
        p_Val2_17_reg_2261 <= p_Val2_17_fu_1548_p2;
        select_ln350_1_reg_2277 <= select_ln350_1_fu_1578_p3;
        select_ln350_reg_2251 <= select_ln350_fu_1520_p3;
        xor_ln302_13_reg_2245 <= xor_ln302_13_fu_1514_p2;
        xor_ln302_15_reg_2271 <= xor_ln302_15_fu_1572_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        inv_exp_sum_V_reg_2335 <= invert_table_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        lhs_2_reg_2192 <= lhs_2_fu_1330_p3;
        lhs_5_reg_2204 <= lhs_5_fu_1418_p3;
        rhs_2_reg_2198 <= rhs_2_fu_1374_p3;
        rhs_5_reg_2210 <= rhs_5_fu_1462_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        out_pack_data_1_reg_2360 <= {{grp_fu_275_p2[24:9]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        out_pack_data_2_reg_2370 <= {{grp_fu_275_p2[24:9]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        out_pack_data_3_reg_2380 <= {{grp_fu_275_p2[24:9]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        out_pack_data_reg_2350 <= {{grp_fu_275_p2[24:9]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        p_Result_21_reg_2049 <= p_Result_21_fu_1038_p3;
        p_Result_22_reg_2054 <= p_Result_22_fu_1064_p3;
        p_Result_23_reg_2059 <= p_Result_23_fu_1090_p3;
        p_Result_24_reg_2064 <= p_Result_24_fu_1116_p3;
        p_Result_25_reg_2069 <= p_Result_25_fu_1142_p3;
        p_Result_26_reg_2074 <= p_Result_26_fu_1168_p3;
        p_Result_27_reg_2079 <= p_Result_27_fu_1194_p3;
        p_Result_28_reg_2084 <= p_Result_28_fu_1220_p3;
        p_Result_29_reg_2089 <= p_Result_29_fu_1246_p3;
        p_Result_s_reg_2044 <= p_Result_s_fu_1012_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        p_Result_43_reg_2325 <= p_Result_43_fu_1849_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        p_Result_72_reg_2282 <= ret_V_12_fu_1668_p2[32'd18];
        p_Result_73_reg_2293 <= p_Val2_19_fu_1682_p2[32'd17];
        p_Val2_19_reg_2288 <= p_Val2_19_fu_1682_p2;
        rhs_7_reg_2299 <= rhs_7_fu_1714_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        p_Result_75_reg_2305 <= ret_V_13_fu_1761_p2[32'd18];
        p_Result_76_reg_2312 <= p_Val2_22_fu_1775_p2[32'd17];
        tmp_9_reg_2319 <= {{p_Val2_22_fu_1775_p2[17:8]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        select_ln66_1_reg_1997 <= select_ln66_1_fu_443_p3;
        select_ln66_3_reg_2003 <= select_ln66_3_fu_459_p3;
        select_ln66_4_reg_2009 <= select_ln66_4_fu_475_p3;
        select_ln66_reg_1991 <= select_ln66_fu_427_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        select_ln66_2_reg_2015 <= select_ln66_2_fu_491_p3;
        select_ln66_5_reg_2021 <= select_ln66_5_fu_507_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        select_ln66_6_reg_2027 <= select_ln66_6_fu_523_p3;
        select_ln66_7_reg_2033 <= select_ln66_7_fu_539_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        sext_ln1273_reg_2340 <= sext_ln1273_fu_1861_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        trunc_ln1_reg_2390 <= {{grp_fu_275_p2[24:9]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        trunc_ln818_1_reg_2400 <= {{grp_fu_275_p2[24:9]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        trunc_ln818_2_reg_2410 <= {{grp_fu_275_p2[24:9]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        trunc_ln818_3_reg_2420 <= {{grp_fu_275_p2[24:9]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        trunc_ln818_4_reg_2430 <= {{grp_fu_275_p2[24:9]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        x_max_V_reg_2039 <= x_max_V_fu_555_p3;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if (((layer16_out_empty_n == 1'b0) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

always @ (*) begin
    if ((layer17_out_TREADY == 1'b0)) begin
        ap_ST_fsm_state26_blk = 1'b1;
    end else begin
        ap_ST_fsm_state26_blk = 1'b0;
    end
end

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state27) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        exp_table_address0 = zext_ln225_9_fu_1290_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        exp_table_address0 = zext_ln225_7_fu_1282_p1;
    end else begin
        exp_table_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        exp_table_address1 = zext_ln225_8_fu_1286_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        exp_table_address1 = zext_ln225_6_fu_1278_p1;
    end else begin
        exp_table_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state7))) begin
        exp_table_ce0 = 1'b1;
    end else begin
        exp_table_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state7))) begin
        exp_table_ce1 = 1'b1;
    end else begin
        exp_table_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        exp_table_ce2 = 1'b1;
    end else begin
        exp_table_ce2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        exp_table_ce3 = 1'b1;
    end else begin
        exp_table_ce3 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        exp_table_ce4 = 1'b1;
    end else begin
        exp_table_ce4 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        exp_table_ce5 = 1'b1;
    end else begin
        exp_table_ce5 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        exp_table_ce6 = 1'b1;
    end else begin
        exp_table_ce6 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        exp_table_ce7 = 1'b1;
    end else begin
        exp_table_ce7 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | ((layer17_out_TREADY == 1'b1) & (1'b1 == ap_CS_fsm_state26)))) begin
        grp_fu_275_ce = 1'b1;
    end else begin
        grp_fu_275_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17))) begin
        grp_fu_275_p0 = sext_ln1273_reg_2340;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_275_p0 = sext_ln1273_fu_1861_p1;
    end else begin
        grp_fu_275_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_fu_275_p1 = zext_ln1273_9_fu_1901_p1;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        grp_fu_275_p1 = zext_ln1273_8_fu_1897_p1;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        grp_fu_275_p1 = zext_ln1273_7_fu_1893_p1;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        grp_fu_275_p1 = zext_ln1273_6_fu_1889_p1;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_fu_275_p1 = zext_ln1273_5_fu_1885_p1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_275_p1 = zext_ln1273_4_fu_1881_p1;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        grp_fu_275_p1 = zext_ln1273_3_fu_1877_p1;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_275_p1 = zext_ln1273_2_fu_1873_p1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_275_p1 = zext_ln1273_1_fu_1869_p1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_275_p1 = zext_ln1273_fu_1865_p1;
    end else begin
        grp_fu_275_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        invert_table_ce0 = 1'b1;
    end else begin
        invert_table_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer16_out_blk_n = layer16_out_empty_n;
    end else begin
        layer16_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((layer16_out_empty_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer16_out_read = 1'b1;
    end else begin
        layer16_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        layer17_out_TDATA_blk_n = layer17_out_TREADY;
    end else begin
        layer17_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer17_out_TREADY == 1'b1) & (1'b1 == ap_CS_fsm_state26))) begin
        layer17_out_TVALID = 1'b1;
    end else begin
        layer17_out_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((layer16_out_empty_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            if (((layer17_out_TREADY == 1'b1) & (1'b1 == ap_CS_fsm_state26))) begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln856_fu_1702_p2 = (exp_res_V_18_reg_2223 + exp_res_V_17_reg_2216);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((layer16_out_empty_n == 1'b0) | (ap_start == 1'b0));
end

assign data_array_V_fu_323_p1 = layer16_out_dout[15:0];

assign exp_res_V_8_cast39_fu_1586_p1 = exp_res_V_17_reg_2216;

assign exp_res_V_9_cast40_fu_1589_p1 = exp_res_V_18_reg_2223;

assign exp_table_address2 = zext_ln225_5_fu_1274_p1;

assign exp_table_address3 = zext_ln225_4_fu_1270_p1;

assign exp_table_address4 = zext_ln225_3_fu_1266_p1;

assign exp_table_address5 = zext_ln225_2_fu_1262_p1;

assign exp_table_address6 = zext_ln225_1_fu_1258_p1;

assign exp_table_address7 = zext_ln225_fu_1254_p1;

assign grp_fu_313_p4 = {{grp_fu_275_p2[24:9]}};

assign icmp_ln1651_1_fu_433_p2 = (($signed(data_array_V_2_reg_1949) < $signed(data_array_V_3_reg_1956)) ? 1'b1 : 1'b0);

assign icmp_ln1651_2_fu_481_p2 = (($signed(select_ln66_reg_1991) < $signed(select_ln66_1_reg_1997)) ? 1'b1 : 1'b0);

assign icmp_ln1651_3_fu_449_p2 = (($signed(data_array_V_4_reg_1963) < $signed(data_array_V_5_reg_1970)) ? 1'b1 : 1'b0);

assign icmp_ln1651_4_fu_465_p2 = (($signed(data_array_V_6_reg_1977) < $signed(data_array_V_7_reg_1984)) ? 1'b1 : 1'b0);

assign icmp_ln1651_5_fu_497_p2 = (($signed(select_ln66_3_reg_2003) < $signed(select_ln66_4_reg_2009)) ? 1'b1 : 1'b0);

assign icmp_ln1651_6_fu_513_p2 = (($signed(select_ln66_2_reg_2015) < $signed(select_ln66_5_reg_2021)) ? 1'b1 : 1'b0);

assign icmp_ln1651_7_fu_529_p2 = (($signed(data_array_V_8_reg_1928) < $signed(data_array_V_9_reg_1935)) ? 1'b1 : 1'b0);

assign icmp_ln1651_8_fu_545_p2 = (($signed(select_ln66_6_reg_2027) < $signed(select_ln66_7_reg_2033)) ? 1'b1 : 1'b0);

assign icmp_ln1651_fu_417_p2 = (($signed(data_array_V_reg_1921) < $signed(data_array_V_1_reg_1942)) ? 1'b1 : 1'b0);

assign invert_table_address0 = zext_ln235_fu_1857_p1;

assign layer17_out_TDATA = {{{{{{{{{{grp_fu_313_p4}, {trunc_ln818_4_reg_2430}}, {trunc_ln818_3_reg_2420}}, {trunc_ln818_2_reg_2410}}, {trunc_ln818_1_reg_2400}}, {trunc_ln1_reg_2390}}, {out_pack_data_3_reg_2380}}, {out_pack_data_2_reg_2370}}, {out_pack_data_1_reg_2360}}, {out_pack_data_reg_2350}};

assign lhs_2_fu_1330_p3 = ((p_Result_64_fu_1306_p3[0:0] == 1'b1) ? select_ln346_11_fu_1322_p3 : p_Val2_10_fu_1300_p2);

assign lhs_5_fu_1418_p3 = ((p_Result_68_fu_1394_p3[0:0] == 1'b1) ? select_ln346_13_fu_1410_p3 : p_Val2_14_fu_1388_p2);

assign lhs_6_fu_1619_p3 = ((or_ln302_1_fu_1607_p2[0:0] == 1'b1) ? select_ln302_fu_1613_p3 : select_ln350_reg_2251);

assign lhs_7_fu_1744_p3 = ((xor_ln302_10_fu_1732_p2[0:0] == 1'b1) ? select_ln346_10_fu_1736_p3 : p_Val2_19_reg_2288);

assign or_ln302_1_fu_1607_p2 = (xor_ln302_14_fu_1602_p2 | overflow_12_fu_1597_p2);

assign or_ln302_2_fu_1641_p2 = (xor_ln302_16_fu_1636_p2 | overflow_15_fu_1631_p2);

assign or_ln302_fu_1829_p2 = (xor_ln302_12_fu_1823_p2 | overflow_18_fu_1804_p2);

assign overflow_12_fu_1597_p2 = (xor_ln895_12_fu_1592_p2 & p_Result_67_reg_2240);

assign overflow_15_fu_1631_p2 = (xor_ln895_13_fu_1626_p2 & p_Result_71_reg_2266);

assign overflow_16_fu_1727_p2 = (xor_ln895_10_fu_1722_p2 & p_Result_73_reg_2293);

assign overflow_18_fu_1804_p2 = (xor_ln895_11_fu_1799_p2 & p_Result_76_reg_2312);

assign overflow_1_fu_638_p2 = (xor_ln895_1_fu_632_p2 & p_Result_47_fu_624_p3);

assign overflow_2_fu_681_p2 = (xor_ln895_2_fu_675_p2 & p_Result_49_fu_667_p3);

assign overflow_3_fu_724_p2 = (xor_ln895_3_fu_718_p2 & p_Result_51_fu_710_p3);

assign overflow_4_fu_767_p2 = (xor_ln895_4_fu_761_p2 & p_Result_53_fu_753_p3);

assign overflow_5_fu_810_p2 = (xor_ln895_5_fu_804_p2 & p_Result_55_fu_796_p3);

assign overflow_6_fu_853_p2 = (xor_ln895_6_fu_847_p2 & p_Result_57_fu_839_p3);

assign overflow_7_fu_896_p2 = (xor_ln895_7_fu_890_p2 & p_Result_59_fu_882_p3);

assign overflow_8_fu_939_p2 = (xor_ln895_8_fu_933_p2 & p_Result_61_fu_925_p3);

assign overflow_9_fu_982_p2 = (xor_ln895_9_fu_976_p2 & p_Result_63_fu_968_p3);

assign overflow_fu_595_p2 = (xor_ln895_fu_589_p2 & p_Result_45_fu_581_p3);

assign p_Result_21_fu_1038_p3 = ((xor_ln302_1_fu_644_p2[0:0] == 1'b1) ? select_ln346_1_fu_1020_p3 : tmp_s_fu_1028_p4);

assign p_Result_22_fu_1064_p3 = ((xor_ln302_2_fu_687_p2[0:0] == 1'b1) ? select_ln346_2_fu_1046_p3 : tmp_1_fu_1054_p4);

assign p_Result_23_fu_1090_p3 = ((xor_ln302_3_fu_730_p2[0:0] == 1'b1) ? select_ln346_3_fu_1072_p3 : tmp_2_fu_1080_p4);

assign p_Result_24_fu_1116_p3 = ((xor_ln302_4_fu_773_p2[0:0] == 1'b1) ? select_ln346_4_fu_1098_p3 : tmp_3_fu_1106_p4);

assign p_Result_25_fu_1142_p3 = ((xor_ln302_5_fu_816_p2[0:0] == 1'b1) ? select_ln346_5_fu_1124_p3 : tmp_4_fu_1132_p4);

assign p_Result_26_fu_1168_p3 = ((xor_ln302_6_fu_859_p2[0:0] == 1'b1) ? select_ln346_6_fu_1150_p3 : tmp_5_fu_1158_p4);

assign p_Result_27_fu_1194_p3 = ((xor_ln302_7_fu_902_p2[0:0] == 1'b1) ? select_ln346_7_fu_1176_p3 : tmp_6_fu_1184_p4);

assign p_Result_28_fu_1220_p3 = ((xor_ln302_8_fu_945_p2[0:0] == 1'b1) ? select_ln346_8_fu_1202_p3 : tmp_7_fu_1210_p4);

assign p_Result_29_fu_1246_p3 = ((xor_ln302_9_fu_988_p2[0:0] == 1'b1) ? select_ln346_9_fu_1228_p3 : tmp_8_fu_1236_p4);

assign p_Result_43_fu_1849_p3 = ((or_ln302_fu_1829_p2[0:0] == 1'b1) ? select_ln302_8_fu_1835_p3 : select_ln350_2_fu_1842_p3);

assign p_Result_44_fu_573_p3 = ret_V_fu_567_p2[32'd16];

assign p_Result_45_fu_581_p3 = ret_V_fu_567_p2[32'd15];

assign p_Result_46_fu_616_p3 = ret_V_1_fu_610_p2[32'd16];

assign p_Result_47_fu_624_p3 = ret_V_1_fu_610_p2[32'd15];

assign p_Result_48_fu_659_p3 = ret_V_2_fu_653_p2[32'd16];

assign p_Result_49_fu_667_p3 = ret_V_2_fu_653_p2[32'd15];

assign p_Result_50_fu_702_p3 = ret_V_3_fu_696_p2[32'd16];

assign p_Result_51_fu_710_p3 = ret_V_3_fu_696_p2[32'd15];

assign p_Result_52_fu_745_p3 = ret_V_4_fu_739_p2[32'd16];

assign p_Result_53_fu_753_p3 = ret_V_4_fu_739_p2[32'd15];

assign p_Result_54_fu_788_p3 = ret_V_5_fu_782_p2[32'd16];

assign p_Result_55_fu_796_p3 = ret_V_5_fu_782_p2[32'd15];

assign p_Result_56_fu_831_p3 = ret_V_6_fu_825_p2[32'd16];

assign p_Result_57_fu_839_p3 = ret_V_6_fu_825_p2[32'd15];

assign p_Result_58_fu_874_p3 = ret_V_7_fu_868_p2[32'd16];

assign p_Result_59_fu_882_p3 = ret_V_7_fu_868_p2[32'd15];

assign p_Result_60_fu_917_p3 = ret_V_8_fu_911_p2[32'd16];

assign p_Result_61_fu_925_p3 = ret_V_8_fu_911_p2[32'd15];

assign p_Result_62_fu_960_p3 = ret_V_9_fu_954_p2[32'd16];

assign p_Result_63_fu_968_p3 = ret_V_9_fu_954_p2[32'd15];

assign p_Result_64_fu_1306_p3 = p_Val2_10_fu_1300_p2[32'd17];

assign p_Result_65_fu_1350_p3 = p_Val2_11_fu_1344_p2[32'd17];

assign p_Result_66_fu_1482_p3 = ret_V_10_fu_1476_p2[32'd18];

assign p_Result_67_fu_1494_p3 = p_Val2_13_fu_1490_p2[32'd17];

assign p_Result_68_fu_1394_p3 = p_Val2_14_fu_1388_p2[32'd17];

assign p_Result_69_fu_1438_p3 = p_Val2_15_fu_1432_p2[32'd17];

assign p_Result_70_fu_1540_p3 = ret_V_11_fu_1534_p2[32'd18];

assign p_Result_71_fu_1552_p3 = p_Val2_17_fu_1548_p2[32'd17];

assign p_Result_74_fu_1706_p3 = p_Val2_20_fu_1696_p2[32'd17];

assign p_Result_s_fu_1012_p3 = ((xor_ln302_fu_601_p2[0:0] == 1'b1) ? select_ln346_fu_994_p3 : tmp_fu_1002_p4);

assign p_Val2_10_fu_1300_p2 = (zext_ln44_1_fu_1297_p1 + zext_ln44_fu_1294_p1);

assign p_Val2_11_fu_1344_p2 = (zext_ln44_3_fu_1341_p1 + zext_ln44_2_fu_1338_p1);

assign p_Val2_13_fu_1490_p2 = ($signed(rhs_2_reg_2198) + $signed(lhs_2_reg_2192));

assign p_Val2_14_fu_1388_p2 = (zext_ln44_5_fu_1385_p1 + zext_ln44_4_fu_1382_p1);

assign p_Val2_15_fu_1432_p2 = (zext_ln44_7_fu_1429_p1 + zext_ln44_6_fu_1426_p1);

assign p_Val2_17_fu_1548_p2 = ($signed(rhs_5_reg_2210) + $signed(lhs_5_reg_2204));

assign p_Val2_19_fu_1682_p2 = ($signed(lhs_6_fu_1619_p3) + $signed(rhs_6_fu_1653_p3));

assign p_Val2_20_fu_1696_p2 = (exp_res_V_9_cast40_fu_1589_p1 + exp_res_V_8_cast39_fu_1586_p1);

assign p_Val2_22_fu_1775_p2 = ($signed(lhs_7_fu_1744_p3) + $signed(zext_ln813_fu_1751_p1));

assign ret_V_10_fu_1476_p2 = ($signed(sext_ln813_4_fu_1473_p1) + $signed(sext_ln813_3_fu_1470_p1));

assign ret_V_11_fu_1534_p2 = ($signed(sext_ln813_6_fu_1531_p1) + $signed(sext_ln813_5_fu_1528_p1));

assign ret_V_12_fu_1668_p2 = ($signed(sext_ln813_fu_1660_p1) + $signed(sext_ln813_1_fu_1664_p1));

assign ret_V_13_fu_1761_p2 = ($signed(sext_ln813_2_fu_1754_p1) + $signed(zext_ln813_1_fu_1758_p1));

assign ret_V_1_fu_610_p2 = ($signed(sext_ln1348_2_fu_607_p1) - $signed(sext_ln1348_1_fu_564_p1));

assign ret_V_2_fu_653_p2 = ($signed(sext_ln1348_3_fu_650_p1) - $signed(sext_ln1348_1_fu_564_p1));

assign ret_V_3_fu_696_p2 = ($signed(sext_ln1348_4_fu_693_p1) - $signed(sext_ln1348_1_fu_564_p1));

assign ret_V_4_fu_739_p2 = ($signed(sext_ln1348_5_fu_736_p1) - $signed(sext_ln1348_1_fu_564_p1));

assign ret_V_5_fu_782_p2 = ($signed(sext_ln1348_6_fu_779_p1) - $signed(sext_ln1348_1_fu_564_p1));

assign ret_V_6_fu_825_p2 = ($signed(sext_ln1348_7_fu_822_p1) - $signed(sext_ln1348_1_fu_564_p1));

assign ret_V_7_fu_868_p2 = ($signed(sext_ln1348_8_fu_865_p1) - $signed(sext_ln1348_1_fu_564_p1));

assign ret_V_8_fu_911_p2 = ($signed(sext_ln1348_9_fu_908_p1) - $signed(sext_ln1348_1_fu_564_p1));

assign ret_V_9_fu_954_p2 = ($signed(sext_ln1348_10_fu_951_p1) - $signed(sext_ln1348_1_fu_564_p1));

assign ret_V_fu_567_p2 = ($signed(sext_ln1348_fu_561_p1) - $signed(sext_ln1348_1_fu_564_p1));

assign rhs_2_fu_1374_p3 = ((p_Result_65_fu_1350_p3[0:0] == 1'b1) ? select_ln346_12_fu_1366_p3 : p_Val2_11_fu_1344_p2);

assign rhs_5_fu_1462_p3 = ((p_Result_69_fu_1438_p3[0:0] == 1'b1) ? select_ln346_14_fu_1454_p3 : p_Val2_15_fu_1432_p2);

assign rhs_6_fu_1653_p3 = ((or_ln302_2_fu_1641_p2[0:0] == 1'b1) ? select_ln302_5_fu_1647_p3 : select_ln350_1_reg_2277);

assign rhs_7_fu_1714_p3 = ((p_Result_74_fu_1706_p3[0:0] == 1'b1) ? 17'd131071 : add_ln856_fu_1702_p2);

assign select_ln302_5_fu_1647_p3 = ((xor_ln302_15_reg_2271[0:0] == 1'b1) ? 18'd131071 : p_Val2_17_reg_2261);

assign select_ln302_8_fu_1835_p3 = ((xor_ln302_11_fu_1819_p2[0:0] == 1'b1) ? 10'd511 : tmp_9_reg_2319);

assign select_ln302_fu_1613_p3 = ((xor_ln302_13_reg_2245[0:0] == 1'b1) ? 18'd131071 : p_Val2_13_reg_2235);

assign select_ln346_10_fu_1736_p3 = ((overflow_16_fu_1727_p2[0:0] == 1'b1) ? 18'd131071 : 18'd131072);

assign select_ln346_11_fu_1322_p3 = ((tmp_31_fu_1314_p3[0:0] == 1'b1) ? 18'd131071 : 18'd131072);

assign select_ln346_12_fu_1366_p3 = ((tmp_33_fu_1358_p3[0:0] == 1'b1) ? 18'd131071 : 18'd131072);

assign select_ln346_13_fu_1410_p3 = ((tmp_37_fu_1402_p3[0:0] == 1'b1) ? 18'd131071 : 18'd131072);

assign select_ln346_14_fu_1454_p3 = ((tmp_39_fu_1446_p3[0:0] == 1'b1) ? 18'd131071 : 18'd131072);

assign select_ln346_1_fu_1020_p3 = ((overflow_1_fu_638_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln346_2_fu_1046_p3 = ((overflow_2_fu_681_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln346_3_fu_1072_p3 = ((overflow_3_fu_724_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln346_4_fu_1098_p3 = ((overflow_4_fu_767_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln346_5_fu_1124_p3 = ((overflow_5_fu_810_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln346_6_fu_1150_p3 = ((overflow_6_fu_853_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln346_7_fu_1176_p3 = ((overflow_7_fu_896_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln346_8_fu_1202_p3 = ((overflow_8_fu_939_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln346_9_fu_1228_p3 = ((overflow_9_fu_982_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln346_fu_994_p3 = ((overflow_fu_595_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln350_1_fu_1578_p3 = ((underflow_2_fu_1566_p2[0:0] == 1'b1) ? 18'd131072 : p_Val2_17_fu_1548_p2);

assign select_ln350_2_fu_1842_p3 = ((underflow_fu_1814_p2[0:0] == 1'b1) ? 10'd512 : tmp_9_reg_2319);

assign select_ln350_fu_1520_p3 = ((underflow_1_fu_1508_p2[0:0] == 1'b1) ? 18'd131072 : p_Val2_13_fu_1490_p2);

assign select_ln66_1_fu_443_p3 = ((xor_ln1651_1_fu_437_p2[0:0] == 1'b1) ? data_array_V_2_reg_1949 : data_array_V_3_reg_1956);

assign select_ln66_2_fu_491_p3 = ((xor_ln1651_2_fu_485_p2[0:0] == 1'b1) ? select_ln66_reg_1991 : select_ln66_1_reg_1997);

assign select_ln66_3_fu_459_p3 = ((xor_ln1651_3_fu_453_p2[0:0] == 1'b1) ? data_array_V_4_reg_1963 : data_array_V_5_reg_1970);

assign select_ln66_4_fu_475_p3 = ((xor_ln1651_4_fu_469_p2[0:0] == 1'b1) ? data_array_V_6_reg_1977 : data_array_V_7_reg_1984);

assign select_ln66_5_fu_507_p3 = ((xor_ln1651_5_fu_501_p2[0:0] == 1'b1) ? select_ln66_3_reg_2003 : select_ln66_4_reg_2009);

assign select_ln66_6_fu_523_p3 = ((xor_ln1651_6_fu_517_p2[0:0] == 1'b1) ? select_ln66_2_reg_2015 : select_ln66_5_reg_2021);

assign select_ln66_7_fu_539_p3 = ((xor_ln1651_7_fu_533_p2[0:0] == 1'b1) ? data_array_V_8_reg_1928 : data_array_V_9_reg_1935);

assign select_ln66_fu_427_p3 = ((xor_ln1651_fu_421_p2[0:0] == 1'b1) ? data_array_V_reg_1921 : data_array_V_1_reg_1942);

assign sext_ln1273_fu_1861_p1 = $signed(inv_exp_sum_V_reg_2335);

assign sext_ln1348_10_fu_951_p1 = data_array_V_9_reg_1935;

assign sext_ln1348_1_fu_564_p1 = $signed(x_max_V_reg_2039);

assign sext_ln1348_2_fu_607_p1 = data_array_V_1_reg_1942;

assign sext_ln1348_3_fu_650_p1 = data_array_V_2_reg_1949;

assign sext_ln1348_4_fu_693_p1 = data_array_V_3_reg_1956;

assign sext_ln1348_5_fu_736_p1 = data_array_V_4_reg_1963;

assign sext_ln1348_6_fu_779_p1 = data_array_V_5_reg_1970;

assign sext_ln1348_7_fu_822_p1 = data_array_V_6_reg_1977;

assign sext_ln1348_8_fu_865_p1 = data_array_V_7_reg_1984;

assign sext_ln1348_9_fu_908_p1 = data_array_V_8_reg_1928;

assign sext_ln1348_fu_561_p1 = data_array_V_reg_1921;

assign sext_ln813_1_fu_1664_p1 = rhs_6_fu_1653_p3;

assign sext_ln813_2_fu_1754_p1 = lhs_7_fu_1744_p3;

assign sext_ln813_3_fu_1470_p1 = lhs_2_reg_2192;

assign sext_ln813_4_fu_1473_p1 = rhs_2_reg_2198;

assign sext_ln813_5_fu_1528_p1 = lhs_5_reg_2204;

assign sext_ln813_6_fu_1531_p1 = rhs_5_reg_2210;

assign sext_ln813_fu_1660_p1 = lhs_6_fu_1619_p3;

assign tmp_1_fu_1054_p4 = {{ret_V_2_fu_653_p2[15:6]}};

assign tmp_2_fu_1080_p4 = {{ret_V_3_fu_696_p2[15:6]}};

assign tmp_31_fu_1314_p3 = p_Val2_10_fu_1300_p2[32'd17];

assign tmp_33_fu_1358_p3 = p_Val2_11_fu_1344_p2[32'd17];

assign tmp_37_fu_1402_p3 = p_Val2_14_fu_1388_p2[32'd17];

assign tmp_39_fu_1446_p3 = p_Val2_15_fu_1432_p2[32'd17];

assign tmp_3_fu_1106_p4 = {{ret_V_4_fu_739_p2[15:6]}};

assign tmp_4_fu_1132_p4 = {{ret_V_5_fu_782_p2[15:6]}};

assign tmp_5_fu_1158_p4 = {{ret_V_6_fu_825_p2[15:6]}};

assign tmp_6_fu_1184_p4 = {{ret_V_7_fu_868_p2[15:6]}};

assign tmp_7_fu_1210_p4 = {{ret_V_8_fu_911_p2[15:6]}};

assign tmp_8_fu_1236_p4 = {{ret_V_9_fu_954_p2[15:6]}};

assign tmp_fu_1002_p4 = {{ret_V_fu_567_p2[15:6]}};

assign tmp_s_fu_1028_p4 = {{ret_V_1_fu_610_p2[15:6]}};

assign underflow_1_fu_1508_p2 = (xor_ln896_1_fu_1502_p2 & p_Result_66_fu_1482_p3);

assign underflow_2_fu_1566_p2 = (xor_ln896_2_fu_1560_p2 & p_Result_70_fu_1540_p3);

assign underflow_fu_1814_p2 = (xor_ln896_fu_1809_p2 & p_Result_75_reg_2305);

assign x_max_V_fu_555_p3 = ((xor_ln1651_8_fu_549_p2[0:0] == 1'b1) ? select_ln66_6_reg_2027 : select_ln66_7_reg_2033);

assign xor_ln1651_1_fu_437_p2 = (icmp_ln1651_1_fu_433_p2 ^ 1'd1);

assign xor_ln1651_2_fu_485_p2 = (icmp_ln1651_2_fu_481_p2 ^ 1'd1);

assign xor_ln1651_3_fu_453_p2 = (icmp_ln1651_3_fu_449_p2 ^ 1'd1);

assign xor_ln1651_4_fu_469_p2 = (icmp_ln1651_4_fu_465_p2 ^ 1'd1);

assign xor_ln1651_5_fu_501_p2 = (icmp_ln1651_5_fu_497_p2 ^ 1'd1);

assign xor_ln1651_6_fu_517_p2 = (icmp_ln1651_6_fu_513_p2 ^ 1'd1);

assign xor_ln1651_7_fu_533_p2 = (icmp_ln1651_7_fu_529_p2 ^ 1'd1);

assign xor_ln1651_8_fu_549_p2 = (icmp_ln1651_8_fu_545_p2 ^ 1'd1);

assign xor_ln1651_fu_421_p2 = (icmp_ln1651_fu_417_p2 ^ 1'd1);

assign xor_ln302_10_fu_1732_p2 = (p_Result_73_reg_2293 ^ p_Result_72_reg_2282);

assign xor_ln302_11_fu_1819_p2 = (p_Result_76_reg_2312 ^ p_Result_75_reg_2305);

assign xor_ln302_12_fu_1823_p2 = (xor_ln302_11_fu_1819_p2 ^ 1'd1);

assign xor_ln302_13_fu_1514_p2 = (p_Result_67_fu_1494_p3 ^ p_Result_66_fu_1482_p3);

assign xor_ln302_14_fu_1602_p2 = (xor_ln302_13_reg_2245 ^ 1'd1);

assign xor_ln302_15_fu_1572_p2 = (p_Result_71_fu_1552_p3 ^ p_Result_70_fu_1540_p3);

assign xor_ln302_16_fu_1636_p2 = (xor_ln302_15_reg_2271 ^ 1'd1);

assign xor_ln302_1_fu_644_p2 = (p_Result_47_fu_624_p3 ^ p_Result_46_fu_616_p3);

assign xor_ln302_2_fu_687_p2 = (p_Result_49_fu_667_p3 ^ p_Result_48_fu_659_p3);

assign xor_ln302_3_fu_730_p2 = (p_Result_51_fu_710_p3 ^ p_Result_50_fu_702_p3);

assign xor_ln302_4_fu_773_p2 = (p_Result_53_fu_753_p3 ^ p_Result_52_fu_745_p3);

assign xor_ln302_5_fu_816_p2 = (p_Result_55_fu_796_p3 ^ p_Result_54_fu_788_p3);

assign xor_ln302_6_fu_859_p2 = (p_Result_57_fu_839_p3 ^ p_Result_56_fu_831_p3);

assign xor_ln302_7_fu_902_p2 = (p_Result_59_fu_882_p3 ^ p_Result_58_fu_874_p3);

assign xor_ln302_8_fu_945_p2 = (p_Result_61_fu_925_p3 ^ p_Result_60_fu_917_p3);

assign xor_ln302_9_fu_988_p2 = (p_Result_63_fu_968_p3 ^ p_Result_62_fu_960_p3);

assign xor_ln302_fu_601_p2 = (p_Result_45_fu_581_p3 ^ p_Result_44_fu_573_p3);

assign xor_ln895_10_fu_1722_p2 = (p_Result_72_reg_2282 ^ 1'd1);

assign xor_ln895_11_fu_1799_p2 = (p_Result_75_reg_2305 ^ 1'd1);

assign xor_ln895_12_fu_1592_p2 = (p_Result_66_reg_2230 ^ 1'd1);

assign xor_ln895_13_fu_1626_p2 = (p_Result_70_reg_2256 ^ 1'd1);

assign xor_ln895_1_fu_632_p2 = (p_Result_46_fu_616_p3 ^ 1'd1);

assign xor_ln895_2_fu_675_p2 = (p_Result_48_fu_659_p3 ^ 1'd1);

assign xor_ln895_3_fu_718_p2 = (p_Result_50_fu_702_p3 ^ 1'd1);

assign xor_ln895_4_fu_761_p2 = (p_Result_52_fu_745_p3 ^ 1'd1);

assign xor_ln895_5_fu_804_p2 = (p_Result_54_fu_788_p3 ^ 1'd1);

assign xor_ln895_6_fu_847_p2 = (p_Result_56_fu_831_p3 ^ 1'd1);

assign xor_ln895_7_fu_890_p2 = (p_Result_58_fu_874_p3 ^ 1'd1);

assign xor_ln895_8_fu_933_p2 = (p_Result_60_fu_917_p3 ^ 1'd1);

assign xor_ln895_9_fu_976_p2 = (p_Result_62_fu_960_p3 ^ 1'd1);

assign xor_ln895_fu_589_p2 = (p_Result_44_fu_573_p3 ^ 1'd1);

assign xor_ln896_1_fu_1502_p2 = (p_Result_67_fu_1494_p3 ^ 1'd1);

assign xor_ln896_2_fu_1560_p2 = (p_Result_71_fu_1552_p3 ^ 1'd1);

assign xor_ln896_fu_1809_p2 = (p_Result_76_reg_2312 ^ 1'd1);

assign zext_ln1273_1_fu_1869_p1 = exp_res_V_10_reg_2140;

assign zext_ln1273_2_fu_1873_p1 = exp_res_V_11_reg_2146;

assign zext_ln1273_3_fu_1877_p1 = exp_res_V_12_reg_2152;

assign zext_ln1273_4_fu_1881_p1 = exp_res_V_13_reg_2158;

assign zext_ln1273_5_fu_1885_p1 = exp_res_V_14_reg_2164;

assign zext_ln1273_6_fu_1889_p1 = exp_res_V_15_reg_2170;

assign zext_ln1273_7_fu_1893_p1 = exp_res_V_16_reg_2176;

assign zext_ln1273_8_fu_1897_p1 = exp_res_V_17_reg_2216;

assign zext_ln1273_9_fu_1901_p1 = exp_res_V_18_reg_2223;

assign zext_ln1273_fu_1865_p1 = exp_res_V_reg_2134;

assign zext_ln225_1_fu_1258_p1 = p_Result_21_reg_2049;

assign zext_ln225_2_fu_1262_p1 = p_Result_22_reg_2054;

assign zext_ln225_3_fu_1266_p1 = p_Result_23_reg_2059;

assign zext_ln225_4_fu_1270_p1 = p_Result_24_reg_2064;

assign zext_ln225_5_fu_1274_p1 = p_Result_25_reg_2069;

assign zext_ln225_6_fu_1278_p1 = p_Result_26_reg_2074;

assign zext_ln225_7_fu_1282_p1 = p_Result_27_reg_2079;

assign zext_ln225_8_fu_1286_p1 = p_Result_28_reg_2084;

assign zext_ln225_9_fu_1290_p1 = p_Result_29_reg_2089;

assign zext_ln225_fu_1254_p1 = p_Result_s_reg_2044;

assign zext_ln235_fu_1857_p1 = p_Result_43_reg_2325;

assign zext_ln44_1_fu_1297_p1 = exp_res_V_10_reg_2140;

assign zext_ln44_2_fu_1338_p1 = exp_res_V_11_reg_2146;

assign zext_ln44_3_fu_1341_p1 = exp_res_V_12_reg_2152;

assign zext_ln44_4_fu_1382_p1 = exp_res_V_13_reg_2158;

assign zext_ln44_5_fu_1385_p1 = exp_res_V_14_reg_2164;

assign zext_ln44_6_fu_1426_p1 = exp_res_V_15_reg_2170;

assign zext_ln44_7_fu_1429_p1 = exp_res_V_16_reg_2176;

assign zext_ln44_fu_1294_p1 = exp_res_V_reg_2134;

assign zext_ln813_1_fu_1758_p1 = rhs_7_reg_2299;

assign zext_ln813_fu_1751_p1 = rhs_7_reg_2299;

endmodule //myproject_softmax_stable_array_array_ap_fixed_16_5_5_3_0_10u_softmax_config17_s
