-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_shift_line_buffer_array_ap_fixed_16_5_5_3_0_1u_config2_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (15 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_i : IN STD_LOGIC_VECTOR (15 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_o_ap_vld : OUT STD_LOGIC;
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18 : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18_ap_vld : OUT STD_LOGIC;
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_i : IN STD_LOGIC_VECTOR (15 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o_ap_vld : OUT STD_LOGIC;
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15 : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_ap_vld : OUT STD_LOGIC;
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_i : IN STD_LOGIC_VECTOR (15 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o_ap_vld : OUT STD_LOGIC;
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12 : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_ap_vld : OUT STD_LOGIC;
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_i : IN STD_LOGIC_VECTOR (15 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o_ap_vld : OUT STD_LOGIC;
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_i : IN STD_LOGIC_VECTOR (15 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o_ap_vld : OUT STD_LOGIC;
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_i : IN STD_LOGIC_VECTOR (15 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o_ap_vld : OUT STD_LOGIC );
end;


architecture behav of myproject_shift_line_buffer_array_ap_fixed_16_5_5_3_0_1u_config2_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal void_conv_2d_buffer_resource_cl_stream_stream_weight_t_bias_t_line_buffer_1_ce0 : STD_LOGIC;
    signal void_conv_2d_buffer_resource_cl_stream_stream_weight_t_bias_t_line_buffer_1_we0 : STD_LOGIC;
    signal void_conv_2d_buffer_resource_cl_stream_stream_weight_t_bias_t_line_buffer_1_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal void_conv_2d_buffer_resource_cl_stream_stream_weight_t_bias_t_line_buffer_ce0 : STD_LOGIC;
    signal void_conv_2d_buffer_resource_cl_stream_stream_weight_t_bias_t_line_buffer_we0 : STD_LOGIC;
    signal void_conv_2d_buffer_resource_cl_stream_stream_weight_t_bias_t_line_buffer_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_shift_line_buffer_array_ap_fixed_16_5_5_3_0_1u_config2_s_void_conv_2d_buffer_bkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    void_conv_2d_buffer_resource_cl_stream_stream_weight_t_bias_t_line_buffer_1_U : component myproject_shift_line_buffer_array_ap_fixed_16_5_5_3_0_1u_config2_s_void_conv_2d_buffer_bkb
    generic map (
        DataWidth => 16,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv4_9,
        ce0 => void_conv_2d_buffer_resource_cl_stream_stream_weight_t_bias_t_line_buffer_1_ce0,
        we0 => void_conv_2d_buffer_resource_cl_stream_stream_weight_t_bias_t_line_buffer_1_we0,
        d0 => p_read,
        q0 => void_conv_2d_buffer_resource_cl_stream_stream_weight_t_bias_t_line_buffer_1_q0);

    void_conv_2d_buffer_resource_cl_stream_stream_weight_t_bias_t_line_buffer_U : component myproject_shift_line_buffer_array_ap_fixed_16_5_5_3_0_1u_config2_s_void_conv_2d_buffer_bkb
    generic map (
        DataWidth => 16,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv4_9,
        ce0 => void_conv_2d_buffer_resource_cl_stream_stream_weight_t_bias_t_line_buffer_ce0,
        we0 => void_conv_2d_buffer_resource_cl_stream_stream_weight_t_bias_t_line_buffer_we0,
        d0 => void_conv_2d_buffer_resource_cl_stream_stream_weight_t_bias_t_line_buffer_1_q0,
        q0 => void_conv_2d_buffer_resource_cl_stream_stream_weight_t_bias_t_line_buffer_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o_assign_proc : process(ap_CS_fsm_state1, p_read, void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o <= p_read;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_i;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o_assign_proc : process(ap_CS_fsm_state1, void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_i, void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_i;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_i;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_i;

    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o_assign_proc : process(ap_CS_fsm_state1, void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_i, void_conv_2d_buffer_resource_cl_stream_stream_weight_t_bias_t_line_buffer_1_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o <= void_conv_2d_buffer_resource_cl_stream_stream_weight_t_bias_t_line_buffer_1_q0;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_i;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o_assign_proc : process(ap_CS_fsm_state1, void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_i, void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_i;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_i;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_i;

    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o_assign_proc : process(ap_CS_fsm_state1, void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_i, void_conv_2d_buffer_resource_cl_stream_stream_weight_t_bias_t_line_buffer_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o <= void_conv_2d_buffer_resource_cl_stream_stream_weight_t_bias_t_line_buffer_q0;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_i;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_o_assign_proc : process(ap_CS_fsm_state1, void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_i, void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_o <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_i;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_o <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_i;
        end if; 
    end process;


    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_o_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_i;

    void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    void_conv_2d_buffer_resource_cl_stream_stream_weight_t_bias_t_line_buffer_1_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_conv_2d_buffer_resource_cl_stream_stream_weight_t_bias_t_line_buffer_1_ce0 <= ap_const_logic_1;
        else 
            void_conv_2d_buffer_resource_cl_stream_stream_weight_t_bias_t_line_buffer_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    void_conv_2d_buffer_resource_cl_stream_stream_weight_t_bias_t_line_buffer_1_we0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_conv_2d_buffer_resource_cl_stream_stream_weight_t_bias_t_line_buffer_1_we0 <= ap_const_logic_1;
        else 
            void_conv_2d_buffer_resource_cl_stream_stream_weight_t_bias_t_line_buffer_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    void_conv_2d_buffer_resource_cl_stream_stream_weight_t_bias_t_line_buffer_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_conv_2d_buffer_resource_cl_stream_stream_weight_t_bias_t_line_buffer_ce0 <= ap_const_logic_1;
        else 
            void_conv_2d_buffer_resource_cl_stream_stream_weight_t_bias_t_line_buffer_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    void_conv_2d_buffer_resource_cl_stream_stream_weight_t_bias_t_line_buffer_we0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            void_conv_2d_buffer_resource_cl_stream_stream_weight_t_bias_t_line_buffer_we0 <= ap_const_logic_1;
        else 
            void_conv_2d_buffer_resource_cl_stream_stream_weight_t_bias_t_line_buffer_we0 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
