-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_pooling2d_cl_array_ap_ufixed_4u_array_ap_ufixed_6_0_4_0_0_4u_config5_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    layer5_out_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    layer5_out_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    layer5_out_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    layer5_out_full_n : IN STD_LOGIC;
    layer5_out_write : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    layer4_out_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    layer4_out_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    layer4_out_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    layer4_out_empty_n : IN STD_LOGIC;
    layer4_out_read : OUT STD_LOGIC );
end;


architecture behav of myproject_pooling2d_cl_array_ap_ufixed_4u_array_ap_ufixed_6_0_4_0_0_4u_config5_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal internal_ap_ready : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage1_iter1 : BOOLEAN;
    signal icmp_ln55_reg_908 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln55_reg_908_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln55_2_reg_995 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op147_write_state6 : BOOLEAN;
    signal ap_block_state6_pp0_stage1_iter2 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal icmp_ln109_reg_888 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal sY_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal pY_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal pX_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal sX_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_17 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_16 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_15 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_14 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_3_ce0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_3_we0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_3_q0 : STD_LOGIC_VECTOR (5 downto 0);
    signal void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_2_ce0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_2_we0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_2_d0 : STD_LOGIC_VECTOR (5 downto 0);
    signal void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_2_q0 : STD_LOGIC_VECTOR (5 downto 0);
    signal void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_1_ce0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_1_we0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_1_d0 : STD_LOGIC_VECTOR (5 downto 0);
    signal void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_1_q0 : STD_LOGIC_VECTOR (5 downto 0);
    signal void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_ce0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_we0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_d0 : STD_LOGIC_VECTOR (5 downto 0);
    signal void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_q0 : STD_LOGIC_VECTOR (5 downto 0);
    signal layer4_out_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal layer5_out_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal icmp_ln109_fu_156_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln109_reg_888_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal pX_1_load_reg_892 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln76_fu_172_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln76_reg_897 : STD_LOGIC_VECTOR (31 downto 0);
    signal sX_1_load_reg_903 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal icmp_ln55_fu_187_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln55_6_fu_193_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln55_6_reg_913 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln76_fu_198_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln76_reg_918 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln76_reg_918_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln80_fu_207_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln80_reg_922 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln115_fu_213_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln115_reg_928 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln115_9_reg_934 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln115_s_reg_940 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln115_4_reg_946 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_1_reg_952 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_2_reg_958 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_s_reg_964 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_0_reg_970 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln91_fu_299_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln91_reg_976 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln80_fu_316_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln80_reg_981 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_load_fu_138_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sY_1_load_1_reg_985 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_142_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln86_reg_990 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln55_2_fu_408_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln66_fu_456_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln66_reg_999 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln66_32_fu_476_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln66_32_reg_1005 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln66_34_fu_526_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln66_34_reg_1011 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln66_35_fu_546_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln66_35_reg_1017 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln66_37_fu_596_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln66_37_reg_1023 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln66_38_fu_616_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln66_38_reg_1029 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln66_40_fu_666_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln66_40_reg_1035 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln66_41_fu_686_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln66_41_reg_1041 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln86_fu_711_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln86_reg_1047 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Val2_s_fu_750_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_Val2_s_reg_1052 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_Val2_115_fu_786_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_Val2_115_reg_1057 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_Val2_116_fu_822_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_Val2_116_reg_1062 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_Val2_117_fu_858_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_Val2_117_reg_1067 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_phi_mux_storemerge_phi_fu_131_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter2_storemerge_reg_127 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_storemerge_reg_127 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_storemerge_reg_127 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_allocacmp_sY_1_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_allocacmp_pY_1_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_allocacmp_pX_1_load : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_allocacmp_sX_1_load : STD_LOGIC_VECTOR (31 downto 0);
    signal indvar_flatten_fu_110 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln109_fu_162_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_pp0_stage1_01001 : BOOLEAN;
    signal select_ln91_fu_292_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln55_5_fu_397_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln55_fu_403_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal pool_window_V_fu_414_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal pool_window_V_32_fu_422_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln1651_fu_444_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1651_fu_450_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal pool_window_V_33_fu_429_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal pool_window_V_34_fu_437_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln1651_32_fu_464_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1651_32_fu_470_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal pool_window_V_35_fu_484_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal pool_window_V_36_fu_492_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln1651_34_fu_514_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1651_34_fu_520_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal pool_window_V_37_fu_499_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal pool_window_V_38_fu_507_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln1651_35_fu_534_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1651_35_fu_540_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal pool_window_V_39_fu_554_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal pool_window_V_40_fu_562_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln1651_37_fu_584_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1651_37_fu_590_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal pool_window_V_41_fu_569_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal pool_window_V_42_fu_577_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln1651_38_fu_604_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1651_38_fu_610_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal pool_window_V_43_fu_624_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal pool_window_V_44_fu_632_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln1651_40_fu_654_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1651_40_fu_660_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal pool_window_V_45_fu_639_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal pool_window_V_46_fu_647_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln1651_41_fu_674_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1651_41_fu_680_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln86_fu_704_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln1651_33_fu_722_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1651_33_fu_726_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_24_fu_732_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_25_fu_741_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln1651_36_fu_758_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1651_36_fu_762_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_27_fu_768_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_28_fu_777_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln1651_39_fu_794_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1651_39_fu_798_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_30_fu_804_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_31_fu_813_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln1651_42_fu_830_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1651_42_fu_834_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_33_fu_840_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_34_fu_849_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_idle_pp0_1to2 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_298 : BOOLEAN;
    signal ap_condition_296 : BOOLEAN;
    signal ap_condition_146 : BOOLEAN;
    signal ap_condition_771 : BOOLEAN;
    signal ap_condition_777 : BOOLEAN;
    signal ap_condition_781 : BOOLEAN;
    signal ap_condition_354 : BOOLEAN;
    signal ap_condition_233 : BOOLEAN;
    signal ap_condition_789 : BOOLEAN;
    signal ap_condition_792 : BOOLEAN;
    signal ap_condition_228 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_pooling2d_cl_array_ap_ufixed_4u_array_ap_ufixed_6_0_4_0_0_4u_config5_s_void_peOg IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (5 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (5 downto 0) );
    end component;


    component myproject_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_3_U : component myproject_pooling2d_cl_array_ap_ufixed_4u_array_ap_ufixed_6_0_4_0_0_4u_config5_s_void_peOg
    generic map (
        DataWidth => 6,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv3_7,
        ce0 => void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_3_ce0,
        we0 => void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_3_we0,
        d0 => trunc_ln115_fu_213_p1,
        q0 => void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_3_q0);

    void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_2_U : component myproject_pooling2d_cl_array_ap_ufixed_4u_array_ap_ufixed_6_0_4_0_0_4u_config5_s_void_peOg
    generic map (
        DataWidth => 6,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv3_7,
        ce0 => void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_2_ce0,
        we0 => void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_2_we0,
        d0 => void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_2_d0,
        q0 => void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_2_q0);

    void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_1_U : component myproject_pooling2d_cl_array_ap_ufixed_4u_array_ap_ufixed_6_0_4_0_0_4u_config5_s_void_peOg
    generic map (
        DataWidth => 6,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv3_7,
        ce0 => void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_1_ce0,
        we0 => void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_1_we0,
        d0 => void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_1_d0,
        q0 => void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_1_q0);

    void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_U : component myproject_pooling2d_cl_array_ap_ufixed_4u_array_ap_ufixed_6_0_4_0_0_4u_config5_s_void_peOg
    generic map (
        DataWidth => 6,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv3_7,
        ce0 => void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_ce0,
        we0 => void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_we0,
        d0 => void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_d0,
        q0 => void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_q0);

    flow_control_loop_pipe_U : component myproject_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => real_start,
        ap_ready => internal_ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter2_storemerge_reg_127_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_296)) then
                if ((ap_const_boolean_1 = ap_condition_298)) then 
                    ap_phi_reg_pp0_iter2_storemerge_reg_127 <= ap_const_lv32_0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_storemerge_reg_127 <= ap_phi_reg_pp0_iter1_storemerge_reg_127;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_354)) then
                if ((icmp_ln109_fu_156_p2 = ap_const_lv1_0)) then 
                    indvar_flatten_fu_110 <= add_ln109_fu_162_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_110 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;

    pX_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_233)) then
                if ((icmp_ln76_reg_918 = ap_const_lv1_1)) then 
                    pX_1 <= ap_const_lv32_0;
                elsif ((icmp_ln76_reg_918 = ap_const_lv1_0)) then 
                    pX_1 <= add_ln76_reg_897;
                end if;
            end if; 
        end if;
    end process;

    pY_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_789)) then
                if ((icmp_ln80_reg_981 = ap_const_lv1_1)) then 
                    pY_1 <= ap_const_lv32_0;
                elsif ((icmp_ln80_reg_981 = ap_const_lv1_0)) then 
                    pY_1 <= add_ln80_reg_922;
                end if;
            end if; 
        end if;
    end process;

    sX_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then
                if ((ap_const_boolean_1 = ap_condition_228)) then 
                    sX_1 <= ap_const_lv32_0;
                elsif ((ap_const_boolean_1 = ap_condition_792)) then 
                    sX_1 <= add_ln91_reg_976;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln109_fu_156_p2 = ap_const_lv1_0))) then
                add_ln76_reg_897 <= add_ln76_fu_172_p2;
                pX_1_load_reg_892 <= ap_sig_allocacmp_pX_1_load;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln109_reg_888 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln76_fu_198_p2 = ap_const_lv1_1))) then
                add_ln80_reg_922 <= add_ln80_fu_207_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln80_reg_981 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln76_reg_918 = ap_const_lv1_1) and (icmp_ln109_reg_888_pp0_iter1_reg = ap_const_lv1_0))) then
                add_ln86_reg_1047 <= add_ln86_fu_711_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln76_reg_918 = ap_const_lv1_0))) then
                add_ln91_reg_976 <= add_ln91_fu_299_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln55_reg_908 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                and_ln55_2_reg_995 <= and_ln55_2_fu_408_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                icmp_ln55_reg_908_pp0_iter1_reg <= icmp_ln55_reg_908;
                icmp_ln76_reg_918_pp0_iter1_reg <= icmp_ln76_reg_918;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                ap_phi_reg_pp0_iter1_storemerge_reg_127 <= ap_phi_reg_pp0_iter0_storemerge_reg_127;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln109_reg_888 <= icmp_ln109_fu_156_p2;
                icmp_ln109_reg_888_pp0_iter1_reg <= icmp_ln109_reg_888;
                p_0_reg_970 <= void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_q0;
                p_1_reg_952 <= void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_3_q0;
                p_2_reg_958 <= void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_2_q0;
                p_s_reg_964 <= void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_1_q0;
                trunc_ln115_4_reg_946 <= layer4_out_dout(11 downto 6);
                trunc_ln115_9_reg_934 <= layer4_out_dout(17 downto 12);
                trunc_ln115_reg_928 <= trunc_ln115_fu_213_p1;
                trunc_ln115_s_reg_940 <= layer4_out_dout(23 downto 18);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln109_reg_888 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln55_fu_187_p2 = ap_const_lv1_1))) then
                icmp_ln55_6_reg_913 <= icmp_ln55_6_fu_193_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln109_reg_888 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                icmp_ln55_reg_908 <= icmp_ln55_fu_187_p2;
                icmp_ln76_reg_918 <= icmp_ln76_fu_198_p2;
                sX_1_load_reg_903 <= ap_sig_allocacmp_sX_1_load;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln76_reg_918 = ap_const_lv1_1))) then
                icmp_ln80_reg_981 <= icmp_ln80_fu_316_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln109_reg_888 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln80_fu_316_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln76_reg_918 = ap_const_lv1_1))) then
                icmp_ln86_reg_990 <= grp_fu_142_p2;
                sY_1_load_1_reg_985 <= grp_load_fu_138_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln55_2_reg_995) and (icmp_ln55_reg_908_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                p_Val2_115_reg_1057 <= p_Val2_115_fu_786_p3;
                p_Val2_116_reg_1062 <= p_Val2_116_fu_822_p3;
                p_Val2_117_reg_1067 <= p_Val2_117_fu_858_p3;
                p_Val2_s_reg_1052 <= p_Val2_s_fu_750_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_14 <= trunc_ln115_s_reg_940;
                p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_15 <= trunc_ln115_9_reg_934;
                p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_16 <= trunc_ln115_4_reg_946;
                p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_17 <= trunc_ln115_reg_928;
                void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2 <= p_0_reg_970;
                void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3 <= p_s_reg_964;
                void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4 <= p_2_reg_958;
                void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5 <= p_1_reg_952;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln76_reg_918_pp0_iter1_reg = ap_const_lv1_1))) then
                sY_1 <= ap_phi_mux_storemerge_phi_fu_131_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_lv1_1 = and_ln55_2_fu_408_p2) and (icmp_ln55_reg_908 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                    select_ln66_32_reg_1005(10 downto 5) <= select_ln66_32_fu_476_p3(10 downto 5);
                    select_ln66_34_reg_1011(10 downto 5) <= select_ln66_34_fu_526_p3(10 downto 5);
                    select_ln66_35_reg_1017(10 downto 5) <= select_ln66_35_fu_546_p3(10 downto 5);
                    select_ln66_37_reg_1023(10 downto 5) <= select_ln66_37_fu_596_p3(10 downto 5);
                    select_ln66_38_reg_1029(10 downto 5) <= select_ln66_38_fu_616_p3(10 downto 5);
                    select_ln66_40_reg_1035(10 downto 5) <= select_ln66_40_fu_666_p3(10 downto 5);
                    select_ln66_41_reg_1041(10 downto 5) <= select_ln66_41_fu_686_p3(10 downto 5);
                    select_ln66_reg_999(10 downto 5) <= select_ln66_fu_456_p3(10 downto 5);
            end if;
        end if;
    end process;
    select_ln66_reg_999(4 downto 0) <= "00000";
    select_ln66_32_reg_1005(4 downto 0) <= "00000";
    select_ln66_34_reg_1011(4 downto 0) <= "00000";
    select_ln66_35_reg_1017(4 downto 0) <= "00000";
    select_ln66_37_reg_1023(4 downto 0) <= "00000";
    select_ln66_38_reg_1029(4 downto 0) <= "00000";
    select_ln66_40_reg_1035(4 downto 0) <= "00000";
    select_ln66_41_reg_1041(4 downto 0) <= "00000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to2, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to2 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln109_fu_162_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv7_1));
    add_ln76_fu_172_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_pX_1_load) + unsigned(ap_const_lv32_1));
    add_ln80_fu_207_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_pY_1_load_1) + unsigned(ap_const_lv32_1));
    add_ln86_fu_711_p2 <= std_logic_vector(unsigned(sY_1_load_1_reg_985) + unsigned(select_ln86_fu_704_p3));
    add_ln91_fu_299_p2 <= std_logic_vector(unsigned(sX_1_load_reg_903) + unsigned(select_ln91_fu_292_p3));
    and_ln55_2_fu_408_p2 <= (grp_fu_142_p2 and and_ln55_fu_403_p2);
    and_ln55_fu_403_p2 <= (icmp_ln55_6_reg_913 and icmp_ln55_5_fu_397_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, layer4_out_empty_n, ap_done_reg)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_done_reg = ap_const_logic_1)) or ((layer4_out_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, layer4_out_empty_n, ap_done_reg)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_done_reg = ap_const_logic_1)) or ((layer4_out_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_01001_assign_proc : process(ap_enable_reg_pp0_iter2, layer5_out_full_n, ap_predicate_op147_write_state6)
    begin
                ap_block_pp0_stage1_01001 <= ((ap_predicate_op147_write_state6 = ap_const_boolean_1) and (layer5_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage1_11001_assign_proc : process(ap_enable_reg_pp0_iter2, layer5_out_full_n, ap_predicate_op147_write_state6)
    begin
                ap_block_pp0_stage1_11001 <= ((ap_predicate_op147_write_state6 = ap_const_boolean_1) and (layer5_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, layer5_out_full_n, ap_predicate_op147_write_state6)
    begin
                ap_block_pp0_stage1_subdone <= ((ap_predicate_op147_write_state6 = ap_const_boolean_1) and (layer5_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_done_reg = ap_const_logic_1);
    end process;

        ap_block_state2_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_pp0_stage0_iter1_assign_proc : process(layer4_out_empty_n)
    begin
                ap_block_state3_pp0_stage0_iter1 <= (layer4_out_empty_n = ap_const_logic_0);
    end process;

        ap_block_state4_pp0_stage1_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state6_pp0_stage1_iter2_assign_proc : process(layer5_out_full_n, ap_predicate_op147_write_state6)
    begin
                ap_block_state6_pp0_stage1_iter2 <= ((ap_predicate_op147_write_state6 = ap_const_boolean_1) and (layer5_out_full_n = ap_const_logic_0));
    end process;


    ap_condition_146_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
                ap_condition_146 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_228_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln76_reg_918)
    begin
                ap_condition_228 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln76_reg_918 = ap_const_lv1_1));
    end process;


    ap_condition_233_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
                ap_condition_233 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_296_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
                ap_condition_296 <= ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1));
    end process;


    ap_condition_298_assign_proc : process(icmp_ln109_reg_888_pp0_iter1_reg, icmp_ln76_reg_918, icmp_ln80_reg_981)
    begin
                ap_condition_298 <= ((icmp_ln80_reg_981 = ap_const_lv1_1) and (icmp_ln76_reg_918 = ap_const_lv1_1) and (icmp_ln109_reg_888_pp0_iter1_reg = ap_const_lv1_0));
    end process;


    ap_condition_354_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_354 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_771_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, icmp_ln109_reg_888_pp0_iter1_reg, icmp_ln76_reg_918)
    begin
                ap_condition_771 <= ((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln76_reg_918 = ap_const_lv1_1) and (icmp_ln109_reg_888_pp0_iter1_reg = ap_const_lv1_0));
    end process;


    ap_condition_777_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln109_reg_888, ap_block_pp0_stage0, icmp_ln76_reg_918, icmp_ln80_fu_316_p2)
    begin
                ap_condition_777 <= ((icmp_ln109_reg_888 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln80_fu_316_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln76_reg_918 = ap_const_lv1_1));
    end process;


    ap_condition_781_assign_proc : process(ap_CS_fsm_pp0_stage1, icmp_ln55_reg_908, ap_block_pp0_stage1)
    begin
                ap_condition_781 <= ((ap_const_boolean_0 = ap_block_pp0_stage1) and (icmp_ln55_reg_908 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1));
    end process;


    ap_condition_789_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, icmp_ln109_reg_888_pp0_iter1_reg, ap_block_pp0_stage1_11001, icmp_ln76_reg_918)
    begin
                ap_condition_789 <= ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln76_reg_918 = ap_const_lv1_1) and (icmp_ln109_reg_888_pp0_iter1_reg = ap_const_lv1_0));
    end process;


    ap_condition_792_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, icmp_ln76_reg_918)
    begin
                ap_condition_792 <= ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln76_reg_918 = ap_const_lv1_0));
    end process;


    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, icmp_ln109_reg_888)
    begin
        if (((icmp_ln109_reg_888 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to2_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to2 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to2 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;

    ap_phi_mux_storemerge_phi_fu_131_p4_assign_proc : process(icmp_ln109_reg_888_pp0_iter1_reg, icmp_ln76_reg_918_pp0_iter1_reg, icmp_ln80_reg_981, add_ln86_reg_1047, ap_phi_reg_pp0_iter2_storemerge_reg_127)
    begin
        if (((icmp_ln80_reg_981 = ap_const_lv1_0) and (icmp_ln76_reg_918_pp0_iter1_reg = ap_const_lv1_1) and (icmp_ln109_reg_888_pp0_iter1_reg = ap_const_lv1_0))) then 
            ap_phi_mux_storemerge_phi_fu_131_p4 <= add_ln86_reg_1047;
        else 
            ap_phi_mux_storemerge_phi_fu_131_p4 <= ap_phi_reg_pp0_iter2_storemerge_reg_127;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_storemerge_reg_127 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_predicate_op147_write_state6_assign_proc : process(icmp_ln55_reg_908_pp0_iter1_reg, and_ln55_2_reg_995)
    begin
                ap_predicate_op147_write_state6 <= ((ap_const_lv1_1 = and_ln55_2_reg_995) and (icmp_ln55_reg_908_pp0_iter1_reg = ap_const_lv1_1));
    end process;

    ap_ready <= internal_ap_ready;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, indvar_flatten_fu_110, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_110;
        end if; 
    end process;


    ap_sig_allocacmp_pX_1_load_assign_proc : process(pX_1, add_ln76_reg_897, icmp_ln76_reg_918, ap_condition_146)
    begin
        if ((ap_const_boolean_1 = ap_condition_146)) then
            if ((icmp_ln76_reg_918 = ap_const_lv1_1)) then 
                ap_sig_allocacmp_pX_1_load <= ap_const_lv32_0;
            elsif ((icmp_ln76_reg_918 = ap_const_lv1_0)) then 
                ap_sig_allocacmp_pX_1_load <= add_ln76_reg_897;
            else 
                ap_sig_allocacmp_pX_1_load <= pX_1;
            end if;
        else 
            ap_sig_allocacmp_pX_1_load <= pX_1;
        end if; 
    end process;


    ap_sig_allocacmp_pY_1_load_1_assign_proc : process(pY_1, add_ln80_reg_922, icmp_ln80_reg_981, ap_condition_771)
    begin
        if ((ap_const_boolean_1 = ap_condition_771)) then
            if ((icmp_ln80_reg_981 = ap_const_lv1_1)) then 
                ap_sig_allocacmp_pY_1_load_1 <= ap_const_lv32_0;
            elsif ((icmp_ln80_reg_981 = ap_const_lv1_0)) then 
                ap_sig_allocacmp_pY_1_load_1 <= add_ln80_reg_922;
            else 
                ap_sig_allocacmp_pY_1_load_1 <= pY_1;
            end if;
        else 
            ap_sig_allocacmp_pY_1_load_1 <= pY_1;
        end if; 
    end process;


    ap_sig_allocacmp_sX_1_load_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, sX_1, ap_block_pp0_stage1, icmp_ln76_reg_918, add_ln91_reg_976)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln76_reg_918 = ap_const_lv1_0))) then 
            ap_sig_allocacmp_sX_1_load <= add_ln91_reg_976;
        else 
            ap_sig_allocacmp_sX_1_load <= sX_1;
        end if; 
    end process;


    ap_sig_allocacmp_sY_1_load_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, sY_1, ap_block_pp0_stage0, icmp_ln76_reg_918_pp0_iter1_reg, ap_phi_mux_storemerge_phi_fu_131_p4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln76_reg_918_pp0_iter1_reg = ap_const_lv1_1))) then 
            ap_sig_allocacmp_sY_1_load_1 <= ap_phi_mux_storemerge_phi_fu_131_p4;
        else 
            ap_sig_allocacmp_sY_1_load_1 <= sY_1;
        end if; 
    end process;

    grp_fu_142_p2 <= "1" when (grp_load_fu_138_p1 = ap_const_lv32_1) else "0";

    grp_load_fu_138_p1_assign_proc : process(ap_enable_reg_pp0_iter1, sY_1, ap_sig_allocacmp_sY_1_load_1, ap_condition_777, ap_condition_781)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then
            if ((ap_const_boolean_1 = ap_condition_781)) then 
                grp_load_fu_138_p1 <= sY_1;
            elsif ((ap_const_boolean_1 = ap_condition_777)) then 
                grp_load_fu_138_p1 <= ap_sig_allocacmp_sY_1_load_1;
            else 
                grp_load_fu_138_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_load_fu_138_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    icmp_ln109_fu_156_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv7_40) else "0";
    icmp_ln1651_32_fu_464_p2 <= "1" when (unsigned(pool_window_V_33_fu_429_p3) < unsigned(pool_window_V_34_fu_437_p3)) else "0";
    icmp_ln1651_33_fu_722_p2 <= "1" when (unsigned(select_ln66_reg_999) < unsigned(select_ln66_32_reg_1005)) else "0";
    icmp_ln1651_34_fu_514_p2 <= "1" when (unsigned(pool_window_V_35_fu_484_p3) < unsigned(pool_window_V_36_fu_492_p3)) else "0";
    icmp_ln1651_35_fu_534_p2 <= "1" when (unsigned(pool_window_V_37_fu_499_p3) < unsigned(pool_window_V_38_fu_507_p3)) else "0";
    icmp_ln1651_36_fu_758_p2 <= "1" when (unsigned(select_ln66_34_reg_1011) < unsigned(select_ln66_35_reg_1017)) else "0";
    icmp_ln1651_37_fu_584_p2 <= "1" when (unsigned(pool_window_V_39_fu_554_p3) < unsigned(pool_window_V_40_fu_562_p3)) else "0";
    icmp_ln1651_38_fu_604_p2 <= "1" when (unsigned(pool_window_V_41_fu_569_p3) < unsigned(pool_window_V_42_fu_577_p3)) else "0";
    icmp_ln1651_39_fu_794_p2 <= "1" when (unsigned(select_ln66_37_reg_1023) < unsigned(select_ln66_38_reg_1029)) else "0";
    icmp_ln1651_40_fu_654_p2 <= "1" when (unsigned(pool_window_V_43_fu_624_p3) < unsigned(pool_window_V_44_fu_632_p3)) else "0";
    icmp_ln1651_41_fu_674_p2 <= "1" when (unsigned(pool_window_V_45_fu_639_p3) < unsigned(pool_window_V_46_fu_647_p3)) else "0";
    icmp_ln1651_42_fu_830_p2 <= "1" when (unsigned(select_ln66_40_reg_1035) < unsigned(select_ln66_41_reg_1041)) else "0";
    icmp_ln1651_fu_444_p2 <= "1" when (unsigned(pool_window_V_fu_414_p3) < unsigned(pool_window_V_32_fu_422_p3)) else "0";
    icmp_ln55_5_fu_397_p2 <= "1" when (signed(pY_1) > signed(ap_const_lv32_0)) else "0";
    icmp_ln55_6_fu_193_p2 <= "1" when (signed(pX_1_load_reg_892) > signed(ap_const_lv32_0)) else "0";
    icmp_ln55_fu_187_p2 <= "1" when (ap_sig_allocacmp_sX_1_load = ap_const_lv32_1) else "0";
    icmp_ln76_fu_198_p2 <= "1" when (add_ln76_reg_897 = ap_const_lv32_8) else "0";
    icmp_ln80_fu_316_p2 <= "1" when (add_ln80_reg_922 = ap_const_lv32_8) else "0";

    layer4_out_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, layer4_out_empty_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer4_out_blk_n <= layer4_out_empty_n;
        else 
            layer4_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer4_out_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer4_out_read <= ap_const_logic_1;
        else 
            layer4_out_read <= ap_const_logic_0;
        end if; 
    end process;


    layer5_out_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, layer5_out_full_n, ap_predicate_op147_write_state6, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_predicate_op147_write_state6 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            layer5_out_blk_n <= layer5_out_full_n;
        else 
            layer5_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer5_out_din <= (((p_Val2_117_reg_1067 & p_Val2_116_reg_1062) & p_Val2_115_reg_1057) & p_Val2_s_reg_1052);

    layer5_out_write_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_predicate_op147_write_state6, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_predicate_op147_write_state6 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            layer5_out_write <= ap_const_logic_1;
        else 
            layer5_out_write <= ap_const_logic_0;
        end if; 
    end process;

    p_Val2_115_fu_786_p3 <= 
        tmp_27_fu_768_p4 when (xor_ln1651_36_fu_762_p2(0) = '1') else 
        tmp_28_fu_777_p4;
    p_Val2_116_fu_822_p3 <= 
        tmp_30_fu_804_p4 when (xor_ln1651_39_fu_798_p2(0) = '1') else 
        tmp_31_fu_813_p4;
    p_Val2_117_fu_858_p3 <= 
        tmp_33_fu_840_p4 when (xor_ln1651_42_fu_834_p2(0) = '1') else 
        tmp_34_fu_849_p4;
    p_Val2_s_fu_750_p3 <= 
        tmp_24_fu_732_p4 when (xor_ln1651_33_fu_726_p2(0) = '1') else 
        tmp_25_fu_741_p4;
    pool_window_V_32_fu_422_p3 <= (p_1_reg_952 & ap_const_lv5_0);
    pool_window_V_33_fu_429_p3 <= (p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_17 & ap_const_lv5_0);
    pool_window_V_34_fu_437_p3 <= (trunc_ln115_reg_928 & ap_const_lv5_0);
    pool_window_V_35_fu_484_p3 <= (void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4 & ap_const_lv5_0);
    pool_window_V_36_fu_492_p3 <= (p_2_reg_958 & ap_const_lv5_0);
    pool_window_V_37_fu_499_p3 <= (p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_16 & ap_const_lv5_0);
    pool_window_V_38_fu_507_p3 <= (trunc_ln115_4_reg_946 & ap_const_lv5_0);
    pool_window_V_39_fu_554_p3 <= (void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3 & ap_const_lv5_0);
    pool_window_V_40_fu_562_p3 <= (p_s_reg_964 & ap_const_lv5_0);
    pool_window_V_41_fu_569_p3 <= (p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_15 & ap_const_lv5_0);
    pool_window_V_42_fu_577_p3 <= (trunc_ln115_9_reg_934 & ap_const_lv5_0);
    pool_window_V_43_fu_624_p3 <= (void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2 & ap_const_lv5_0);
    pool_window_V_44_fu_632_p3 <= (p_0_reg_970 & ap_const_lv5_0);
    pool_window_V_45_fu_639_p3 <= (p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_14 & ap_const_lv5_0);
    pool_window_V_46_fu_647_p3 <= (trunc_ln115_s_reg_940 & ap_const_lv5_0);
    pool_window_V_fu_414_p3 <= (void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5 & ap_const_lv5_0);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    select_ln66_32_fu_476_p3 <= 
        pool_window_V_33_fu_429_p3 when (xor_ln1651_32_fu_470_p2(0) = '1') else 
        pool_window_V_34_fu_437_p3;
    select_ln66_34_fu_526_p3 <= 
        pool_window_V_35_fu_484_p3 when (xor_ln1651_34_fu_520_p2(0) = '1') else 
        pool_window_V_36_fu_492_p3;
    select_ln66_35_fu_546_p3 <= 
        pool_window_V_37_fu_499_p3 when (xor_ln1651_35_fu_540_p2(0) = '1') else 
        pool_window_V_38_fu_507_p3;
    select_ln66_37_fu_596_p3 <= 
        pool_window_V_39_fu_554_p3 when (xor_ln1651_37_fu_590_p2(0) = '1') else 
        pool_window_V_40_fu_562_p3;
    select_ln66_38_fu_616_p3 <= 
        pool_window_V_41_fu_569_p3 when (xor_ln1651_38_fu_610_p2(0) = '1') else 
        pool_window_V_42_fu_577_p3;
    select_ln66_40_fu_666_p3 <= 
        pool_window_V_43_fu_624_p3 when (xor_ln1651_40_fu_660_p2(0) = '1') else 
        pool_window_V_44_fu_632_p3;
    select_ln66_41_fu_686_p3 <= 
        pool_window_V_45_fu_639_p3 when (xor_ln1651_41_fu_680_p2(0) = '1') else 
        pool_window_V_46_fu_647_p3;
    select_ln66_fu_456_p3 <= 
        pool_window_V_fu_414_p3 when (xor_ln1651_fu_450_p2(0) = '1') else 
        pool_window_V_32_fu_422_p3;
    select_ln86_fu_704_p3 <= 
        ap_const_lv32_FFFFFFFF when (icmp_ln86_reg_990(0) = '1') else 
        ap_const_lv32_1;
    select_ln91_fu_292_p3 <= 
        ap_const_lv32_FFFFFFFF when (icmp_ln55_reg_908(0) = '1') else 
        ap_const_lv32_1;
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp_24_fu_732_p4 <= select_ln66_reg_999(10 downto 5);
    tmp_25_fu_741_p4 <= select_ln66_32_reg_1005(10 downto 5);
    tmp_27_fu_768_p4 <= select_ln66_34_reg_1011(10 downto 5);
    tmp_28_fu_777_p4 <= select_ln66_35_reg_1017(10 downto 5);
    tmp_30_fu_804_p4 <= select_ln66_37_reg_1023(10 downto 5);
    tmp_31_fu_813_p4 <= select_ln66_38_reg_1029(10 downto 5);
    tmp_33_fu_840_p4 <= select_ln66_40_reg_1035(10 downto 5);
    tmp_34_fu_849_p4 <= select_ln66_41_reg_1041(10 downto 5);
    trunc_ln115_fu_213_p1 <= layer4_out_dout(6 - 1 downto 0);

    void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_1_ce0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_1_d0 <= layer4_out_dout(17 downto 12);

    void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_1_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_1_we0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_2_ce0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_2_d0 <= layer4_out_dout(11 downto 6);

    void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_2_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_2_we0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_3_ce0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_3_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_3_we0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_ce0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_d0 <= layer4_out_dout(23 downto 18);

    void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_we0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_ufixed_4u_0_line_buffer_we0 <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln1651_32_fu_470_p2 <= (icmp_ln1651_32_fu_464_p2 xor ap_const_lv1_1);
    xor_ln1651_33_fu_726_p2 <= (icmp_ln1651_33_fu_722_p2 xor ap_const_lv1_1);
    xor_ln1651_34_fu_520_p2 <= (icmp_ln1651_34_fu_514_p2 xor ap_const_lv1_1);
    xor_ln1651_35_fu_540_p2 <= (icmp_ln1651_35_fu_534_p2 xor ap_const_lv1_1);
    xor_ln1651_36_fu_762_p2 <= (icmp_ln1651_36_fu_758_p2 xor ap_const_lv1_1);
    xor_ln1651_37_fu_590_p2 <= (icmp_ln1651_37_fu_584_p2 xor ap_const_lv1_1);
    xor_ln1651_38_fu_610_p2 <= (icmp_ln1651_38_fu_604_p2 xor ap_const_lv1_1);
    xor_ln1651_39_fu_798_p2 <= (icmp_ln1651_39_fu_794_p2 xor ap_const_lv1_1);
    xor_ln1651_40_fu_660_p2 <= (icmp_ln1651_40_fu_654_p2 xor ap_const_lv1_1);
    xor_ln1651_41_fu_680_p2 <= (icmp_ln1651_41_fu_674_p2 xor ap_const_lv1_1);
    xor_ln1651_42_fu_834_p2 <= (icmp_ln1651_42_fu_830_p2 xor ap_const_lv1_1);
    xor_ln1651_fu_450_p2 <= (icmp_ln1651_fu_444_p2 xor ap_const_lv1_1);
end behav;
