<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="17">
<syndb class_id="0" tracking_level="0" version="0">
	<userIPLatency>-1</userIPLatency>
	<userIPName></userIPName>
	<cdfg class_id="1" tracking_level="1" version="0" object_id="_0">
		<name>conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_19_8_5_3_0_8u_config6_s</name>
		<module_structure>Sequential</module_structure>
		<ret_bitwidth>0</ret_bitwidth>
		<ports class_id="2" tracking_level="0" version="0">
			<count>2</count>
			<item_version>0</item_version>
			<item class_id="3" tracking_level="1" version="0" object_id="_1">
				<Value class_id="4" tracking_level="0" version="0">
					<Obj class_id="5" tracking_level="0" version="0">
						<type>1</type>
						<id>1</id>
						<name>layer19_out</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo class_id="6" tracking_level="0" version="0">
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>1868525665</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>24</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>3</if_type>
				<array_size>0</array_size>
				<bit_vecs class_id="7" tracking_level="0" version="0">
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_2">
				<Value>
					<Obj>
						<type>1</type>
						<id>2</id>
						<name>layer6_out</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>1868525665</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>152</bitwidth>
				</Value>
				<direction>1</direction>
				<if_type>3</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
		</ports>
		<nodes class_id="8" tracking_level="0" version="0">
			<count>16</count>
			<item_version>0</item_version>
			<item class_id="9" tracking_level="1" version="0" object_id="_3">
				<Value>
					<Obj>
						<type>0</type>
						<id>52</id>
						<name>indvar_flatten</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>539766825</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>6</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>78</item>
				</oprand_edges>
				<opcode>alloca</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>1</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_4">
				<Value>
					<Obj>
						<type>0</type>
						<id>55</id>
						<name>indvar_flatten_write_ln51</name>
						<fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
						<fileDirectory>/home/yvan/Bureau/Projekt/PA2/MNIST/model_personDetection/hls4ml_prj_qat</fileDirectory>
						<lineNumber>51</lineNumber>
						<contextFuncName>conv_2d_buffer_resource_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;6, 0, AP_RND_CONV, AP_SAT, 0&amp;gt;, 4&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;19, 8, AP_TRN, AP_WRAP, 0&amp;gt;, 8&amp;gt;, config6&amp;gt;</contextFuncName>
						<contextNormFuncName>conv_2d_buffer_resource_cl_nnet_array_ap_ufixed_6_0_AP_RND_CONV_AP_SAT_0_4_nnet_array_ap_fixed_19_8_AP_TRN_AP_WRAP_0_8_config6_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item class_id="11" tracking_level="0" version="0">
								<first>/home/yvan/Bureau/Projekt/PA2/MNIST/model_personDetection/hls4ml_prj_qat</first>
								<second class_id="12" tracking_level="0" version="0">
									<count>1</count>
									<item_version>0</item_version>
									<item class_id="13" tracking_level="0" version="0">
										<first class_id="14" tracking_level="0" version="0">
											<first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
											<second>conv_2d_buffer_resource_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;6, 0, AP_RND_CONV, AP_SAT, 0&amp;gt;, 4&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;19, 8, AP_TRN, AP_WRAP, 0&amp;gt;, 8&amp;gt;, config6&amp;gt;</second>
										</first>
										<second>51</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>539767593</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>80</item>
					<item>81</item>
				</oprand_edges>
				<opcode>store</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>1.58</m_delay>
				<m_topoIndex>2</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_5">
				<Value>
					<Obj>
						<type>0</type>
						<id>56</id>
						<name>br_ln51</name>
						<fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
						<fileDirectory>/home/yvan/Bureau/Projekt/PA2/MNIST/model_personDetection/hls4ml_prj_qat</fileDirectory>
						<lineNumber>51</lineNumber>
						<contextFuncName>conv_2d_buffer_resource_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;6, 0, AP_RND_CONV, AP_SAT, 0&amp;gt;, 4&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;19, 8, AP_TRN, AP_WRAP, 0&amp;gt;, 8&amp;gt;, config6&amp;gt;</contextFuncName>
						<contextNormFuncName>conv_2d_buffer_resource_cl_nnet_array_ap_ufixed_6_0_AP_RND_CONV_AP_SAT_0_4_nnet_array_ap_fixed_19_8_AP_TRN_AP_WRAP_0_8_config6_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/yvan/Bureau/Projekt/PA2/MNIST/model_personDetection/hls4ml_prj_qat</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
											<second>conv_2d_buffer_resource_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;6, 0, AP_RND_CONV, AP_SAT, 0&amp;gt;, 4&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;19, 8, AP_TRN, AP_WRAP, 0&amp;gt;, 8&amp;gt;, config6&amp;gt;</second>
										</first>
										<second>51</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>539767593</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>82</item>
				</oprand_edges>
				<opcode>br</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>3</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_6">
				<Value>
					<Obj>
						<type>0</type>
						<id>58</id>
						<name>indvar_flatten_load</name>
						<fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
						<fileDirectory>/home/yvan/Bureau/Projekt/PA2/MNIST/model_personDetection/hls4ml_prj_qat</fileDirectory>
						<lineNumber>51</lineNumber>
						<contextFuncName>conv_2d_buffer_resource_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;6, 0, AP_RND_CONV, AP_SAT, 0&amp;gt;, 4&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;19, 8, AP_TRN, AP_WRAP, 0&amp;gt;, 8&amp;gt;, config6&amp;gt;</contextFuncName>
						<contextNormFuncName>conv_2d_buffer_resource_cl_nnet_array_ap_ufixed_6_0_AP_RND_CONV_AP_SAT_0_4_nnet_array_ap_fixed_19_8_AP_TRN_AP_WRAP_0_8_config6_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/yvan/Bureau/Projekt/PA2/MNIST/model_personDetection/hls4ml_prj_qat</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
											<second>conv_2d_buffer_resource_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;6, 0, AP_RND_CONV, AP_SAT, 0&amp;gt;, 4&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;19, 8, AP_TRN, AP_WRAP, 0&amp;gt;, 8&amp;gt;, config6&amp;gt;</second>
										</first>
										<second>51</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>539767593</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>6</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>83</item>
					<item>235</item>
				</oprand_edges>
				<opcode>load</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>4</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_7">
				<Value>
					<Obj>
						<type>0</type>
						<id>59</id>
						<name>icmp_ln51</name>
						<fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
						<fileDirectory>/home/yvan/Bureau/Projekt/PA2/MNIST/model_personDetection/hls4ml_prj_qat</fileDirectory>
						<lineNumber>51</lineNumber>
						<contextFuncName>conv_2d_buffer_resource_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;6, 0, AP_RND_CONV, AP_SAT, 0&amp;gt;, 4&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;19, 8, AP_TRN, AP_WRAP, 0&amp;gt;, 8&amp;gt;, config6&amp;gt;</contextFuncName>
						<contextNormFuncName>conv_2d_buffer_resource_cl_nnet_array_ap_ufixed_6_0_AP_RND_CONV_AP_SAT_0_4_nnet_array_ap_fixed_19_8_AP_TRN_AP_WRAP_0_8_config6_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/yvan/Bureau/Projekt/PA2/MNIST/model_personDetection/hls4ml_prj_qat</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
											<second>conv_2d_buffer_resource_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;6, 0, AP_RND_CONV, AP_SAT, 0&amp;gt;, 4&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;19, 8, AP_TRN, AP_WRAP, 0&amp;gt;, 8&amp;gt;, config6&amp;gt;</second>
										</first>
										<second>51</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>539767593</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>1</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>84</item>
					<item>86</item>
				</oprand_edges>
				<opcode>icmp</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>1.42</m_delay>
				<m_topoIndex>5</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_8">
				<Value>
					<Obj>
						<type>0</type>
						<id>60</id>
						<name>add_ln51</name>
						<fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
						<fileDirectory>/home/yvan/Bureau/Projekt/PA2/MNIST/model_personDetection/hls4ml_prj_qat</fileDirectory>
						<lineNumber>51</lineNumber>
						<contextFuncName>conv_2d_buffer_resource_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;6, 0, AP_RND_CONV, AP_SAT, 0&amp;gt;, 4&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;19, 8, AP_TRN, AP_WRAP, 0&amp;gt;, 8&amp;gt;, config6&amp;gt;</contextFuncName>
						<contextNormFuncName>conv_2d_buffer_resource_cl_nnet_array_ap_ufixed_6_0_AP_RND_CONV_AP_SAT_0_4_nnet_array_ap_fixed_19_8_AP_TRN_AP_WRAP_0_8_config6_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/yvan/Bureau/Projekt/PA2/MNIST/model_personDetection/hls4ml_prj_qat</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
											<second>conv_2d_buffer_resource_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;6, 0, AP_RND_CONV, AP_SAT, 0&amp;gt;, 4&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;19, 8, AP_TRN, AP_WRAP, 0&amp;gt;, 8&amp;gt;, config6&amp;gt;</second>
										</first>
										<second>51</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>1966092576</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>6</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>87</item>
					<item>89</item>
				</oprand_edges>
				<opcode>add</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>1.82</m_delay>
				<m_topoIndex>6</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_9">
				<Value>
					<Obj>
						<type>0</type>
						<id>61</id>
						<name>br_ln51</name>
						<fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
						<fileDirectory>/home/yvan/Bureau/Projekt/PA2/MNIST/model_personDetection/hls4ml_prj_qat</fileDirectory>
						<lineNumber>51</lineNumber>
						<contextFuncName>conv_2d_buffer_resource_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;6, 0, AP_RND_CONV, AP_SAT, 0&amp;gt;, 4&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;19, 8, AP_TRN, AP_WRAP, 0&amp;gt;, 8&amp;gt;, config6&amp;gt;</contextFuncName>
						<contextNormFuncName>conv_2d_buffer_resource_cl_nnet_array_ap_ufixed_6_0_AP_RND_CONV_AP_SAT_0_4_nnet_array_ap_fixed_19_8_AP_TRN_AP_WRAP_0_8_config6_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/yvan/Bureau/Projekt/PA2/MNIST/model_personDetection/hls4ml_prj_qat</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
											<second>conv_2d_buffer_resource_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;6, 0, AP_RND_CONV, AP_SAT, 0&amp;gt;, 4&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;19, 8, AP_TRN, AP_WRAP, 0&amp;gt;, 8&amp;gt;, config6&amp;gt;</second>
										</first>
										<second>51</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>1966092576</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>90</item>
					<item>91</item>
					<item>92</item>
				</oprand_edges>
				<opcode>br</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>7</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_10">
				<Value>
					<Obj>
						<type>0</type>
						<id>66</id>
						<name>layer19_out_read</name>
						<fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
						<fileDirectory>/home/yvan/Bureau/Projekt/PA2/MNIST/model_personDetection/hls4ml_prj_qat</fileDirectory>
						<lineNumber>57</lineNumber>
						<contextFuncName>conv_2d_buffer_resource_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;6, 0, AP_RND_CONV, AP_SAT, 0&amp;gt;, 4&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;19, 8, AP_TRN, AP_WRAP, 0&amp;gt;, 8&amp;gt;, config6&amp;gt;</contextFuncName>
						<contextNormFuncName>conv_2d_buffer_resource_cl_nnet_array_ap_ufixed_6_0_AP_RND_CONV_AP_SAT_0_4_nnet_array_ap_fixed_19_8_AP_TRN_AP_WRAP_0_8_config6_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/yvan/Bureau/Projekt/PA2/MNIST/model_personDetection/hls4ml_prj_qat</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
											<second>conv_2d_buffer_resource_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;6, 0, AP_RND_CONV, AP_SAT, 0&amp;gt;, 4&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;19, 8, AP_TRN, AP_WRAP, 0&amp;gt;, 8&amp;gt;, config6&amp;gt;</second>
										</first>
										<second>57</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>2974045408</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>24</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>94</item>
					<item>95</item>
				</oprand_edges>
				<opcode>read</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>1.82</m_delay>
				<m_topoIndex>8</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_11">
				<Value>
					<Obj>
						<type>0</type>
						<id>67</id>
						<name>trunc_ln57</name>
						<fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
						<fileDirectory>/home/yvan/Bureau/Projekt/PA2/MNIST/model_personDetection/hls4ml_prj_qat</fileDirectory>
						<lineNumber>57</lineNumber>
						<contextFuncName>conv_2d_buffer_resource_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;6, 0, AP_RND_CONV, AP_SAT, 0&amp;gt;, 4&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;19, 8, AP_TRN, AP_WRAP, 0&amp;gt;, 8&amp;gt;, config6&amp;gt;</contextFuncName>
						<contextNormFuncName>conv_2d_buffer_resource_cl_nnet_array_ap_ufixed_6_0_AP_RND_CONV_AP_SAT_0_4_nnet_array_ap_fixed_19_8_AP_TRN_AP_WRAP_0_8_config6_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/yvan/Bureau/Projekt/PA2/MNIST/model_personDetection/hls4ml_prj_qat</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
											<second>conv_2d_buffer_resource_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;6, 0, AP_RND_CONV, AP_SAT, 0&amp;gt;, 4&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;19, 8, AP_TRN, AP_WRAP, 0&amp;gt;, 8&amp;gt;, config6&amp;gt;</second>
										</first>
										<second>57</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>2971504112</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>6</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>96</item>
				</oprand_edges>
				<opcode>trunc</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>9</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_12">
				<Value>
					<Obj>
						<type>0</type>
						<id>68</id>
						<name>trunc_ln57_2</name>
						<fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
						<fileDirectory>/home/yvan/Bureau/Projekt/PA2/MNIST/model_personDetection/hls4ml_prj_qat</fileDirectory>
						<lineNumber>57</lineNumber>
						<contextFuncName>conv_2d_buffer_resource_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;6, 0, AP_RND_CONV, AP_SAT, 0&amp;gt;, 4&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;19, 8, AP_TRN, AP_WRAP, 0&amp;gt;, 8&amp;gt;, config6&amp;gt;</contextFuncName>
						<contextNormFuncName>conv_2d_buffer_resource_cl_nnet_array_ap_ufixed_6_0_AP_RND_CONV_AP_SAT_0_4_nnet_array_ap_fixed_19_8_AP_TRN_AP_WRAP_0_8_config6_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/yvan/Bureau/Projekt/PA2/MNIST/model_personDetection/hls4ml_prj_qat</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
											<second>conv_2d_buffer_resource_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;6, 0, AP_RND_CONV, AP_SAT, 0&amp;gt;, 4&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;19, 8, AP_TRN, AP_WRAP, 0&amp;gt;, 8&amp;gt;, config6&amp;gt;</second>
										</first>
										<second>57</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>2974209936</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>6</bitwidth>
				</Value>
				<oprand_edges>
					<count>4</count>
					<item_version>0</item_version>
					<item>98</item>
					<item>99</item>
					<item>101</item>
					<item>103</item>
				</oprand_edges>
				<opcode>partselect</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>10</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_13">
				<Value>
					<Obj>
						<type>0</type>
						<id>69</id>
						<name>trunc_ln57_3</name>
						<fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
						<fileDirectory>/home/yvan/Bureau/Projekt/PA2/MNIST/model_personDetection/hls4ml_prj_qat</fileDirectory>
						<lineNumber>57</lineNumber>
						<contextFuncName>conv_2d_buffer_resource_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;6, 0, AP_RND_CONV, AP_SAT, 0&amp;gt;, 4&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;19, 8, AP_TRN, AP_WRAP, 0&amp;gt;, 8&amp;gt;, config6&amp;gt;</contextFuncName>
						<contextNormFuncName>conv_2d_buffer_resource_cl_nnet_array_ap_ufixed_6_0_AP_RND_CONV_AP_SAT_0_4_nnet_array_ap_fixed_19_8_AP_TRN_AP_WRAP_0_8_config6_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/yvan/Bureau/Projekt/PA2/MNIST/model_personDetection/hls4ml_prj_qat</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
											<second>conv_2d_buffer_resource_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;6, 0, AP_RND_CONV, AP_SAT, 0&amp;gt;, 4&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;19, 8, AP_TRN, AP_WRAP, 0&amp;gt;, 8&amp;gt;, config6&amp;gt;</second>
										</first>
										<second>57</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>2974209936</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>6</bitwidth>
				</Value>
				<oprand_edges>
					<count>4</count>
					<item_version>0</item_version>
					<item>104</item>
					<item>105</item>
					<item>107</item>
					<item>109</item>
				</oprand_edges>
				<opcode>partselect</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>11</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_14">
				<Value>
					<Obj>
						<type>0</type>
						<id>70</id>
						<name>trunc_ln57_5</name>
						<fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
						<fileDirectory>/home/yvan/Bureau/Projekt/PA2/MNIST/model_personDetection/hls4ml_prj_qat</fileDirectory>
						<lineNumber>57</lineNumber>
						<contextFuncName>conv_2d_buffer_resource_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;6, 0, AP_RND_CONV, AP_SAT, 0&amp;gt;, 4&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;19, 8, AP_TRN, AP_WRAP, 0&amp;gt;, 8&amp;gt;, config6&amp;gt;</contextFuncName>
						<contextNormFuncName>conv_2d_buffer_resource_cl_nnet_array_ap_ufixed_6_0_AP_RND_CONV_AP_SAT_0_4_nnet_array_ap_fixed_19_8_AP_TRN_AP_WRAP_0_8_config6_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/yvan/Bureau/Projekt/PA2/MNIST/model_personDetection/hls4ml_prj_qat</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
											<second>conv_2d_buffer_resource_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;6, 0, AP_RND_CONV, AP_SAT, 0&amp;gt;, 4&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;19, 8, AP_TRN, AP_WRAP, 0&amp;gt;, 8&amp;gt;, config6&amp;gt;</second>
										</first>
										<second>57</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>2974209936</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>6</bitwidth>
				</Value>
				<oprand_edges>
					<count>4</count>
					<item_version>0</item_version>
					<item>110</item>
					<item>111</item>
					<item>113</item>
					<item>115</item>
				</oprand_edges>
				<opcode>partselect</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>12</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_15">
				<Value>
					<Obj>
						<type>0</type>
						<id>71</id>
						<name>_ln57</name>
						<fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
						<fileDirectory>/home/yvan/Bureau/Projekt/PA2/MNIST/model_personDetection/hls4ml_prj_qat</fileDirectory>
						<lineNumber>57</lineNumber>
						<contextFuncName>conv_2d_buffer_resource_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;6, 0, AP_RND_CONV, AP_SAT, 0&amp;gt;, 4&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;19, 8, AP_TRN, AP_WRAP, 0&amp;gt;, 8&amp;gt;, config6&amp;gt;</contextFuncName>
						<contextNormFuncName>conv_2d_buffer_resource_cl_nnet_array_ap_ufixed_6_0_AP_RND_CONV_AP_SAT_0_4_nnet_array_ap_fixed_19_8_AP_TRN_AP_WRAP_0_8_config6_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/yvan/Bureau/Projekt/PA2/MNIST/model_personDetection/hls4ml_prj_qat</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
											<second>conv_2d_buffer_resource_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;6, 0, AP_RND_CONV, AP_SAT, 0&amp;gt;, 4&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;19, 8, AP_TRN, AP_WRAP, 0&amp;gt;, 8&amp;gt;, config6&amp;gt;</second>
										</first>
										<second>57</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>2974209936</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>55</count>
					<item_version>0</item_version>
					<item>117</item>
					<item>118</item>
					<item>119</item>
					<item>120</item>
					<item>121</item>
					<item>122</item>
					<item>126</item>
					<item>127</item>
					<item>128</item>
					<item>129</item>
					<item>130</item>
					<item>131</item>
					<item>132</item>
					<item>133</item>
					<item>134</item>
					<item>135</item>
					<item>136</item>
					<item>137</item>
					<item>138</item>
					<item>139</item>
					<item>140</item>
					<item>141</item>
					<item>142</item>
					<item>143</item>
					<item>144</item>
					<item>145</item>
					<item>146</item>
					<item>147</item>
					<item>148</item>
					<item>149</item>
					<item>150</item>
					<item>151</item>
					<item>152</item>
					<item>153</item>
					<item>154</item>
					<item>155</item>
					<item>156</item>
					<item>157</item>
					<item>158</item>
					<item>159</item>
					<item>160</item>
					<item>161</item>
					<item>162</item>
					<item>163</item>
					<item>164</item>
					<item>165</item>
					<item>166</item>
					<item>167</item>
					<item>168</item>
					<item>169</item>
					<item>170</item>
					<item>171</item>
					<item>172</item>
					<item>173</item>
					<item>174</item>
				</oprand_edges>
				<opcode>call</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>13</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_16">
				<Value>
					<Obj>
						<type>0</type>
						<id>72</id>
						<name>indvar_flatten_write_ln53</name>
						<fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
						<fileDirectory>/home/yvan/Bureau/Projekt/PA2/MNIST/model_personDetection/hls4ml_prj_qat</fileDirectory>
						<lineNumber>53</lineNumber>
						<contextFuncName>conv_2d_buffer_resource_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;6, 0, AP_RND_CONV, AP_SAT, 0&amp;gt;, 4&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;19, 8, AP_TRN, AP_WRAP, 0&amp;gt;, 8&amp;gt;, config6&amp;gt;</contextFuncName>
						<contextNormFuncName>conv_2d_buffer_resource_cl_nnet_array_ap_ufixed_6_0_AP_RND_CONV_AP_SAT_0_4_nnet_array_ap_fixed_19_8_AP_TRN_AP_WRAP_0_8_config6_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/yvan/Bureau/Projekt/PA2/MNIST/model_personDetection/hls4ml_prj_qat</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
											<second>conv_2d_buffer_resource_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;6, 0, AP_RND_CONV, AP_SAT, 0&amp;gt;, 4&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;19, 8, AP_TRN, AP_WRAP, 0&amp;gt;, 8&amp;gt;, config6&amp;gt;</second>
										</first>
										<second>53</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>2974209936</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>4</count>
					<item_version>0</item_version>
					<item>123</item>
					<item>124</item>
					<item>236</item>
					<item>237</item>
				</oprand_edges>
				<opcode>store</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>1.58</m_delay>
				<m_topoIndex>14</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_17">
				<Value>
					<Obj>
						<type>0</type>
						<id>73</id>
						<name>br_ln53</name>
						<fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
						<fileDirectory>/home/yvan/Bureau/Projekt/PA2/MNIST/model_personDetection/hls4ml_prj_qat</fileDirectory>
						<lineNumber>53</lineNumber>
						<contextFuncName>conv_2d_buffer_resource_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;6, 0, AP_RND_CONV, AP_SAT, 0&amp;gt;, 4&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;19, 8, AP_TRN, AP_WRAP, 0&amp;gt;, 8&amp;gt;, config6&amp;gt;</contextFuncName>
						<contextNormFuncName>conv_2d_buffer_resource_cl_nnet_array_ap_ufixed_6_0_AP_RND_CONV_AP_SAT_0_4_nnet_array_ap_fixed_19_8_AP_TRN_AP_WRAP_0_8_config6_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/yvan/Bureau/Projekt/PA2/MNIST/model_personDetection/hls4ml_prj_qat</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
											<second>conv_2d_buffer_resource_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;6, 0, AP_RND_CONV, AP_SAT, 0&amp;gt;, 4&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;19, 8, AP_TRN, AP_WRAP, 0&amp;gt;, 8&amp;gt;, config6&amp;gt;</second>
										</first>
										<second>53</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>2974209936</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>125</item>
				</oprand_edges>
				<opcode>br</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>16</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_18">
				<Value>
					<Obj>
						<type>0</type>
						<id>75</id>
						<name>_ln79</name>
						<fileName>firmware/nnet_utils/nnet_conv2d_stream.h</fileName>
						<fileDirectory>/home/yvan/Bureau/Projekt/PA2/MNIST/model_personDetection/hls4ml_prj_qat</fileDirectory>
						<lineNumber>79</lineNumber>
						<contextFuncName>conv_2d_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;6, 0, AP_RND_CONV, AP_SAT, 0&amp;gt;, 4&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;19, 8, AP_TRN, AP_WRAP, 0&amp;gt;, 8&amp;gt;, config6&amp;gt;</contextFuncName>
						<contextNormFuncName>conv_2d_cl_nnet_array_ap_ufixed_6_0_AP_RND_CONV_AP_SAT_0_4_nnet_array_ap_fixed_19_8_AP_TRN_AP_WRAP_0_8_config6_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/yvan/Bureau/Projekt/PA2/MNIST/model_personDetection/hls4ml_prj_qat</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>firmware/nnet_utils/nnet_conv2d_stream.h</first>
											<second>conv_2d_cl&amp;lt;nnet::array&amp;lt;ap_ufixed&amp;lt;6, 0, AP_RND_CONV, AP_SAT, 0&amp;gt;, 4&amp;gt;, nnet::array&amp;lt;ap_fixed&amp;lt;19, 8, AP_TRN, AP_WRAP, 0&amp;gt;, 8&amp;gt;, config6&amp;gt;</second>
										</first>
										<second>79</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>2974209936</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>0</count>
					<item_version>0</item_version>
				</oprand_edges>
				<opcode>ret</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>15</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
		</nodes>
		<consts class_id="15" tracking_level="0" version="0">
			<count>11</count>
			<item_version>0</item_version>
			<item class_id="16" tracking_level="1" version="0" object_id="_19">
				<Value>
					<Obj>
						<type>2</type>
						<id>77</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>2974131568</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>1</content>
			</item>
			<item class_id_reference="16" object_id="_20">
				<Value>
					<Obj>
						<type>2</type>
						<id>79</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>2847316136</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>6</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>0</content>
			</item>
			<item class_id_reference="16" object_id="_21">
				<Value>
					<Obj>
						<type>2</type>
						<id>85</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>1630019628</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>6</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>36</content>
			</item>
			<item class_id_reference="16" object_id="_22">
				<Value>
					<Obj>
						<type>2</type>
						<id>88</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>2974209936</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>6</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>1</content>
			</item>
			<item class_id_reference="16" object_id="_23">
				<Value>
					<Obj>
						<type>2</type>
						<id>100</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>2974209936</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>12</content>
			</item>
			<item class_id_reference="16" object_id="_24">
				<Value>
					<Obj>
						<type>2</type>
						<id>102</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>2974209936</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>17</content>
			</item>
			<item class_id_reference="16" object_id="_25">
				<Value>
					<Obj>
						<type>2</type>
						<id>106</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>2974152528</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>18</content>
			</item>
			<item class_id_reference="16" object_id="_26">
				<Value>
					<Obj>
						<type>2</type>
						<id>108</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>2971495776</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>23</content>
			</item>
			<item class_id_reference="16" object_id="_27">
				<Value>
					<Obj>
						<type>2</type>
						<id>112</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>2972932000</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>6</content>
			</item>
			<item class_id_reference="16" object_id="_28">
				<Value>
					<Obj>
						<type>2</type>
						<id>114</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>2970878832</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>11</content>
			</item>
			<item class_id_reference="16" object_id="_29">
				<Value>
					<Obj>
						<type>2</type>
						<id>116</id>
						<name>compute_output_buffer_2d_array_array_ap_fixed_19_8_5_3_0_8u_config6_s</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>2971839808</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<const_type>6</const_type>
				<content>&lt;constant:compute_output_buffer_2d&lt;array,array&lt;ap_fixed&lt;19,8,5,3,0&gt;,8u&gt;,config6&gt;&gt;</content>
			</item>
		</consts>
		<blocks class_id="17" tracking_level="0" version="0">
			<count>4</count>
			<item_version>0</item_version>
			<item class_id="18" tracking_level="1" version="0" object_id="_30">
				<Obj>
					<type>3</type>
					<id>57</id>
					<name>entry</name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<contextNormFuncName></contextNormFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<control></control>
					<opType></opType>
					<implIndex></implIndex>
					<coreName></coreName>
					<isStorage>0</isStorage>
					<storageDepth>0</storageDepth>
					<coreId>874523710</coreId>
					<rtlModuleName></rtlModuleName>
				</Obj>
				<node_objs>
					<count>3</count>
					<item_version>0</item_version>
					<item>52</item>
					<item>55</item>
					<item>56</item>
				</node_objs>
			</item>
			<item class_id_reference="18" object_id="_31">
				<Obj>
					<type>3</type>
					<id>62</id>
					<name>for.inc.i</name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<contextNormFuncName></contextNormFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<control></control>
					<opType></opType>
					<implIndex></implIndex>
					<coreName></coreName>
					<isStorage>0</isStorage>
					<storageDepth>0</storageDepth>
					<coreId>1966350380</coreId>
					<rtlModuleName></rtlModuleName>
				</Obj>
				<node_objs>
					<count>4</count>
					<item_version>0</item_version>
					<item>58</item>
					<item>59</item>
					<item>60</item>
					<item>61</item>
				</node_objs>
			</item>
			<item class_id_reference="18" object_id="_32">
				<Obj>
					<type>3</type>
					<id>74</id>
					<name>for.inc13.i</name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<contextNormFuncName></contextNormFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<control></control>
					<opType></opType>
					<implIndex></implIndex>
					<coreName></coreName>
					<isStorage>0</isStorage>
					<storageDepth>0</storageDepth>
					<coreId>1047868448</coreId>
					<rtlModuleName></rtlModuleName>
				</Obj>
				<node_objs>
					<count>8</count>
					<item_version>0</item_version>
					<item>66</item>
					<item>67</item>
					<item>68</item>
					<item>69</item>
					<item>70</item>
					<item>71</item>
					<item>72</item>
					<item>73</item>
				</node_objs>
			</item>
			<item class_id_reference="18" object_id="_33">
				<Obj>
					<type>3</type>
					<id>76</id>
					<name>_ZN4nnet26conv_2d_buffer_resource_clINS_5arrayI9ap_ufixedILi6ELi0EL9ap_q_mode4EL9ap_o_mode0ELi0EELj4EEENS1_I8ap_fixedILi19ELi8ELS3_5ELS4_3ELi0EELj8EEE7config6EEvRN3hls6streamIT_Li0EEERNSC_IT0_Li0EEEPNT1_8weight_tEPNSJ_6bias_tE.exit</name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<contextNormFuncName></contextNormFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<control></control>
					<opType></opType>
					<implIndex></implIndex>
					<coreName></coreName>
					<isStorage>0</isStorage>
					<storageDepth>0</storageDepth>
					<coreId>1966350380</coreId>
					<rtlModuleName></rtlModuleName>
				</Obj>
				<node_objs>
					<count>1</count>
					<item_version>0</item_version>
					<item>75</item>
				</node_objs>
			</item>
		</blocks>
		<edges class_id="19" tracking_level="0" version="0">
			<count>88</count>
			<item_version>0</item_version>
			<item class_id="20" tracking_level="1" version="0" object_id="_34">
				<id>78</id>
				<edge_type>1</edge_type>
				<source_obj>77</source_obj>
				<sink_obj>52</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_35">
				<id>80</id>
				<edge_type>1</edge_type>
				<source_obj>79</source_obj>
				<sink_obj>55</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_36">
				<id>81</id>
				<edge_type>1</edge_type>
				<source_obj>52</source_obj>
				<sink_obj>55</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_37">
				<id>82</id>
				<edge_type>2</edge_type>
				<source_obj>62</source_obj>
				<sink_obj>56</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_38">
				<id>83</id>
				<edge_type>1</edge_type>
				<source_obj>52</source_obj>
				<sink_obj>58</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_39">
				<id>84</id>
				<edge_type>1</edge_type>
				<source_obj>58</source_obj>
				<sink_obj>59</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_40">
				<id>86</id>
				<edge_type>1</edge_type>
				<source_obj>85</source_obj>
				<sink_obj>59</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_41">
				<id>87</id>
				<edge_type>1</edge_type>
				<source_obj>58</source_obj>
				<sink_obj>60</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_42">
				<id>89</id>
				<edge_type>1</edge_type>
				<source_obj>88</source_obj>
				<sink_obj>60</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_43">
				<id>90</id>
				<edge_type>1</edge_type>
				<source_obj>59</source_obj>
				<sink_obj>61</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_44">
				<id>91</id>
				<edge_type>2</edge_type>
				<source_obj>74</source_obj>
				<sink_obj>61</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_45">
				<id>92</id>
				<edge_type>2</edge_type>
				<source_obj>76</source_obj>
				<sink_obj>61</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_46">
				<id>95</id>
				<edge_type>1</edge_type>
				<source_obj>1</source_obj>
				<sink_obj>66</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_47">
				<id>96</id>
				<edge_type>1</edge_type>
				<source_obj>66</source_obj>
				<sink_obj>67</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_48">
				<id>99</id>
				<edge_type>1</edge_type>
				<source_obj>66</source_obj>
				<sink_obj>68</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_49">
				<id>101</id>
				<edge_type>1</edge_type>
				<source_obj>100</source_obj>
				<sink_obj>68</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_50">
				<id>103</id>
				<edge_type>1</edge_type>
				<source_obj>102</source_obj>
				<sink_obj>68</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_51">
				<id>105</id>
				<edge_type>1</edge_type>
				<source_obj>66</source_obj>
				<sink_obj>69</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_52">
				<id>107</id>
				<edge_type>1</edge_type>
				<source_obj>106</source_obj>
				<sink_obj>69</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_53">
				<id>109</id>
				<edge_type>1</edge_type>
				<source_obj>108</source_obj>
				<sink_obj>69</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_54">
				<id>111</id>
				<edge_type>1</edge_type>
				<source_obj>66</source_obj>
				<sink_obj>70</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_55">
				<id>113</id>
				<edge_type>1</edge_type>
				<source_obj>112</source_obj>
				<sink_obj>70</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_56">
				<id>115</id>
				<edge_type>1</edge_type>
				<source_obj>114</source_obj>
				<sink_obj>70</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_57">
				<id>117</id>
				<edge_type>1</edge_type>
				<source_obj>116</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_58">
				<id>118</id>
				<edge_type>1</edge_type>
				<source_obj>67</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_59">
				<id>119</id>
				<edge_type>1</edge_type>
				<source_obj>70</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_60">
				<id>120</id>
				<edge_type>1</edge_type>
				<source_obj>68</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_61">
				<id>121</id>
				<edge_type>1</edge_type>
				<source_obj>69</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_62">
				<id>122</id>
				<edge_type>1</edge_type>
				<source_obj>2</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_63">
				<id>123</id>
				<edge_type>1</edge_type>
				<source_obj>60</source_obj>
				<sink_obj>72</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_64">
				<id>124</id>
				<edge_type>1</edge_type>
				<source_obj>52</source_obj>
				<sink_obj>72</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_65">
				<id>125</id>
				<edge_type>2</edge_type>
				<source_obj>62</source_obj>
				<sink_obj>73</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_66">
				<id>126</id>
				<edge_type>1</edge_type>
				<source_obj>3</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_67">
				<id>127</id>
				<edge_type>1</edge_type>
				<source_obj>4</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_68">
				<id>128</id>
				<edge_type>1</edge_type>
				<source_obj>5</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_69">
				<id>129</id>
				<edge_type>1</edge_type>
				<source_obj>6</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_70">
				<id>130</id>
				<edge_type>1</edge_type>
				<source_obj>7</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_71">
				<id>131</id>
				<edge_type>1</edge_type>
				<source_obj>8</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_72">
				<id>132</id>
				<edge_type>1</edge_type>
				<source_obj>9</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_73">
				<id>133</id>
				<edge_type>1</edge_type>
				<source_obj>10</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_74">
				<id>134</id>
				<edge_type>1</edge_type>
				<source_obj>11</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_75">
				<id>135</id>
				<edge_type>1</edge_type>
				<source_obj>12</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_76">
				<id>136</id>
				<edge_type>1</edge_type>
				<source_obj>13</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_77">
				<id>137</id>
				<edge_type>1</edge_type>
				<source_obj>14</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_78">
				<id>138</id>
				<edge_type>1</edge_type>
				<source_obj>15</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_79">
				<id>139</id>
				<edge_type>1</edge_type>
				<source_obj>16</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_80">
				<id>140</id>
				<edge_type>1</edge_type>
				<source_obj>17</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_81">
				<id>141</id>
				<edge_type>1</edge_type>
				<source_obj>18</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_82">
				<id>142</id>
				<edge_type>1</edge_type>
				<source_obj>19</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_83">
				<id>143</id>
				<edge_type>1</edge_type>
				<source_obj>20</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_84">
				<id>144</id>
				<edge_type>1</edge_type>
				<source_obj>21</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_85">
				<id>145</id>
				<edge_type>1</edge_type>
				<source_obj>22</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_86">
				<id>146</id>
				<edge_type>1</edge_type>
				<source_obj>23</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_87">
				<id>147</id>
				<edge_type>1</edge_type>
				<source_obj>24</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_88">
				<id>148</id>
				<edge_type>1</edge_type>
				<source_obj>25</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_89">
				<id>149</id>
				<edge_type>1</edge_type>
				<source_obj>26</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_90">
				<id>150</id>
				<edge_type>1</edge_type>
				<source_obj>27</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_91">
				<id>151</id>
				<edge_type>1</edge_type>
				<source_obj>28</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_92">
				<id>152</id>
				<edge_type>1</edge_type>
				<source_obj>29</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_93">
				<id>153</id>
				<edge_type>1</edge_type>
				<source_obj>30</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_94">
				<id>154</id>
				<edge_type>1</edge_type>
				<source_obj>31</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_95">
				<id>155</id>
				<edge_type>1</edge_type>
				<source_obj>32</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_96">
				<id>156</id>
				<edge_type>1</edge_type>
				<source_obj>33</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_97">
				<id>157</id>
				<edge_type>1</edge_type>
				<source_obj>34</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_98">
				<id>158</id>
				<edge_type>1</edge_type>
				<source_obj>35</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_99">
				<id>159</id>
				<edge_type>1</edge_type>
				<source_obj>36</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_100">
				<id>160</id>
				<edge_type>1</edge_type>
				<source_obj>37</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_101">
				<id>161</id>
				<edge_type>1</edge_type>
				<source_obj>38</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_102">
				<id>162</id>
				<edge_type>1</edge_type>
				<source_obj>39</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_103">
				<id>163</id>
				<edge_type>1</edge_type>
				<source_obj>40</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_104">
				<id>164</id>
				<edge_type>1</edge_type>
				<source_obj>41</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_105">
				<id>165</id>
				<edge_type>1</edge_type>
				<source_obj>42</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_106">
				<id>166</id>
				<edge_type>1</edge_type>
				<source_obj>43</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_107">
				<id>167</id>
				<edge_type>1</edge_type>
				<source_obj>44</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_108">
				<id>168</id>
				<edge_type>1</edge_type>
				<source_obj>45</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_109">
				<id>169</id>
				<edge_type>1</edge_type>
				<source_obj>46</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_110">
				<id>170</id>
				<edge_type>1</edge_type>
				<source_obj>47</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_111">
				<id>171</id>
				<edge_type>1</edge_type>
				<source_obj>48</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_112">
				<id>172</id>
				<edge_type>1</edge_type>
				<source_obj>49</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_113">
				<id>173</id>
				<edge_type>1</edge_type>
				<source_obj>50</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_114">
				<id>174</id>
				<edge_type>1</edge_type>
				<source_obj>51</source_obj>
				<sink_obj>71</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_115">
				<id>231</id>
				<edge_type>2</edge_type>
				<source_obj>57</source_obj>
				<sink_obj>62</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_116">
				<id>232</id>
				<edge_type>2</edge_type>
				<source_obj>62</source_obj>
				<sink_obj>76</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_117">
				<id>233</id>
				<edge_type>2</edge_type>
				<source_obj>62</source_obj>
				<sink_obj>74</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_118">
				<id>234</id>
				<edge_type>2</edge_type>
				<source_obj>74</source_obj>
				<sink_obj>62</sink_obj>
				<is_back_edge>1</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_119">
				<id>235</id>
				<edge_type>4</edge_type>
				<source_obj>55</source_obj>
				<sink_obj>58</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_120">
				<id>236</id>
				<edge_type>4</edge_type>
				<source_obj>55</source_obj>
				<sink_obj>72</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_121">
				<id>237</id>
				<edge_type>4</edge_type>
				<source_obj>58</source_obj>
				<sink_obj>72</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
		</edges>
	</cdfg>
	<cdfg_regions class_id="21" tracking_level="0" version="0">
		<count>4</count>
		<item_version>0</item_version>
		<item class_id="22" tracking_level="1" version="0" object_id="_122">
			<mId>1</mId>
			<mTag>conv_2d_cl&lt;array&lt;ap_ufixed,4u&gt;,array&lt;ap_fixed&lt;19,8,5,3,0&gt;,8u&gt;,config6&gt;</mTag>
			<mNormTag>conv_2d_cl_array_ap_ufixed_4u_array_ap_fixed_19_8_5_3_0_8u_config6_s</mNormTag>
			<mType>0</mType>
			<sub_regions>
				<count>3</count>
				<item_version>0</item_version>
				<item>2</item>
				<item>3</item>
				<item>4</item>
			</sub_regions>
			<basic_blocks>
				<count>0</count>
				<item_version>0</item_version>
			</basic_blocks>
			<mII>-1</mII>
			<mDepth>-1</mDepth>
			<mMinTripCount>-1</mMinTripCount>
			<mMaxTripCount>-1</mMaxTripCount>
			<mMinLatency>253</mMinLatency>
			<mMaxLatency>865</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
		<item class_id_reference="22" object_id="_123">
			<mId>2</mId>
			<mTag>Entry</mTag>
			<mNormTag>Entry</mNormTag>
			<mType>0</mType>
			<sub_regions>
				<count>0</count>
				<item_version>0</item_version>
			</sub_regions>
			<basic_blocks>
				<count>1</count>
				<item_version>0</item_version>
				<item>57</item>
			</basic_blocks>
			<mII>-1</mII>
			<mDepth>-1</mDepth>
			<mMinTripCount>-1</mMinTripCount>
			<mMaxTripCount>-1</mMaxTripCount>
			<mMinLatency>0</mMinLatency>
			<mMaxLatency>0</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
		<item class_id_reference="22" object_id="_124">
			<mId>3</mId>
			<mTag>ReadInputHeight_ReadInputWidth</mTag>
			<mNormTag>ReadInputHeight_ReadInputWidth</mNormTag>
			<mType>1</mType>
			<sub_regions>
				<count>0</count>
				<item_version>0</item_version>
			</sub_regions>
			<basic_blocks>
				<count>2</count>
				<item_version>0</item_version>
				<item>62</item>
				<item>74</item>
			</basic_blocks>
			<mII>-1</mII>
			<mDepth>-1</mDepth>
			<mMinTripCount>36</mMinTripCount>
			<mMaxTripCount>36</mMaxTripCount>
			<mMinLatency>252</mMinLatency>
			<mMaxLatency>864</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
		<item class_id_reference="22" object_id="_125">
			<mId>4</mId>
			<mTag>Return</mTag>
			<mNormTag>Return</mNormTag>
			<mType>0</mType>
			<sub_regions>
				<count>0</count>
				<item_version>0</item_version>
			</sub_regions>
			<basic_blocks>
				<count>1</count>
				<item_version>0</item_version>
				<item>76</item>
			</basic_blocks>
			<mII>-1</mII>
			<mDepth>-1</mDepth>
			<mMinTripCount>-1</mMinTripCount>
			<mMaxTripCount>-1</mMaxTripCount>
			<mMinLatency>0</mMinLatency>
			<mMaxLatency>0</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
	</cdfg_regions>
	<fsm class_id="-1"></fsm>
	<res class_id="-1"></res>
	<node_label_latency class_id="26" tracking_level="0" version="0">
		<count>16</count>
		<item_version>0</item_version>
		<item class_id="27" tracking_level="0" version="0">
			<first>52</first>
			<second class_id="28" tracking_level="0" version="0">
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>55</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>56</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>58</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>59</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>60</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>61</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>66</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>67</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>68</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>69</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>70</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>71</first>
			<second>
				<first>1</first>
				<second>1</second>
			</second>
		</item>
		<item>
			<first>72</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>73</first>
			<second>
				<first>2</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>75</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
	</node_label_latency>
	<bblk_ent_exit class_id="29" tracking_level="0" version="0">
		<count>4</count>
		<item_version>0</item_version>
		<item class_id="30" tracking_level="0" version="0">
			<first>57</first>
			<second class_id="31" tracking_level="0" version="0">
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>62</first>
			<second>
				<first>1</first>
				<second>1</second>
			</second>
		</item>
		<item>
			<first>74</first>
			<second>
				<first>1</first>
				<second>2</second>
			</second>
		</item>
		<item>
			<first>76</first>
			<second>
				<first>1</first>
				<second>1</second>
			</second>
		</item>
	</bblk_ent_exit>
	<regions class_id="32" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</regions>
	<dp_fu_nodes class_id="33" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes>
	<dp_fu_nodes_expression class_id="34" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes_expression>
	<dp_fu_nodes_module>
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes_module>
	<dp_fu_nodes_io>
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes_io>
	<return_ports>
		<count>0</count>
		<item_version>0</item_version>
	</return_ports>
	<dp_mem_port_nodes class_id="35" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_mem_port_nodes>
	<dp_reg_nodes>
		<count>0</count>
		<item_version>0</item_version>
	</dp_reg_nodes>
	<dp_regname_nodes>
		<count>0</count>
		<item_version>0</item_version>
	</dp_regname_nodes>
	<dp_reg_phi>
		<count>0</count>
		<item_version>0</item_version>
	</dp_reg_phi>
	<dp_regname_phi>
		<count>0</count>
		<item_version>0</item_version>
	</dp_regname_phi>
	<dp_port_io_nodes class_id="36" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_port_io_nodes>
	<port2core>
		<count>0</count>
		<item_version>0</item_version>
	</port2core>
	<node2core>
		<count>0</count>
		<item_version>0</item_version>
	</node2core>
</syndb>
</boost_serialization>

