// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_27_11_5_3_0_4u_config2_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer18_out_dout,
        layer18_out_num_data_valid,
        layer18_out_fifo_cap,
        layer18_out_empty_n,
        layer18_out_read,
        layer2_out_din,
        layer2_out_num_data_valid,
        layer2_out_fifo_cap,
        layer2_out_full_n,
        layer2_out_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [15:0] layer18_out_dout;
input  [7:0] layer18_out_num_data_valid;
input  [7:0] layer18_out_fifo_cap;
input   layer18_out_empty_n;
output   layer18_out_read;
output  [107:0] layer2_out_din;
input  [6:0] layer2_out_num_data_valid;
input  [6:0] layer2_out_fifo_cap;
input   layer2_out_full_n;
output   layer2_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer18_out_read;
reg layer2_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer18_out_blk_n;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln51_fu_126_p2;
reg   [15:0] layer18_out_read_reg_153;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_27_11_5_3_0_4u_config2_s_fu_78_ap_start;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_27_11_5_3_0_4u_config2_s_fu_78_ap_done;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_27_11_5_3_0_4u_config2_s_fu_78_ap_idle;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_27_11_5_3_0_4u_config2_s_fu_78_ap_ready;
wire   [107:0] grp_compute_output_buffer_2d_array_array_ap_fixed_27_11_5_3_0_4u_config2_s_fu_78_layer2_out_din;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_27_11_5_3_0_4u_config2_s_fu_78_layer2_out_write;
reg    grp_compute_output_buffer_2d_array_array_ap_fixed_27_11_5_3_0_4u_config2_s_fu_78_ap_start_reg;
reg    ap_block_state2_ignore_call4;
wire    ap_CS_fsm_state3;
reg   [6:0] indvar_flatten_fu_68;
wire   [6:0] add_ln51_fu_132_p2;
reg    ap_block_state2;
reg    ap_block_state1;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_compute_output_buffer_2d_array_array_ap_fixed_27_11_5_3_0_4u_config2_s_fu_78_ap_start_reg = 1'b0;
end

myproject_compute_output_buffer_2d_array_array_ap_fixed_27_11_5_3_0_4u_config2_s grp_compute_output_buffer_2d_array_array_ap_fixed_27_11_5_3_0_4u_config2_s_fu_78(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_output_buffer_2d_array_array_ap_fixed_27_11_5_3_0_4u_config2_s_fu_78_ap_start),
    .ap_done(grp_compute_output_buffer_2d_array_array_ap_fixed_27_11_5_3_0_4u_config2_s_fu_78_ap_done),
    .ap_idle(grp_compute_output_buffer_2d_array_array_ap_fixed_27_11_5_3_0_4u_config2_s_fu_78_ap_idle),
    .ap_ready(grp_compute_output_buffer_2d_array_array_ap_fixed_27_11_5_3_0_4u_config2_s_fu_78_ap_ready),
    .p_read(layer18_out_read_reg_153),
    .layer2_out_din(grp_compute_output_buffer_2d_array_array_ap_fixed_27_11_5_3_0_4u_config2_s_fu_78_layer2_out_din),
    .layer2_out_num_data_valid(7'd0),
    .layer2_out_fifo_cap(7'd0),
    .layer2_out_full_n(layer2_out_full_n),
    .layer2_out_write(grp_compute_output_buffer_2d_array_array_ap_fixed_27_11_5_3_0_4u_config2_s_fu_78_layer2_out_write)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((icmp_ln51_fu_126_p2 == 1'd0) & (layer18_out_empty_n == 1'b0)) & (icmp_ln51_fu_126_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_output_buffer_2d_array_array_ap_fixed_27_11_5_3_0_4u_config2_s_fu_78_ap_start_reg <= 1'b0;
    end else begin
        if ((~((icmp_ln51_fu_126_p2 == 1'd0) & (layer18_out_empty_n == 1'b0)) & (icmp_ln51_fu_126_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_compute_output_buffer_2d_array_array_ap_fixed_27_11_5_3_0_4u_config2_s_fu_78_ap_start_reg <= 1'b1;
        end else if ((grp_compute_output_buffer_2d_array_array_ap_fixed_27_11_5_3_0_4u_config2_s_fu_78_ap_ready == 1'b1)) begin
            grp_compute_output_buffer_2d_array_array_ap_fixed_27_11_5_3_0_4u_config2_s_fu_78_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_fu_68 <= 7'd0;
    end else if ((~((icmp_ln51_fu_126_p2 == 1'd0) & (layer18_out_empty_n == 1'b0)) & (icmp_ln51_fu_126_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        indvar_flatten_fu_68 <= add_ln51_fu_132_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln51_fu_126_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        layer18_out_read_reg_153 <= layer18_out_dout;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln51_fu_126_p2 == 1'd0) & (layer18_out_empty_n == 1'b0))) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_compute_output_buffer_2d_array_array_ap_fixed_27_11_5_3_0_4u_config2_s_fu_78_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((icmp_ln51_fu_126_p2 == 1'd0) & (layer18_out_empty_n == 1'b0)) & (icmp_ln51_fu_126_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((icmp_ln51_fu_126_p2 == 1'd0) & (layer18_out_empty_n == 1'b0)) & (icmp_ln51_fu_126_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln51_fu_126_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        layer18_out_blk_n = layer18_out_empty_n;
    end else begin
        layer18_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((icmp_ln51_fu_126_p2 == 1'd0) & (layer18_out_empty_n == 1'b0)) & (icmp_ln51_fu_126_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        layer18_out_read = 1'b1;
    end else begin
        layer18_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        layer2_out_write = grp_compute_output_buffer_2d_array_array_ap_fixed_27_11_5_3_0_4u_config2_s_fu_78_layer2_out_write;
    end else begin
        layer2_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~((icmp_ln51_fu_126_p2 == 1'd0) & (layer18_out_empty_n == 1'b0)) & (icmp_ln51_fu_126_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if ((~((icmp_ln51_fu_126_p2 == 1'd0) & (layer18_out_empty_n == 1'b0)) & (icmp_ln51_fu_126_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_compute_output_buffer_2d_array_array_ap_fixed_27_11_5_3_0_4u_config2_s_fu_78_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln51_fu_132_p2 = (indvar_flatten_fu_68 + 7'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2 = ((icmp_ln51_fu_126_p2 == 1'd0) & (layer18_out_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state2_ignore_call4 = ((icmp_ln51_fu_126_p2 == 1'd0) & (layer18_out_empty_n == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign grp_compute_output_buffer_2d_array_array_ap_fixed_27_11_5_3_0_4u_config2_s_fu_78_ap_start = grp_compute_output_buffer_2d_array_array_ap_fixed_27_11_5_3_0_4u_config2_s_fu_78_ap_start_reg;

assign icmp_ln51_fu_126_p2 = ((indvar_flatten_fu_68 == 7'd100) ? 1'b1 : 1'b0);

assign layer2_out_din = grp_compute_output_buffer_2d_array_array_ap_fixed_27_11_5_3_0_4u_config2_s_fu_78_layer2_out_din;

assign start_out = real_start;

endmodule //myproject_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_27_11_5_3_0_4u_config2_s
